/** Seeded surface hair, parallel-transport curve tubes, deterministic particle
 * emitters and fixed-step ballistic collision integration. */
import {add,sub,mul,cross,dot,normalize} from '../core/math.js';
import {triangulate,vertex,normals,cloneMesh} from '../geometry/mesh.js';
import {seededRandom,XPBD} from './physics.js';
function perpendicular(n){return normalize(cross(Math.abs(n[1])<.9?[0,1,0]:[1,0,0],n));}
export function generateHair(mesh,{count=200,length=.4,segments=6,seed=1,clump=0,curl=0,gravity=.1}={}){if(!Number.isInteger(count)||count<1||count>30000||segments<1||segments>128||length<=0)throw Error('Invalid hair settings');const rand=seededRandom(seed),tris=triangulate(mesh),areas=[],ns=normals(mesh);let total=0;for(const t of tris){const [a,b,c]=t.ids.map(i=>vertex(mesh,i));total+=Math.hypot(...cross(sub(b,a),sub(c,a)))*.5;areas.push(total);}if(total<=0)throw Error('Hair needs a nonzero surface area');const curves=[];for(let i=0;i<count;i++){const r=rand()*total;let lo=0,hi=areas.length-1;while(lo<hi){const mid=(lo+hi)>>1;areas[mid]<r?lo=mid+1:hi=mid;}const ids=tris[lo].ids,s=Math.sqrt(rand()),v=rand(),weights=[1-s,s*(1-v),s*v],root=[0,0,0],n=[0,0,0];for(let k=0;k<3;k++){const p=vertex(mesh,ids[k]);for(let a=0;a<3;a++){root[a]+=p[a]*weights[k];n[a]+=ns[ids[k]*3+a]*weights[k];}}const normal=normalize(n),u=perpendicular(normal),vv=cross(normal,u),phase=rand()*Math.PI*2,l=length*(.75+.5*rand()),points=[];for(let j=0;j<=segments;j++){const t=j/segments,angle=phase+t*Math.PI*4,p=add(root,mul(normal,l*t));p[0]-=root[0]*clump*t*t;p[2]-=root[2]*clump*t*t;p[1]-=gravity*l*t*t;for(let k=0;k<3;k++)p[k]+=curl*l*t*(u[k]*Math.sin(angle)+vv[k]*Math.cos(angle));points.push(p);}curves.push({points,rootTriangle:lo,barycentric:weights});}return curves;}
export function curvesToMesh(curves,{radius=.008,sides=4,taper=.9}={}){if(radius<=0||sides<3||sides>32)throw Error('Invalid curve tessellation');const out={positions:[],uvs:[],faces:[],smooth:true};for(const curve of curves){const points=curve.points||curve;if(points.length<2)continue;const base=out.positions.length/3;let lastU=null;for(let i=0;i<points.length;i++){const n=normalize(sub(points[Math.min(i+1,points.length-1)],points[Math.max(0,i-1)])),u=lastU?normalize(sub(lastU,mul(n,dot(lastU,n)))):perpendicular(n),U=Math.hypot(...u)<.1?perpendicular(n):u,v=cross(n,U);lastU=U;const t=i/(points.length-1),r=radius*Math.max(.02,1-t*taper);for(let j=0;j<sides;j++){const a=j/sides*Math.PI*2;out.positions.push(...points[i].map((p,k)=>p+r*(U[k]*Math.cos(a)+v[k]*Math.sin(a))));out.uvs.push(j/sides,t);}if(i)for(let j=0;j<sides;j++){const a=base+(i-1)*sides+j,b=base+(i-1)*sides+(j+1)%sides;out.faces.push([a,b,b+sides,a+sides]);}}out.faces.push(Array.from({length:sides},(_,j)=>base+sides-1-j));const end=base+(points.length-1)*sides;out.faces.push(Array.from({length:sides},(_,j)=>end+j));}return out;}
export function simulateHair(curves,time,{gravity=[0,-9.81,0],compliance=1e-7,floor=-100,damping=2}={}){const p=[],pins=[],links=[];for(const curve of curves){const ps=curve.points||curve,pbase=p.length/3;pins.push(pbase);p.push(...ps.flat());for(let i=1;i<ps.length;i++)links.push([pbase+i-1,pbase+i]);}const solver=new XPBD(p,{pins,gravity,compliance,floor,damping,iterations:8,substeps:2});for(const l of links)solver.distance(...l);for(let t=0;t<time-1e-10;t+=1/60)solver.step(Math.min(1/60,time-t));let offset=0;return curves.map(c=>{const n=(c.points||c).length,points=Array.from({length:n},(_,i)=>Array.from(solver.positions.slice((offset+i)*3,(offset+i+1)*3)));offset+=n;return {points};});}
export function sampleParticles({rate=50,lifetime=3,seed=1,speed=2,spread=.7,gravity=[0,-9.81,0],origin=[0,1,0],direction=[0,1,0],floor=0,restitution=.45,radius=.035,maxParticles=20000}={},time=0){if(rate<=0||lifetime<=0||!Number.isFinite(time)||maxParticles>100000)throw Error('Invalid emitter settings');const last=Math.floor(time*rate),first=Math.max(0,Math.ceil((time-lifetime)*rate));if(last-first>maxParticles)throw Error('Particle budget exceeded');const out=[];for(let id=first;id<=last;id++){const birth=id/rate,age=time-birth;if(age<0||age>lifetime)continue;const rand=seededRandom((seed+Math.imul(id+1,2654435761))>>>0),dir=normalize(direction.map(v=>v+(rand()-.5)*spread*2));let p=[...origin],vel=mul(dir,speed*(.8+.4*rand()));for(let t=0;t<age-1e-10;t+=1/120){const dt=Math.min(1/120,age-t);p=add(p,add(mul(vel,dt),mul(gravity,.5*dt*dt)));vel=add(vel,mul(gravity,dt));if(p[1]<floor+radius){p[1]=floor+radius;if(vel[1]<0)vel[1]*=-restitution;vel[0]*=.99;vel[2]*=.99;}}out.push({id,position:p,velocity:vel,age,radius});}return out;}
export function particlesToMesh(particles){const m={positions:[],uvs:[],faces:[],smooth:true},unit=[[1,0,0],[-1,0,0],[0,1,0],[0,-1,0],[0,0,1],[0,0,-1]],fs=[[0,2,4],[4,2,1],[1,2,5],[5,2,0],[4,3,0],[1,3,4],[5,3,1],[0,3,5]];for(const p of particles){const base=m.positions.length/3;for(const v of unit){m.positions.push(...add(p.position,mul(v,p.radius)));m.uvs.push(v[0]*.5+.5,v[1]*.5+.5);}for(const f of fs)m.faces.push(f.map(i=>i+base));}return m;}
