/** Brush-authored guide offsets in emitter-local space. Roots remain surface
 * attached; deformed emitters carry the guides through their tangent frames.
 * A groom stores explicit curves, not a history of UI commands.
 */
import {add,sub,mul,dot,cross,normalize,clamp} from '../core/math.js';
import {generateHair} from './curves.js';
import {triangulate,vertex} from '../geometry/mesh.js';

function surfaceBinding(mesh,guide,tris=triangulate(mesh)){
 const triangle=tris[guide.rootTriangle];
 if(!triangle||guide.barycentric?.length!==3||guide.barycentric.some(x=>!Number.isFinite(x)||x<0)||Math.abs(guide.barycentric.reduce((a,b)=>a+b,0)-1)>1e-6)throw Error('Groom root binding is invalid for this emitter topology');
 const points=triangle.ids.map(i=>vertex(mesh,i)),t=normalize(sub(points[1],points[0])),n=normalize(cross(t,sub(points[2],points[0])));
 if(Math.hypot(...n)<.5)throw Error('Groom root is on a degenerate face');
 return {root:[0,1,2].map(k=>points.reduce((a,p,i)=>a+p[k]*guide.barycentric[i],0)),frame:[t,cross(n,t),n]};
}

export function createGroom(mesh,options={}){const guides=generateHair(mesh,{...options,count:Math.min(options.count??64,1024)}),triangles=triangulate(mesh);return {version:1,guides:guides.map(g=>({rootTriangle:g.rootTriangle,barycentric:g.barycentric,points:g.points.map(p=>[...p]),radius:options.radius??.008,frame:frame(g.points),surfaceFrame:surfaceBinding(mesh,g,triangles).frame})),seed:options.seed??12};}
export function validateGroom(g){if(g?.version!==1||!Array.isArray(g.guides)||g.guides.length>2048)throw Error('Invalid groom');let count=0;for(const guide of g.guides){if(!Array.isArray(guide.points)||guide.points.length<2||guide.points.length>256||guide.points.some(p=>p.length!==3||p.some(x=>!Number.isFinite(x)))||guide.radius<=0||!Number.isFinite(guide.radius)||!Number.isInteger(guide.rootTriangle)||guide.rootTriangle<0||guide.barycentric?.length!==3||guide.barycentric.some(x=>!Number.isFinite(x)||x<0)||Math.abs(guide.barycentric.reduce((a,b)=>a+b,0)-1)>1e-6||[guide.frame,guide.surfaceFrame].some(F=>F&&(F.length!==3||F.some(a=>a.length!==3||a.some(x=>!Number.isFinite(x))))))throw Error('Invalid guide curve');count+=guide.points.length;}if(count>262144)throw Error('Groom exceeds guide point budget');return g;}
const frame=points=>{const t=normalize(sub(points[1],points[0])),b=normalize(cross(Math.abs(t[1])<.9?[0,1,0]:[1,0,0],t)),n=cross(t,b);return [b,n,t];};
const local=(p,F)=>F.map(a=>dot(p,a));
const world=(p,F)=>add(add(mul(F[0],p[0]),mul(F[1],p[1])),mul(F[2],p[2]));
export function applyGroom(curves,groom,{neighbors=4,influence=1,emitter=null}={}){validateGroom(groom);if(!Number.isInteger(neighbors)||neighbors<1||neighbors>16||!Number.isFinite(influence)||influence<0||influence>1)throw Error('Invalid groom interpolation');const emitterTriangles=emitter?triangulate(emitter):null;const moved=emitter?groom.guides.map(g=>{const binding=surfaceBinding(emitter,g,emitterTriangles),old=g.surfaceFrame||g.frame||frame(g.points),F=g.frame||frame(g.points);return {...g,points:g.points.map(p=>add(binding.root,world(local(sub(p,g.points[0]),old),binding.frame))),frame:F.map(a=>world(local(a,old),binding.frame))};}):groom.guides;return curves.map(curve=>{const root=curve.points[0],F=frame(curve.points),nearest=moved.map(g=>({g,d:Math.hypot(...sub(root,g.points[0]))})).sort((a,b)=>a.d-b.d).slice(0,neighbors);if(!nearest.length)return curve;const weights=nearest.map(x=>1/Math.max(1e-6,x.d)**2),sum=weights.reduce((a,b)=>a+b,0),guideFrames=nearest.map(x=>x.g.frame||frame(x.g.points));return {...curve,points:curve.points.map((p,i)=>{if(i===0)return [...p];const t=i/(curve.points.length-1);let q=[0,0,0];nearest.forEach(({g},k)=>{const at=t*(g.points.length-1),j=Math.min(g.points.length-2,Math.floor(at)),u=at-j,v=add(mul(g.points[j],1-u),mul(g.points[j+1],u));q=add(q,mul(local(sub(v,g.points[0]),guideFrames[k]),weights[k]/sum));});const target=add(root,world(q,F));return add(mul(p,1-influence),mul(target,influence));})};});}
export class GroomBrush {
 constructor(groom,{history=32}={}){this.groom=validateGroom(groom);this.undoStack=[];this.redoStack=[];this.history=history;}
 begin(){if(this.before)throw Error('Groom stroke already active');this.before=structuredClone(this.groom);}
 stroke({center,radius=.3,strength=.2,mode='comb',direction=[1,0,0],pressure=1,targetLength=null}={}){if(!this.before)throw Error('Begin a grooming stroke first');if(!Array.isArray(center)||center.length!==3||center.some(x=>!Number.isFinite(x))||!Number.isFinite(radius)||radius<=0||!Number.isFinite(strength)||strength<0||strength>1||!Number.isFinite(pressure)||pressure<0||pressure>1||!['comb','smooth','cut','length','puff','clump'].includes(mode)||direction.length!==3||direction.some(x=>!Number.isFinite(x)))throw Error('Invalid grooming brush');if(targetLength!==null&&(!Number.isFinite(targetLength)||targetLength<=0))throw Error('Invalid target guide length');const original=this.groom.guides.map(g=>g.points.map(p=>[...p]));this.groom.guides.forEach((g,gi)=>{const points=g.points,F=frame(points),arc=points.slice(1).reduce((s,p,i)=>s+Math.hypot(...sub(p,points[i])),0);for(let i=1;i<points.length;i++){const t=i/(points.length-1),d=Math.hypot(...sub(points[i],center));if(d>=radius)continue;const w=(1-d/radius)**2*strength*pressure*t,old=original[gi][i];let target=old;if(mode==='comb')target=add(old,mul(direction,radius));if(mode==='smooth')target=mul(add(original[gi][i-1],original[gi][Math.min(points.length-1,i+1)]),.5);if(mode==='cut'||mode==='length')target=add(points[0],mul(sub(old,points[0]),targetLength===null?(mode==='cut'?.25:1.5):(mode==='cut'?Math.min(1,targetLength/Math.max(1e-9,arc)):targetLength/Math.max(1e-9,arc))));if(mode==='puff')target=add(old,mul(F[2],radius));if(mode==='clump')target=add(mul(center,.5),mul(old,.5));points[i]=add(mul(old,1-w),mul(target,w));}});return this.groom;}
 end(){if(!this.before)return false;this.undoStack.push(this.before);this.before=null;this.redoStack=[];if(this.undoStack.length>this.history)this.undoStack.shift();return true;}
 cancel(){if(this.before){Object.assign(this.groom,this.before);this.before=null;}}
 undo(){if(this.before)this.cancel();if(!this.undoStack.length)return false;this.redoStack.push(structuredClone(this.groom));Object.assign(this.groom,this.undoStack.pop());return true;}
 redo(){if(!this.redoStack.length)return false;this.undoStack.push(structuredClone(this.groom));Object.assign(this.groom,this.redoStack.pop());return true;}
}
