/** Convex/sphere rigid-body dynamics, angular impulses and Coulomb friction.
 * Dynamic concave shapes must be supplied as convex pieces. Arbitrary static
 * triangle meshes use BVH-selected triangle SAT/contact tests and sphere CCD.
 */
import {add,sub,mul,dot,cross,normalize,clamp,transformPoint,transformVector} from '../core/math.js';
import {quatMatrix,quatMul,quatNormalize,quatConjugate} from '../animation/rig.js';
import {triangulate,vertex,validateMesh} from '../geometry/mesh.js';
import {TriangleBVH,closestTriangle,closestSegment} from './collision.js';
const v3=(v)=>Array.isArray(v)&&v.length===3&&v.every(Number.isFinite);
function inverse3(m){const [a,b,c,d,e,f,g,h,i]=m,A=e*i-f*h,B=c*h-b*i,C=b*f-c*e,D=f*g-d*i,E=a*i-c*g,F=c*d-a*f,G=d*h-e*g,H=b*g-a*h,I=a*e-b*d,det=a*A+b*D+c*G;if(!Number.isFinite(det)||Math.abs(det)<1e-30)throw Error('Singular rigid inertia');return [A,B,C,D,E,F,G,H,I].map(x=>x/det);}
const mv=(m,v)=>[dot(m.slice(0,3),v),dot(m.slice(3,6),v),dot(m.slice(6,9),v)];
function uniqueDirections(vectors){const map=new Map();for(let v of vectors){if(Math.hypot(...v)<1e-10)continue;v=normalize(v);if(v.find(x=>Math.abs(x)>1e-8)<0)v=mul(v,-1);map.set(v.map(x=>Math.round(x*1e7)).join(','),v);}return [...map.values()];}
export function convexShape(mesh,{center=true}={}){
    validateMesh(mesh);if(mesh.positions.length/3>1024||mesh.faces.length>4096)throw Error('Convex collision mesh exceeds 1024 vertices / 4096 faces');
    const unique=new Map(),ids=[],positions=[];for(let i=0;i<mesh.positions.length/3;i++){const p=vertex(mesh,i),key=p.join(',');if(!unique.has(key)){unique.set(key,positions.length);positions.push(p);}ids.push(unique.get(key));}
    const faces=mesh.faces.map(f=>f.map(i=>ids[i]));if(positions.length<4)throw Error('A rigid convex shape needs noncoplanar vertices');
    let volume=0,centroid=[0,0,0];for(const {ids:t} of triangulate(mesh)){const [a,b,c]=t.map(i=>vertex(mesh,i)),V=dot(a,cross(b,c))/6;volume+=V;centroid=add(centroid,mul(add(a,add(b,c)),V/4));}if(volume<=1e-15)throw Error('Convex collision mesh must have positive outward volume');centroid=mul(centroid,1/volume);
    const points=center?positions.map(p=>sub(p,centroid)):positions,edges=new Map(),planes=[];
    for(const f of faces){let n=[0,0,0];for(let i=1;i+1<f.length;i++){n=cross(sub(points[f[i]],points[f[0]]),sub(points[f[i+1]],points[f[0]]));if(Math.hypot(...n)>1e-12)break;}n=normalize(n);if(Math.hypot(...n)<.5)continue;const w=dot(n,points[f[0]]);if(points.some(p=>dot(n,p)-w>1e-6))throw Error('Dynamic collision shape is concave; supply convex pieces');planes.push({n,w});for(let j=0;j<f.length;j++){const a=f[j],b=f[(j+1)%f.length];edges.set(a<b?`${a}:${b}`:`${b}:${a}`,[a,b]);}}
    const directions=uniqueDirections([...edges.values()].map(([a,b])=>sub(points[b],points[a]))),normals=uniqueDirections(planes.map(p=>p.n)),shape={type:'convex',points,faces,edges:[...edges.values()],directions,normals,planes,center:center?centroid:[0,0,0],volume};
    // Exact polynomial volume integrals of the triangulated convex boundary.
    let xx=0,yy=0,zz=0,xy=0,xz=0,yz=0;
    const second=(a,b,c,k)=>a[k]*a[k]+b[k]*b[k]+c[k]*c[k]+a[k]*b[k]+a[k]*c[k]+b[k]*c[k];
    const mixed=(a,b,c,k,l)=>2*(a[k]*a[l]+b[k]*b[l]+c[k]*c[l])+a[k]*b[l]+a[l]*b[k]+a[k]*c[l]+a[l]*c[k]+b[k]*c[l]+b[l]*c[k];
    for(const f of faces)for(let i=1;i+1<f.length;i++){const [a,b,c]=[f[0],f[i],f[i+1]].map(j=>points[j]),V=dot(a,cross(b,c))/6;xx+=V*second(a,b,c,0)/10;yy+=V*second(a,b,c,1)/10;zz+=V*second(a,b,c,2)/10;xy+=V*mixed(a,b,c,0,1)/20;xz+=V*mixed(a,b,c,0,2)/20;yz+=V*mixed(a,b,c,1,2)/20;}
    shape.inertia=[yy+zz,-xy,-xz,-xy,xx+zz,-yz,-xz,-yz,xx+yy].map(x=>x/volume);return shape;
}
function worldShape(body){const m=quatMatrix(body.rotation,body.position),s=body.shape;if(s.type==='sphere')return {...s,center:body.position,min:body.position.map(x=>x-s.radius),max:body.position.map(x=>x+s.radius)};const points=s.points.map(p=>transformPoint(m,p)),normals=s.normals.map(n=>transformVector(m,n)),directions=s.directions.map(n=>transformVector(m,n)),min=[Infinity,Infinity,Infinity],max=[-Infinity,-Infinity,-Infinity];for(const p of points)for(let k=0;k<3;k++){min[k]=Math.min(min[k],p[k]);max[k]=Math.max(max[k],p[k]);}return {...s,points,normals,directions,center:body.position,min,max,planes:s.planes.map(p=>{const n=transformVector(m,p.n);return {n,w:p.w+dot(n,body.position)};})};}
const project=(s,n)=>{if(s.type==='sphere'){const d=dot(s.center,n);return [d-s.radius,d+s.radius];}let min=Infinity,max=-Infinity;for(const p of s.points){const d=dot(p,n);min=Math.min(min,d);max=Math.max(max,d);}return [min,max];};
const support=(s,n)=>{if(s.type==='sphere')return add(s.center,mul(n,s.radius));let value=-Infinity,points=[];for(const p of s.points){const d=dot(p,n);if(d>value+1e-7){value=d;points=[p];}else if(Math.abs(d-value)<1e-7)points.push(p);}return mul(points.reduce(add,[0,0,0]),1/points.length);};
function sphereAxes(s,other){const axes=[];for(const p of other.points)axes.push(sub(p,s.center));for(const [a,b] of other.edges)axes.push(sub(closestSegment(s.center,other.points[a],other.points[b]).point,s.center));return axes;}
export function collideShapes(a,b){
    if(a.type==='sphere'&&b.type==='sphere'){const d=sub(b.center,a.center),distance=Math.hypot(...d),depth=a.radius+b.radius-distance;if(depth<=0)return null;const n=distance>1e-10?mul(d,1/distance):[1,0,0];return {normal:n,depth,points:[add(a.center,mul(n,a.radius-depth*.5))]};}
    let axes=[...(a.normals||[]),...(b.normals||[])];if(a.type==='sphere')axes.push(...sphereAxes(a,b));else if(b.type==='sphere')axes.push(...sphereAxes(b,a));else for(const x of a.directions)for(const y of b.directions)axes.push(cross(x,y));axes=uniqueDirections(axes);
    let depth=Infinity,normal=null;for(const n of axes){const A=project(a,n),B=project(b,n),positive=A[1]-B[0],negative=B[1]-A[0];if(positive<=0||negative<=0)return null;const d=Math.min(positive,negative);if(d<depth){depth=d;normal=positive<negative?n:mul(n,-1);}}
    if(!normal||!Number.isFinite(depth))return null;let points=[];
    if(a.type==='sphere'||b.type==='sphere')points=[mul(add(support(a,normal),support(b,mul(normal,-1))),.5)];
    else{const aMax=project(a,normal)[1],bMin=project(b,normal)[0],plane=(aMax+bMin)/2;
        for(const [shape,other,sign,extreme] of [[a,b,1,aMax],[b,a,-1,bMin]])for(const p of shape.points)if(Math.abs(dot(p,normal)-extreme)<1e-5){const contact=add(p,mul(normal,plane-dot(p,normal)));if(other.planes.every(f=>dot(f.n,contact)-f.w<=depth*.51+1e-6))points.push(contact);}
        const dedup=new Map();points.forEach(p=>dedup.set(p.map(x=>Math.round(x*1e7)).join(','),p));points=[...dedup.values()];if(!points.length)points=[mul(add(support(a,normal),support(b,mul(normal,-1))),.5)];if(points.length>4){const selected=[points.shift()];while(selected.length<4){let best=0,dist=-1;points.forEach((p,i)=>{const d=Math.min(...selected.map(q=>dot(sub(p,q),sub(p,q))));if(d>dist){dist=d;best=i;}});selected.push(points.splice(best,1)[0]);}points=selected;}}
    return {normal,depth,points};
}
function triangleShape(points){const n=normalize(cross(sub(points[1],points[0]),sub(points[2],points[0]))),edges=[[0,1],[1,2],[2,0]],normals=[n],directions=edges.map(([a,b])=>normalize(sub(points[b],points[a])));return {type:'convex',points,edges,normals,directions,planes:[{n,w:dot(n,points[0])},{n:mul(n,-1),w:-dot(n,points[0])}],center:mul(points.reduce(add,[0,0,0]),1/3)};}
export class DynamicsWorld {
    constructor({gravity=[0,-9.81,0],floor=0,substeps=4,iterations=10,linearDamping=.01,angularDamping=.01}={}){if(!v3(gravity)||!Number.isFinite(floor)||!Number.isInteger(substeps)||substeps<1||substeps>64||!Number.isInteger(iterations)||iterations<1||iterations>64)throw Error('Invalid rigid dynamics settings');Object.assign(this,{gravity,floor,substeps,iterations,linearDamping,angularDamping});this.bodies=[];this.colliders=[];this.time=0;}
    add({shape={type:'sphere',radius:.5},position=[0,1,0],velocity=[0,0,0],rotation=[0,0,0,1],angularVelocity=[0,0,0],mass=1,restitution=.2,friction=.5,id=null}={}){
        if(![position,velocity,angularVelocity].every(v3)||rotation.length!==4||!rotation.every(Number.isFinite)||!Number.isFinite(mass)||mass<0||!Number.isFinite(restitution)||restitution<0||restitution>1||!Number.isFinite(friction)||friction<0)throw Error('Invalid rigid body parameters');if(shape.mesh)shape=convexShape(shape.mesh);if(shape.type==='sphere'&&(!Number.isFinite(shape.radius)||shape.radius<=0))throw Error('Invalid rigid sphere');if(!['sphere','convex'].includes(shape.type))throw Error('Unsupported rigid collision shape');const inertia=shape.type==='sphere'?[.4*shape.radius**2,0,0,0,.4*shape.radius**2,0,0,0,.4*shape.radius**2]:shape.inertia,invInertia=mass?inverse3(inertia.map(v=>v*mass)):new Array(9).fill(0),b={id,shape,position:[...position],velocity:[...velocity],rotation:quatNormalize(rotation),angularVelocity:[...angularVelocity],inverseMass:mass?1/mass:0,invInertia,restitution,friction};this.bodies.push(b);return b;
    }
    addCollider(mesh,options={}){this.colliders.push({bvh:new TriangleBVH(mesh),friction:options.friction??.5,restitution:options.restitution??.1});return this;}
    invI(body,vector){if(!body?.inverseMass)return [0,0,0];const R=quatMatrix(body.rotation),inverseR=quatMatrix(quatConjugate(body.rotation));return transformVector(R,mv(body.invInertia,transformVector(inverseR,vector)));}
    impulse(body,force,point){if(!body?.inverseMass)return;body.velocity=add(body.velocity,mul(force,body.inverseMass));body.angularVelocity=add(body.angularVelocity,this.invI(body,cross(sub(point,body.position),force)));}
    contacts(){const contacts=[],shapes=this.bodies.map(worldShape),push=(a,b,c,material={})=>{if(c)for(const point of c.points)contacts.push({a,b,point,normal:c.normal,depth:c.depth,normalImpulse:0,tangentImpulse:[0,0,0],friction:Math.sqrt(a.friction*(b?.friction??material.friction??.5)),restitution:Math.min(a.restitution,b?.restitution??material.restitution??.2)});};
        const order=this.bodies.map((_,i)=>i).sort((a,b)=>shapes[a].min[0]-shapes[b].min[0]);for(let oi=0;oi<order.length;oi++){const i=order[oi],a=this.bodies[i],A=shapes[i];for(let oj=oi+1;oj<order.length&&shapes[order[oj]].min[0]<A.max[0];oj++){const j=order[oj],b=this.bodies[j],B=shapes[j];if(!(a.inverseMass+b.inverseMass)||A.min.some((x,k)=>x>B.max[k]||A.max[k]<B.min[k]))continue;push(a,b,collideShapes(A,B));}
            if(!a.inverseMass)continue;if(A.min[1]<this.floor){const points=A.type==='sphere'?[sub(a.position,[0,A.radius,0])]:A.points.filter(p=>p[1]<this.floor+1e-7);push(a,null,{normal:[0,-1,0],depth:this.floor-A.min[1],points:points.slice(0,4).map(p=>[p[0],this.floor,p[2]])});}
            for(const collider of this.colliders)for(const id of collider.bvh.query(A)){const points=collider.bvh.triangles[id].map(i=>vertex(collider.bvh,i));if(A.type==='sphere'){const q=closestTriangle(a.position,...points),d=sub(q.point,a.position),distance=Math.hypot(...d);if(distance<A.radius)push(a,null,{normal:distance>1e-10?mul(d,1/distance):[0,-1,0],depth:A.radius-distance,points:[q.point]},collider);}else push(a,null,collideShapes(A,triangleShape(points)),collider);}
        }return contacts;
    }
    velocityAt(body,p){return body?add(body.velocity,cross(body.angularVelocity,sub(p,body.position))):[0,0,0];}
    denominator(c,n){const {a,b,point}=c,ra=sub(point,a.position),rb=b?sub(point,b.position):[0,0,0];return a.inverseMass+(b?.inverseMass||0)+dot(n,add(cross(this.invI(a,cross(ra,n)),ra),cross(this.invI(b,cross(rb,n)),rb)));}
    solveContact(c){const rel=sub(this.velocityAt(c.b,c.point),this.velocityAt(c.a,c.point)),vn=dot(rel,c.normal),den=this.denominator(c,c.normal);if(den<1e-15)return;const impulse=Math.max(0,c.normalImpulse+(-vn+c.bounce)/den),delta=impulse-c.normalImpulse;c.normalImpulse=impulse;this.impulse(c.a,mul(c.normal,-delta),c.point);this.impulse(c.b,mul(c.normal,delta),c.point);
        const velocity=sub(this.velocityAt(c.b,c.point),this.velocityAt(c.a,c.point)),tangent=sub(velocity,mul(c.normal,dot(velocity,c.normal))),length=Math.hypot(...tangent);if(length>1e-10){const t=mul(tangent,1/length),D=this.denominator(c,t);if(D>1e-15){let next=sub(c.tangentImpulse,mul(t,length/D)),L=Math.hypot(...next),max=c.friction*c.normalImpulse;if(L>max)next=mul(next,max/L);const d=sub(next,c.tangentImpulse);c.tangentImpulse=next;this.impulse(c.a,mul(d,-1),c.point);this.impulse(c.b,d,c.point);}}
    }
    step(dt){if(!Number.isFinite(dt)||dt<=0||dt>.1)throw Error('Rigid timestep must be in (0,.1]');const h=dt/this.substeps;
        for(let s=0;s<this.substeps;s++){for(const b of this.bodies)if(b.inverseMass){const old=[...b.position];b.velocity=mul(add(b.velocity,mul(this.gravity,h)),Math.exp(-this.linearDamping*h));b.angularVelocity=mul(b.angularVelocity,Math.exp(-this.angularDamping*h));b.position=add(b.position,mul(b.velocity,h));const dq=quatMul([...b.angularVelocity,0],b.rotation);b.rotation=quatNormalize(b.rotation.map((v,i)=>v+.5*h*dq[i]));if(b.shape.type==='sphere')for(const collider of this.colliders){const hit=collider.bvh.sweep(old,b.position,b.shape.radius);if(hit){b.position=add(hit.point,mul(hit.normal,1e-7));const vn=dot(b.velocity,hit.normal);if(vn<0)b.velocity=sub(b.velocity,mul(hit.normal,(1+Math.min(b.restitution,collider.restitution))*vn));}}}
            const contacts=this.contacts();for(const c of contacts){const vn=dot(sub(this.velocityAt(c.b,c.point),this.velocityAt(c.a,c.point)),c.normal);c.bounce=vn<-.5?-vn*c.restitution:0;}for(let it=0;it<this.iterations;it++)for(const c of contacts)this.solveContact(c);
            for(let it=0;it<3;it++){const contacts=this.contacts(),counts=new Map();for(const c of contacts){const key=this.bodies.indexOf(c.a)+':'+this.bodies.indexOf(c.b);counts.set(key,(counts.get(key)||0)+1);}for(const c of contacts){const mass=c.a.inverseMass+(c.b?.inverseMass||0);if(!mass)continue;const count=counts.get(this.bodies.indexOf(c.a)+':'+this.bodies.indexOf(c.b)),correction=mul(c.normal,.8*Math.max(0,c.depth-1e-5)/(mass*count));c.a.position=sub(c.a.position,mul(correction,c.a.inverseMass));if(c.b)c.b.position=add(c.b.position,mul(correction,c.b.inverseMass));}}
        }this.time+=dt;return this;
    }
}
