import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';
import {DurableRenderQueue} from '../src/distributed/durable-queue.js';import {emptyDocument} from '../src/scene/document.js';
function setup(t,options={}){const stateDir=fs.mkdtempSync(path.join(os.tmpdir(),'aureon-state-'));t.after(()=>fs.rmSync(stateDir,{recursive:true,force:true}));return {stateDir,...options};}
function crash(q){fs.closeSync(q.fd);q.closed=true;q.releaseLock();}
test('Durable restart preserves acknowledged HDR data and rejects old unfinished leases',t=>{const options=setup(t),q=new DurableRenderQueue(options),j=q.create({scene:emptyDocument(),width:2,height:2,samples:4,batchSize:2,tileSize:2}),a=q.claim('a'),b=q.claim('b'),data=new Float32Array(96).fill(3.25);q.complete(j.id,a.task.id,a.task.lease,data);crash(q);const r=new DurableRenderQueue(options);assert.equal(r.describe(j.id).completed,1);assert.equal(r.image(j.id).hdr.data[0],3.25);assert.throws(()=>r.complete(j.id,b.task.id,b.task.lease,data),/lease/);assert.equal(r.complete(j.id,a.task.id,a.task.lease,data).duplicate,true);const retry=r.claim('new');assert.equal(retry.task.id,b.task.id);r.complete(j.id,retry.task.id,retry.task.lease,new Float32Array(96).fill(1.75));assert.equal(r.image(j.id).hdr.data[0],2.5);assert.equal(r.describe(j.id).status,'completed');r.close();});
test('Atomic snapshots preserve Kahan sums, tasks and cancellation',t=>{const options=setup(t,{checkpointEvery:1}),q=new DurableRenderQueue(options),j=q.create({scene:emptyDocument(),width:1,height:1,samples:1}),a=q.claim('a');q.complete(j.id,0,a.task.lease,new Float32Array(24).fill(2));q.cancel(j.id);q.close();const r=new DurableRenderQueue(options);assert.equal(r.describe(j.id).status,'cancelled');assert.equal(r.image(j.id).hdr.data[0],2);r.remove(j.id);r.close();const s=new DurableRenderQueue(options);assert.equal(s.jobs.size,0);s.close();});
test('Interrupted trailing writes are truncated; checksum corruption is not ignored',t=>{const options=setup(t),q=new DurableRenderQueue(options),j=q.create({scene:emptyDocument(),width:1,height:1,samples:1});crash(q);fs.appendFileSync(path.join(options.stateDir,'journal.bin'),Buffer.from('AURQ'));const r=new DurableRenderQueue(options);assert.equal(r.recoveredTailBytes,4);assert.equal(r.describe(j.id).completed,0);crash(r);const log=path.join(options.stateDir,'journal.bin'),bytes=fs.readFileSync(log);bytes[bytes.length-1]^=1;fs.writeFileSync(log,bytes);assert.throws(()=>new DurableRenderQueue(options),/checksum/);});
test('A second coordinator cannot open a live writer directory',t=>{const options=setup(t),q=new DurableRenderQueue(options);assert.throws(()=>new DurableRenderQueue(options),/locked/);q.close();});
test('Invalid tile results are not journaled or acknowledged',t=>{const options=setup(t),q=new DurableRenderQueue(options),j=q.create({scene:emptyDocument(),width:1,height:1,samples:1}),a=q.claim('a'),seq=q.seq;assert.throws(()=>q.complete(j.id,0,a.task.lease,new Float32Array([NaN])));assert.equal(q.seq,seq);assert.equal(q.describe(j.id).completed,0);q.close();});
