import test from 'node:test';import assert from 'node:assert/strict';
import {encodeEXRAdvanced,decodeEXRAdvanced,floatToHalf,halfToFloat,zipPredict,zipUnpredict} from '../src/io/exr-advanced.js';
import {encodeEXR,decodeEXR} from '../src/io/exr.js';
test('Every finite half-precision bit pattern round trips exactly',()=>{for(let h=0;h<65536;h++){if((h&0x7c00)===0x7c00)continue;assert.equal(floatToHalf(halfToFloat(h)),h,`half ${h}`);}assert.equal(floatToHalf(1+2**-11),0x3c00);assert.equal(floatToHalf(1+3*2**-11),0x3c02);assert.equal(floatToHalf(2**-25),0);});
test('ZIP predictor handles odd/even blocks and modular differences',()=>{for(let n=1;n<99;n++){const a=Uint8Array.from({length:n},(_,i)=>(i*91+75)%256);assert.deepEqual(zipUnpredict(zipPredict(a)),a);}});
for(const compression of ['NONE','ZIPS','ZIP'])test(`${compression}: independent old reader, multiblock and HALF/UINT channels`,async()=>{const width=32,height=35,R=Float32Array.from({length:width*height},(_,i)=>i%13*.25-2),id=Uint32Array.from({length:width*height},(_,i)=>0x80000000+i);const encoded=await encodeEXRAdvanced({width,height,channels:{R,id},compression,types:{R:'HALF'}}),result=await decodeEXRAdvanced(encoded);assert.deepEqual(result.channels.R,R);assert.deepEqual(result.channels.id,id);const plain=await encodeEXRAdvanced({width,height,channels:{R},compression:'NONE'});assert.deepEqual(decodeEXR(plain).channels.R,R);assert.deepEqual((await decodeEXRAdvanced(encodeEXR({width,height,channels:{R,id}}))).channels.id,id);});
test('ZIP actually compresses smooth HDR images without clamping',async()=>{const image={width:64,height:64,channels:{R:new Float32Array(4096).fill(12.5),G:new Float32Array(4096).fill(-.25)}};const compressed=await encodeEXRAdvanced(image),raw=await encodeEXRAdvanced({...image,compression:'NONE'});assert.ok(compressed.length<raw.length/8);const decoded=await decodeEXRAdvanced(compressed);assert.equal(decoded.channels.R[0],12.5);assert.equal(decoded.channels.G[4095],-.25);});
test('Multipart channels retain independent data windows, names and codecs',async()=>{const bytes=await encodeEXRAdvanced({parts:[{name:'beauty',width:8,height:17,xMin:-4,yMin:-8,channels:{R:new Float32Array(136).fill(3)},types:{R:'HALF'}},{name:'IDs',width:3,height:2,compression:'ZIPS',channels:{objectId:new Uint32Array([1,2,3,4,5,0xffffffff])}}]});const result=await decodeEXRAdvanced(bytes);assert.equal(result.parts.length,2);assert.equal(result.parts[0].yMin,-8);assert.equal(result.parts[1].channels.objectId[5],0xffffffff);assert.equal(result.parts[1].name,'IDs');});
test('Malformed chunks, oversize HALF output and duplicate parts fail explicitly',async()=>{await assert.rejects(encodeEXRAdvanced({width:1,height:1,channels:{R:Float32Array.of(70000)},types:{R:'HALF'}}),/HALF/);const image={name:'same',width:1,height:1,channels:{R:Float32Array.of(1)}};await assert.rejects(encodeEXRAdvanced({parts:[image,image]}),/Duplicate/);const bytes=await encodeEXRAdvanced(image);await assert.rejects(decodeEXRAdvanced(bytes.slice(0,-1)),/Truncated/);await assert.rejects(decodeEXRAdvanced(Uint8Array.of(1,2)),/Truncated/);});
