import test from 'node:test';import assert from 'node:assert/strict';
import {longitudinal,fiberLobes,evaluateFiber,sampleFiber,validateFiber} from '../src/materials/fiber.js';
import {createGroom,GroomBrush,applyGroom} from '../src/simulation/groom.js';
import {generateHair,curvesToMesh} from '../src/simulation/curves.js';
import {createPrimitive} from '../src/geometry/primitives.js';
import {emptyDocument,newObject,GeometryCache} from '../src/scene/document.js';import {compileTriangles} from '../src/render/compile.js';import {compileSceneAssets} from '../src/render/assets.js';
const near=(a,b,e=1e-3)=>assert.ok(Math.abs(a-b)<e,`${a} != ${b}`);
test('Fiber longitudinal distribution integrates to one at normal and grazing angles',()=>{for(const so of [-.95,-.5,0,.7,.98])for(const v of [.002,.04,.25,1,4]){let sum=0;const n=40000;for(let i=0;i<n;i++)sum+=longitudinal(-1+2*(i+.5)/n,so,v)*2/n;near(sum,1,.002);}});
test('Lossless fiber attenuations conserve energy including the internal-reflection tail',()=>{for(const so of [0,.3,.8])for(const h of [-.8,0,.7]){const L=fiberLobes({absorption:[0,0,0]},so,h);for(let k=0;k<3;k++)near(L.A.reduce((s,a)=>s+a[k],0),1,1e-9);near(L.weights.reduce((a,b)=>a+b,0),1,1e-10);}});
test('Fiber PDF integrates and stochastic samples match its first moments',()=>{const f={roughness:.5,azimuthalRoughness:.5},wo=[.3,Math.sqrt(.91),0],h=.2;let mass=0,moment=0;for(let j=0;j<200;j++)for(let i=0;i<400;i++){const s=-1+(j+.5)/100,c=Math.sqrt(1-s*s),phi=(i+.5)*Math.PI/200,q=evaluateFiber(f,wo,[s,c*Math.cos(phi),c*Math.sin(phi)],h);mass+=q.pdf*Math.PI/20000;moment+=q.pdf*s*Math.PI/20000;}near(mass,1,.005);let state=12,random=()=>{state=(1664525*state+1013904223)>>>0;return state/4294967296;},sample=0;for(let i=0;i<20000;i++){const r=sampleFiber(f,wo,h,random);assert.ok(r.pdf>0&&r.value.every(Number.isFinite));near(Math.hypot(...r.wi),1,1e-8);sample+=r.wi[0]/20000;}near(sample,moment,.02);});
test('Fiber absorption reduces transport and invalid parameters are rejected',()=>{const a=fiberLobes({absorption:[0,0,0]},.2),b=fiberLobes({absorption:[2,4,8]},.2);assert.ok(b.A[1].every((x,k)=>x<a.A[1][k]));assert.throws(()=>validateFiber({roughness:0}));assert.throws(()=>validateFiber({absorption:[-1,0,1]}));});
test('Groom strokes preserve roots, change guides and undo losslessly',()=>{const mesh=createPrimitive('plane',{width:1,depth:1,segments:4}),g=createGroom(mesh,{count:8,length:1,seed:4,segments:6}),before=structuredClone(g),brush=new GroomBrush(g);brush.begin();brush.stroke({center:[0,.5,0],radius:2,direction:[1,0,0],strength:.8});brush.end();assert.notDeepEqual(g,before);g.guides.forEach((c,i)=>assert.deepEqual(c.points[0],before.guides[i].points[0]));assert.ok(brush.undo());assert.deepEqual(g,before);assert.ok(brush.redo());const hairs=generateHair(mesh,{count:16,length:1,seed:4,segments:6}),result=applyGroom(hairs,g);assert.notDeepEqual(result,hairs);result.forEach((c,i)=>assert.deepEqual(c.points[0],hairs[i].points[0]));});
test('Fiber tangent/radius metadata survives geometry evaluation and BVH packing',()=>{const doc=emptyDocument(),o=newObject('mesh',0);o.mesh=curvesToMesh([{points:[[0,0,0],[0,1,0]],radius:.03}]);doc.objects.push(o);doc.materials[0].fiber={roughness:.3};const c=compileTriangles(doc,new GeometryCache());assert.ok(c.triangles.length>0);for(let i=0;i<c.triangles.length;i+=32){assert.ok((c.triangles[i+30]&8)!==0);assert.ok(c.triangles[i+23]>0);}const a=compileSceneAssets(doc);assert.equal(a.data[a.materialOffset*16+3],1);});

test('Groom roots and brush shape follow a moved emitter without nearest-guide drift',()=>{
 const mesh=createPrimitive('plane',{width:1,depth:1,segments:2});const g=createGroom(mesh,{count:12,length:1,seed:4,segments:6}),brush=new GroomBrush(g);brush.begin();brush.stroke({center:[0,.5,0],radius:2,direction:[1,0,0],strength:.6});brush.end();
 const hair=generateHair(mesh,{count:20,length:1,seed:7,segments:6}),before=applyGroom(hair,g,{emitter:mesh}),moved=structuredClone(mesh);moved.positions=moved.positions.map((x,i)=>x+[5,1,-3][i%3]);
 const after=applyGroom(generateHair(moved,{count:20,length:1,seed:7,segments:6}),g,{emitter:moved});
 after.forEach((c,i)=>c.points.forEach((p,j)=>p.forEach((v,k)=>near(v,before[i].points[j][k]+[5,1,-3][k],1e-6))));
});
