/** Authoring workspaces for the production systems. Drafts are committed through
 * the same History transaction used by the original editor; cancelling a dialog
 * never changes the scene, paint assets, simulation state, or guide data. */
import {newObject,material,worldMatrix,validateDocument} from '../scene/document.js';
import {inverse,matMul,transformPoint,transformVector,normalize,sub,add,mul,clamp,srgbToLinear} from '../core/math.js';
import {cloneMesh,vertex,bounds} from '../geometry/mesh.js';
import {booleanMesh,transformMesh} from '../geometry/boolean.js';
import {bevelMesh} from '../geometry/bevel.js';
import {conformalUnwrap} from '../geometry/uv.js';
import {packUDIM} from '../geometry/udim.js';
import {createPaintTexture,TexturePainter,compositeLayers,udimCoordinates,udimNumber} from '../materials/udim.js';
import {decodeBitmap} from '../materials/textures.js';
import {validateFiber} from '../materials/fiber.js';
import {createGroom,GroomBrush,applyGroom} from '../simulation/groom.js';
import {generateHair} from '../simulation/curves.js';
import {fluidBlock} from '../simulation/fluids.js';
import {proceduralDensity,validateVolume} from '../volumes/grid.js';
import {applyControllers,retargetRig} from '../animation/controllers.js';
import {cameraFrame,project} from '../render/camera.js';
import {encodeEXRAdvanced} from '../io/exr-advanced.js';
import {renderChannels} from '../io/exr.js';
import {download} from '../io/formats.js';
import {escapeHTML as esc} from './inspector.js';
const $=s=>document.querySelector(s),empty=()=>({positions:[],faces:[],uvs:[],smooth:true});
const row=(label,html)=>`<div class="form-row"><label>${label}</label>${html}</div>`;
const num=(id,v,min=-1e6,max=1e6,step=.1)=>`<input id="${id}" type="number" value="${v}" min="${min}" max="${max}" step="${step}" aria-label="${id}">`;
const choice=(id,values,selected)=>`<select id="${id}">${values.map(v=>{const [key,label]=Array.isArray(v)?v:[v,v];return `<option value="${esc(key)}" ${String(key)===String(selected)?'selected':''}>${esc(label)}</option>`;}).join('')}</select>`;
const button=(id,text)=>`<button type="button" id="${id}" class="small-button">${text}</button>`;
const box=(id,yes)=>`<input id="${id}" type="checkbox" ${yes?'checked':''}>`;
const text=(id,v)=>`<input id="${id}" value="${esc(v??'')}" aria-label="${id}">`;
const area=(id,v)=>`<textarea id="${id}" class="advanced-json" spellcheck="false">${esc(JSON.stringify(v,null,2))}</textarea>`;
const number=id=>{const e=$('#'+id),v=e.valueAsNumber;if(!Number.isFinite(v)||v<Number(e.min)||v>Number(e.max))throw Error('Invalid '+id);return v;};
const vec=(id,v)=>`<div class="xyz">${v.map((x,i)=>num(id+i,x)).join('')}</div>`;
const readVec=id=>[0,1,2].map(i=>number(id+i));
const parse=id=>JSON.parse($('#'+id).value);
const selectedMaterial=app=>{const index=app.materialIndex??app.activeObject?.material??0;return {index,value:app.doc.materials[index]};};
function replaceGeometry(o,mesh){o.type='mesh';o.mesh=mesh;o.params={};o.modifiers=[];for(const key of ['rig','simulation','procedural','meshCache','morphTargets','morphWeights'])delete o[key];}
function files(accept,multiple=false){return new Promise(resolve=>{const e=document.createElement('input');e.type='file';e.accept=accept;e.multiple=multiple;e.onchange=()=>resolve([...e.files]);e.oncancel=()=>resolve([]);e.click();});}
function style(){if($('#advanced-authoring-style'))return;const e=document.createElement('style');e.id='advanced-authoring-style';e.textContent=`.advanced-two{display:grid;grid-template-columns:minmax(0,1fr) 240px;gap:18px}.advanced-json{box-sizing:border-box;width:100%;min-height:150px;resize:vertical;white-space:pre;font:12px/1.5 monospace;padding:10px;color:var(--text,#e4e8ee);background:var(--surface,#20252d);border:1px solid #465162;border-radius:6px}.advanced-canvas{width:100%;height:auto;max-height:62vh;object-fit:contain;background:#171d24;border:1px solid #465162;touch-action:none}.advanced-stats{font:12px/1.5 monospace;white-space:pre-wrap}.advanced-panel .form-row{margin:9px 0}.advanced-panel input,.advanced-panel select{max-width:190px}.advanced-panel .xyz input{max-width:60px}@media(max-width:800px){.advanced-two{grid-template-columns:1fr}.advanced-panel{display:grid;grid-template-columns:1fr 1fr;gap:8px}.advanced-canvas{max-height:48vh}}`;document.head.append(e);}

function bevelDialog(app){const o=app.requireObject();let old=o.modifiers?.findLast(m=>m.type==='bevel');app.dialog('Segmented bevel',`${row('Width',num('bevel-width',old?.value??.06,.00001,1000,.01))}${row('Segments',num('bevel-segments',old?.segments??3,1,32,1))}${row('Profile',num('bevel-profile',old?.profile??.5,.05,.95,.05))}${row('Edges',choice('bevel-selection',['all','sharp'],old?.selection||'all'))}${row('Sharp angle · degrees',num('bevel-angle',old?.angle??30,0,180,1))}<p class="production-note">Constructs edge strips, miter caps and coplanar face patches. Invalid overlapping widths are rejected rather than hidden. Selected edge pairs and per-edge weights are also available in the modifier data.</p>`,()=>{const settings={type:'bevel',value:number('bevel-width'),segments:number('bevel-segments'),profile:number('bevel-profile'),selection:$('#bevel-selection').value,angle:number('bevel-angle')};const clone={...o,modifiers:(o.modifiers||[]).filter(m=>m!==old)};bevelMesh(app.geometry.get(clone),settings.value,settings);app.mutate('Segmented bevel',()=>{if(old)Object.assign(old,settings);else o.modifiers.push(settings);});},'Apply bevel');}
function exactBooleanDialog(app){const a=app.requireObject(),others=app.doc.objects.filter(o=>o.id!==a.id&&o.type!=='group');if(!others.length)throw Error('Create a second solid before a Boolean operation');app.dialog('Solid Boolean',`${row('Operand',choice('solid-other',others.map(o=>[o.id,o.name]),[...app.selected].find(id=>id!==a.id)||others[0].id))}${row('Operation',choice('solid-op',['union','subtract','intersect'],'subtract'))}${row('Arithmetic',choice('solid-arithmetic',[['exact','Exact rational construction'],['fast','Fast floating-point BSP']],'exact'))}${row('Hide operand after operation',box('solid-hide',true))}<p class="production-note">Exact mode constructs and classifies intersections using reduced rational arithmetic derived from the input coordinates. Display vertices are converted back to floating point only at the output boundary. Both inputs must be closed, outward-oriented manifolds.</p>`,()=>{const b=app.doc.objects.find(o=>o.id===$('#solid-other').value),B=transformMesh(app.geometry.get(b),matMul(inverse(worldMatrix(app.doc,a)),worldMatrix(app.doc,b))),mesh=booleanMesh(app.geometry.get(a),B,$('#solid-op').value,{precision:$('#solid-arithmetic').value});const hide=$('#solid-hide').checked;app.mutate('Solid Boolean',()=>{replaceGeometry(a,mesh);if(hide)b.visible=false;});},'Compute');}
function udimDialog(app){const o=app.requireObject();app.dialog('UDIM island packing',`${row('First tile',num('uv-first',1001,1001,2000,1))}${row('Tile count',num('uv-tiles',2,1,64,1))}${row('Padding · UV',num('uv-padding',.02,0,.24,.005))}${row('Unwrap first',box('uv-unwrap',true))}${row('Allow quarter-turns',box('uv-rotate',true))}<p class="production-note">Packs seam-separated charts across multiple tiles with one shared scale. Existing island size ratios are retained. Apply before adding skin, simulation or procedural deformation.</p>`,()=>{const first=number('uv-first'),count=number('uv-tiles');if(first+count-1>2000)throw Error('Requested tiles exceed the UDIM range');let mesh=cloneMesh(app.geometry.get(o));if($('#uv-unwrap').checked)mesh=conformalUnwrap(mesh);const result=packUDIM(mesh,{tiles:Array.from({length:count},(_,i)=>first+i),padding:number('uv-padding'),rotate:$('#uv-rotate').checked});app.mutate('Pack UV islands into UDIM',()=>replaceGeometry(o,result.mesh));},'Pack tiles');}

function paintDialog(app){
 const {index:matIndex,value:mat}=selectedMaterial(app);if(!mat)throw Error('Select a material');let assetIndex=Number.isInteger(mat.bitmap)&&mat.bitmap>=0?mat.bitmap:null;
 let draft=assetIndex!==null&&app.doc.textures?.[assetIndex]?structuredClone(app.doc.textures[assetIndex]):createPaintTexture({name:mat.name+' paint',size:256,udim:true});
 if(draft.kind!=='layers')draft={kind:'layers',name:draft.name||'Paint layers',layers:[{name:'Base',visible:true,opacity:1,blend:'normal',texture:draft}]};let active=0,painter=null,tileId=1001,stroke=false,cloneUV=[.5,.5];
 const painters=new WeakMap();function getPainter(){const t=draft.layers[active].texture;let p=painters.get(t);if(!p){p=new TexturePainter(t,{autoCreateTiles:true,tileSize:256});painters.set(t,p);}return p;}
 app.dialog('Texture paint · layers and UDIM',`<div class="advanced-two"><div><canvas id="paint-surface" class="advanced-canvas" width="768" height="768" aria-label="Texture paint canvas"></canvas><div id="paint-stats" class="advanced-stats"></div></div><div class="advanced-panel">${row('Layer',choice('paint-layer',draft.layers.map((l,i)=>[i,l.name||'Layer '+i]),active))}<div class="production-actions">${button('paint-add','Add layer')}${button('paint-remove','Delete')}</div>${row('Visible',box('paint-visible',true))}${row('Opacity',num('paint-opacity',1,0,1,.05))}${row('Blend',choice('paint-blend',['normal','multiply','screen','add'],'normal'))}${row('Tile',num('paint-tile',1001,1001,2000,1))}<div class="production-actions">${button('paint-add-tile','Add tile')}${button('paint-import','Import image')}</div>${row('Tool',choice('paint-tool',['paint','erase','clone','smudge'],'paint'))}${row('Color','<input id="paint-color" type="color" value="#e59b5b">')}${row('Radius · tile UV',num('paint-radius',.04,.001,.5,.005))}${row('Hardness',num('paint-hardness',.65,0,1,.05))}${row('Brush opacity',num('paint-alpha',.9,0,1,.05))}<div class="production-actions">${button('paint-undo','Undo stroke')}${button('paint-redo','Redo stroke')}${button('paint-export','Export tile')}</div><p class="production-note">Pressure-sensitive brush, eraser, clone and smudge edit real image pixels. Alt-click chooses the clone source. Apply commits the layer stack and assigns it to the material; Cancel discards this draft.</p></div></div>`,()=>{if(stroke){getPainter().end();stroke=false;}compositeLayers(draft);app.mutate('Paint texture layers',()=>{app.doc.textures||=[];if(assetIndex===null){assetIndex=app.doc.textures.length;app.doc.textures.push(draft);}else app.doc.textures[assetIndex]=draft;app.doc.materials[matIndex].bitmap=assetIndex;});},'Apply texture',1060);
 const canvas=$('#paint-surface'),ctx=canvas.getContext('2d');
 function draw(){const composite=compositeLayers(draft),t=composite.kind==='udim'?composite.tiles[tileId]:composite;ctx.clearRect(0,0,768,768);for(let y=0;y<768;y+=24)for(let x=0;x<768;x+=24){ctx.fillStyle=((x+y)/24)%2?'#303641':'#252a33';ctx.fillRect(x,y,24,24);}if(t){const tmp=document.createElement('canvas');tmp.width=t.width;tmp.height=t.height;tmp.getContext('2d').putImageData(new ImageData(Uint8ClampedArray.from(t.data),t.width,t.height),0,0);ctx.imageSmoothingEnabled=true;ctx.save();ctx.translate(0,768);ctx.scale(1,-1);ctx.drawImage(tmp,0,0,768,768);ctx.restore();}$('#paint-stats').textContent=`Tile ${tileId} · ${t?t.width+' × '+t.height:'not present'} · ${draft.layers.length} layers · ${getPainter().undoStack.length} strokes`;}
 function sync(){const l=draft.layers[active];$('#paint-layer').innerHTML=draft.layers.map((l,i)=>`<option value="${i}" ${i===active?'selected':''}>${esc(l.name)}</option>`).join('');$('#paint-opacity').value=l.opacity??1;$('#paint-visible').checked=l.visible!==false;$('#paint-blend').value=l.blend||'normal';painter=getPainter();draw();}
 function point(e){const r=canvas.getBoundingClientRect(),[u,v]=udimCoordinates(tileId);return [u+(e.clientX-r.left)/r.width,v+1-(e.clientY-r.top)/r.height];}
 canvas.onpointerdown=e=>{if(e.button!==0)return;e.preventDefault();const uv=point(e);if(e.altKey){cloneUV=uv;return;}const hex=$('#paint-color').value,color=[1,3,5].map(i=>parseInt(hex.slice(i,i+2),16)/255);painter=getPainter();painter.begin({mode:$('#paint-tool').value==='paint'?'draw':$('#paint-tool').value,radius:number('paint-radius'),hardness:number('paint-hardness'),opacity:number('paint-alpha'),color:[...color.map(srgbToLinear),1],cloneOffset:sub([...cloneUV,0],[...uv,0]).slice(0,2)});painter.point(uv,e.pointerType==='pen'?e.pressure:1);stroke=true;canvas.setPointerCapture(e.pointerId);draw();};
 canvas.onpointermove=e=>{if(stroke){painter.point(point(e),e.pointerType==='pen'?e.pressure:1);draw();}};
 canvas.onpointerup=e=>{if(stroke){painter.end();stroke=false;canvas.releasePointerCapture(e.pointerId);draw();}};canvas.onpointercancel=()=>{if(stroke)painter.cancel();stroke=false;draw();};
 $('#paint-layer').onchange=()=>{active=Number($('#paint-layer').value);sync();};$('#paint-tile').onchange=()=>app.safe(()=>{tileId=number('paint-tile');udimCoordinates(tileId);draw();});
 for(const id of ['opacity','visible','blend'])$('#paint-'+id).onchange=()=>app.safe(()=>{const l=draft.layers[active];l.opacity=number('paint-opacity');l.visible=$('#paint-visible').checked;l.blend=$('#paint-blend').value;draw();});
 $('#paint-add').onclick=()=>app.safe(()=>{if(draft.layers.length>=64)throw Error('The layer limit is 64');draft.layers.push({name:'Layer '+draft.layers.length,visible:true,opacity:1,blend:'normal',texture:createPaintTexture({size:256,udim:true,tile:tileId})});active=draft.layers.length-1;sync();});
 $('#paint-remove').onclick=()=>app.safe(()=>{if(draft.layers.length===1)throw Error('Keep at least one layer');draft.layers.splice(active,1);active=Math.max(0,active-1);sync();});
 $('#paint-add-tile').onclick=()=>app.safe(()=>{let t=draft.layers[active].texture;if(t.kind!=='udim'){t={kind:'udim',name:t.name,tiles:{1001:t},missing:[0,0,0,0]};draft.layers[active].texture=t;}if(!t.tiles[tileId])t.tiles[tileId]=createPaintTexture({size:256});sync();});
 $('#paint-import').onclick=()=>app.safe(async()=>{const [f]=await files('image/png,image/jpeg,image/webp');if(!f)return;const image=await decodeBitmap(f,f.name);let t=draft.layers[active].texture;if(t.kind==='udim')t.tiles[tileId]=image;else draft.layers[active].texture=image;sync();});
 $('#paint-undo').onclick=()=>{getPainter().undo();draw();};$('#paint-redo').onclick=()=>{getPainter().redo();draw();};$('#paint-export').onclick=()=>app.safe(()=>{const t=compositeLayers(draft),image=t.kind==='udim'?t.tiles[tileId]:t;if(!image)throw Error('No image in this tile');const c=document.createElement('canvas');c.width=image.width;c.height=image.height;c.getContext('2d').putImageData(new ImageData(Uint8ClampedArray.from(image.data),image.width,image.height),0,0);c.toBlob(b=>download(b,`${draft.name}.${tileId}.png`,'image/png'));});sync();
}

function fiberDialog(app){const {index,value:m}=selectedMaterial(app),f=validateFiber({roughness:.3,azimuthalRoughness:.3,ior:1.55,tilt:2,absorption:[.5,1,2],...m.fiber});app.dialog('Cylindrical fiber scattering',`${row('Enable fiber BSDF',box('fiber-enable',!!m.fiber))}${row('Longitudinal roughness',num('fiber-long',f.roughness,.03,1,.01))}${row('Azimuthal roughness',num('fiber-az',f.azimuthalRoughness,.03,1,.01))}${row('IOR',num('fiber-ior',f.ior,1.01,3,.01))}${row('Cuticle tilt · degrees',num('fiber-tilt',f.tilt,-15,15,.5))}${row('RGB absorption / diameter',vec('fiber-sigma',f.absorption))}<p class="production-note">Energy-weighted R, TT, TRT and higher-order scattering lobes are evaluated and sampled in the actual path tracer. Strand tangent and radius come from the hair mesh. Use the grooming workspace to author strand direction.</p>`,()=>{const enabled=$('#fiber-enable').checked,fiber=validateFiber({roughness:number('fiber-long'),azimuthalRoughness:number('fiber-az'),ior:number('fiber-ior'),tilt:number('fiber-tilt'),absorption:readVec('fiber-sigma')});app.mutate('Fiber material',()=>{if(enabled)app.doc.materials[index].fiber=fiber;else delete app.doc.materials[index].fiber;});},'Apply material');}
function groomDialog(app){const o=app.requireObject();if(o.procedural?.kind!=='hair')throw Error('Create and select a hair object first');const emitter=app.doc.objects.find(x=>x.id===o.procedural.source),mesh=app.geometry.get(emitter);let groom=structuredClone(o.procedural.groom||createGroom(mesh,{count:Math.min(80,o.procedural.count||80),segments:o.procedural.segments||8,length:o.procedural.length||.5,seed:o.procedural.seed||1}));let brush=new GroomBrush(groom),stroke=false,last=null;
 const wm=worldMatrix(app.doc,o),inv=inverse(wm),b=bounds(mesh),center=b.min.map((v,i)=>(v+b.max[i])*.5),scale=Math.max(.01,...b.max.map((v,i)=>v-b.min[i]),o.procedural.length||.5),camera={...structuredClone(app.doc.camera),target:transformPoint(wm,add(center,[0,(o.procedural.length||.5)*.5,0])),distance:scale*3.2};
 app.dialog('Guide grooming',`<div class="advanced-two"><div><canvas id="groom-surface" class="advanced-canvas" width="820" height="620" aria-label="Hair guide grooming canvas"></canvas><div id="groom-stats" class="advanced-stats"></div></div><div class="advanced-panel">${row('Brush',choice('groom-mode',['comb','smooth','cut','length','puff','clump'],'comb'))}${row('Radius · local units',num('groom-radius',scale*.3,.001,1e4,.02))}${row('Strength',num('groom-strength',.35,0,1,.05))}${row('Target length',num('groom-length',o.procedural.length||.5,.001,100,.05))}${row('Guide count',num('groom-count',groom.guides.length,2,2000,1))}<div class="production-actions">${button('groom-regenerate','Regenerate')}${button('groom-undo','Undo stroke')}${button('groom-redo','Redo stroke')}</div><p class="production-note">Drag over the projected guides to comb, smooth, cut, lengthen, puff or clump them. Roots remain bound to source triangles. Pressure controls strength; the resulting guides deform every generated render strand.</p></div></div>`,()=>{if(stroke)brush.end();app.mutate('Groom hair guides',()=>o.procedural.groom=groom);},'Apply groom',1100);
 const canvas=$('#groom-surface'),ctx=canvas.getContext('2d'),screen=p=>project(camera,transformPoint(wm,p),820,620);
 function draw(){ctx.clearRect(0,0,820,620);ctx.lineWidth=1;ctx.strokeStyle='#d1ab79';for(const g of groom.guides){ctx.beginPath();g.points.forEach((p,i)=>{const q=screen(p);i?ctx.lineTo(q[0],q[1]):ctx.moveTo(q[0],q[1]);});ctx.stroke();const q=screen(g.points[0]);ctx.fillStyle='#7fd0b5';ctx.fillRect(q[0]-2,q[1]-2,4,4);}$('#groom-stats').textContent=`${groom.guides.length} root-bound guides · ${o.procedural.count||0} generated render strands · ${brush.undoStack.length} edits`;}
 function pointer(e){const r=canvas.getBoundingClientRect();return [(e.clientX-r.left)*820/r.width,(e.clientY-r.top)*620/r.height];}
 function hit(p){let best=null,dist=Infinity;for(const g of groom.guides)for(const q of g.points){const s=screen(q),d=Math.hypot(s[0]-p[0],s[1]-p[1]);if(d<dist){best=q;dist=d;}}return best;}
 function apply(e){const p=pointer(e),at=hit(p);if(!at)return;const cf=cameraFrame(camera,820/620),factor=camera.distance/620,dx=last?p[0]-last[0]:0,dy=last?p[1]-last[1]:0;const dir=transformVector(inv,add(mul(cf.right,dx*factor),mul(cf.up,-dy*factor)));brush.stroke({mode:$('#groom-mode').value,center:at,radius:number('groom-radius'),strength:number('groom-strength'),pressure:e.pointerType==='pen'?e.pressure:1,direction:dir,targetLength:number('groom-length')});last=p;draw();}
 canvas.onpointerdown=e=>app.safe(()=>{if(e.button)return;brush.begin();stroke=true;last=pointer(e);canvas.setPointerCapture(e.pointerId);apply(e);});canvas.onpointermove=e=>{if(stroke)app.safe(()=>apply(e));};canvas.onpointerup=e=>{if(stroke)brush.end();stroke=false;last=null;canvas.releasePointerCapture(e.pointerId);draw();};canvas.onpointercancel=()=>{brush.cancel();stroke=false;draw();};$('#groom-undo').onclick=()=>{brush.undo();draw();};$('#groom-redo').onclick=()=>{brush.redo();draw();};$('#groom-regenerate').onclick=()=>app.safe(()=>{groom=createGroom(mesh,{...o.procedural,count:number('groom-count')});brush=new GroomBrush(groom);draw();});draw();
}

function controllerDialog(app){
 const o=app.requireObject(),example=[{path:'position',axis:0,kind:'oscillator',amplitude:1,frequency:.25,offset:o.position[0]}];
 app.dialog('Transform controllers',`<p class="production-note">Controllers replace or blend local transform components after keyframe evaluation. Cubic curves use inSlope/outSlope tangents; expressions are bounded arithmetic ASTs, not executable JavaScript.</p>${area('controller-data',o.controllers||example)}<div class="production-actions">${button('controller-none','Clear')}${button('controller-sine','Oscillator')}${button('controller-curve','Cubic curve')}</div>`,()=>{
  const data=parse('controller-data');if(!Array.isArray(data))throw Error('Controller stack must be an array');const draft=structuredClone(app.doc);draft.objects.find(x=>x.id===o.id).controllers=data;validateDocument(draft);for(const x of draft.objects)worldMatrix(draft,x);app.mutate('Transform controllers',()=>o.controllers=data);
 },'Apply controllers',740);
 $('#controller-none').onclick=()=>$('#controller-data').value='[]';$('#controller-sine').onclick=()=>$('#controller-data').value=JSON.stringify(example,null,2);
 $('#controller-curve').onclick=()=>$('#controller-data').value=JSON.stringify([{path:'position',axis:0,kind:'curve',extrapolation:'cycle',interpolation:'bezier',keys:[{frame:0,value:o.position[0],outSlope:.1},{frame:60,value:o.position[0]+2,inSlope:0}]}],null,2);
}
function constraintDialog(app){
 const o=app.requireObject(),targets=app.doc.objects.filter(x=>x.id!==o.id),target=targets[0]?.id;
 app.dialog('Transform constraints',`${row('Add constraint',choice('constraint-type',['copyPosition','copyRotation','copyScale','parent','aim','limit','path','blendParents'],'copyPosition'))}${row('Target',choice('constraint-target',targets.map(o=>[o.id,o.name]),target))}<div class="production-actions">${button('constraint-add','Append constraint')}${button('constraint-clear','Clear stack')}</div>${area('constraint-data',o.constraints||[])}<p class="production-note">Constraints are evaluated in order in world space. Target dependencies are validated and cycles rejected. The editor exposes influence, offsets, axes, path points and animated parameters.</p>`,()=>{
  const data=parse('constraint-data');if(!Array.isArray(data))throw Error('Constraints must be an array');const draft=structuredClone(app.doc);draft.objects.find(x=>x.id===o.id).constraints=data;validateDocument(draft);for(const x of draft.objects)worldMatrix(draft,x);app.mutate('Transform constraint stack',()=>o.constraints=data);
 },'Apply constraints',800);
 $('#constraint-clear').onclick=()=>$('#constraint-data').value='[]';$('#constraint-add').onclick=()=>app.safe(()=>{
  const type=$('#constraint-type').value,target=$('#constraint-target').value;let c={type,target,influence:1};
  if(type==='limit')c={type,position:{min:[-10,-10,-10],max:[10,10,10]}};
  if(type==='path')c={type,points:[[0,0,0],[1,1,0],[2,0,1],[3,1,0]],parameter:{op:'div',args:[{variable:'frame'},120]},closed:false,follow:true};
  if(type==='blendParents')c={type,targets:[{id:target,weight:1}],influence:1};const data=parse('constraint-data');data.push(c);$('#constraint-data').value=JSON.stringify(data,null,2);
 });
}
function autoBoneMap(source,target){const normalized=s=>s.toLowerCase().replace(/[^a-z0-9]/g,'').replace(/^(mixamorig|armature)/,'');const src=new Map();source.bones.forEach((b,i)=>{const name=normalized(b.name);if(src.has(name))src.set(name,null);else src.set(name,i);});const mapping={};target.bones.forEach((b,i)=>{const j=src.get(normalized(b.name));if(Number.isInteger(j))mapping[i]=j;});return mapping;}
function rootMotionScale(source,target,mapping){let s=0,t=0;for(const [i,j] of Object.entries(mapping)){const a=target.bones[i],b=source.bones[j];if(a?.parent>=0&&b?.parent>=0){const tp=inverse(target.inverseBind[i]).slice(12,15),tq=inverse(target.inverseBind[a.parent]).slice(12,15),sp=inverse(source.inverseBind[j]).slice(12,15),sq=inverse(source.inverseBind[b.parent]).slice(12,15);t+=Math.hypot(...tp.map((x,k)=>x-tq[k]));s+=Math.hypot(...sp.map((x,k)=>x-sq[k]));}}return s>1e-9&&t>1e-9?t/s:1;}
function retargetDialog(app){const target=app.requireObject();if(!target.rig)throw Error('Select a target object with a skeleton');const sources=app.doc.objects.filter(o=>o.id!==target.id&&o.rig);if(!sources.length)throw Error('Import or create a second skeleton to use as the animation source');app.dialog('Retarget skeletal animation',`${row('Source skeleton',choice('retarget-source',sources.map(o=>[o.id,o.name]),sources[0].id))}${row('First frame',num('retarget-first',app.doc.animation.start,0,1e6,1))}${row('Last frame',num('retarget-last',app.doc.animation.end,0,1e6,1))}${row('Sample step',num('retarget-step',1,.01,1e4,1))}${row('Root translation',box('retarget-root',true))}${row('Auto root scale',box('retarget-scale',true))}${area('retarget-map',autoBoneMap(sources[0].rig,target.rig))}<p class="production-note">Map target bone names or indices to source bone names or indices. Bind-pose orientation deltas compensate different rest directions. Root motion can be scaled by mapped bone lengths. Existing target skin weights and inverse-bind matrices remain unchanged.</p>`,()=>{const source=app.doc.objects.find(o=>o.id===$('#retarget-source').value),rig=retargetRig(source.rig,target.rig,parse('retarget-map'),{start:number('retarget-first'),end:number('retarget-last'),step:number('retarget-step'),translateRoot:$('#retarget-root').checked,rootScale:$('#retarget-scale').checked?rootMotionScale(source.rig,target.rig,parse('retarget-map')):1});app.mutate('Retarget skeletal animation',()=>target.rig=rig);},'Bake retargeted keys',750);$('#retarget-source').onchange=()=>$('#retarget-map').value=JSON.stringify(autoBoneMap(app.doc.objects.find(o=>o.id===$('#retarget-source').value).rig,target.rig),null,2);}
function dynamicsDialog(app){const o=app.requireObject(),s=o.simulation||{},type=s.type||'rigid';app.dialog('Scene dynamics',`${row('Object role',choice('dynamics-type',[['rigid','Rigid body · shared scene world'],['cloth','Cloth · XPBD'],['collider','Static / animated mesh collider'],['none','No simulation']],type))}${row('Rigid shape',choice('dynamics-shape',['sphere','convex'],s.shape||'convex'))}${row('Mass · kg',num('dynamics-mass',s.body?.mass??1,0,1e6,.1))}${row('Initial velocity',vec('dynamics-velocity',s.body?.velocity||[0,0,0]))}${row('Restitution',num('dynamics-bounce',s.body?.restitution??.15,0,1,.05))}${row('Friction',num('dynamics-friction',s.body?.friction??.45,0,1,.05))}${row('Cloth thickness',num('dynamics-thickness',s.thickness??.02,.0001,10,.005))}${row('Self-collision',box('dynamics-self',s.selfCollision!==false))}${row('Pin top row of cloth',box('dynamics-pins',true))}<p class="production-note">All attached rigid bodies now share one world and collide with one another. Convex bodies use separating axes and angular impulses. Mesh colliders can be animated. Cloth uses mesh and self contacts; simulation is evaluated deterministically while scrubbing.</p>`,()=>{const role=$('#dynamics-type').value,mesh=cloneMesh(app.geometry.get(o));const settings={type:role,shape:$('#dynamics-shape').value,body:{mass:number('dynamics-mass'),velocity:readVec('dynamics-velocity'),restitution:number('dynamics-bounce'),friction:number('dynamics-friction')},thickness:number('dynamics-thickness'),selfCollision:$('#dynamics-self').checked};if(role==='cloth'&&$('#dynamics-pins').checked){const b=bounds(mesh);settings.pins=Array.from({length:mesh.positions.length/3},(_,i)=>i).filter(i=>vertex(mesh,i)[1]>=b.max[1]-1e-5);}app.mutate('Scene dynamics role',()=>{if(role==='collider'){o.simulation={type:'collider',friction:settings.body.friction};delete o.collider;}else if(role==='none'){delete o.simulation;delete o.collider;}else{replaceGeometry(o,mesh);delete o.collider;o.simulation=settings;}});},'Apply dynamics',710);}
function fluidDialog(app){app.dialog('Incompressible particle fluid',`${row('Block center',vec('fluid-center',[0,1.5,0]))}${row('Block size',vec('fluid-size',[.65,.65,.65]))}${row('Particle spacing',num('fluid-spacing',.15,.02,2,.01))}${row('Viscosity',num('fluid-viscosity',.025,0,1,.01))}${row('Vorticity confinement',num('fluid-vorticity',.1,0,10,.05))}${row('Surface cell size',num('fluid-cell',.15,.02,2,.01))}${row('Domain minimum',vec('fluid-min',[-2,0,-2]))}${row('Domain maximum',vec('fluid-max',[2,4,2]))}<p class="production-note">Creates a deterministic position-based incompressible fluid with hashed neighbors, viscosity, vorticity and collision projection. The viewport and renderer receive a reconstructed surface mesh. This CPU solver has explicit particle and meshing budgets.</p>`,()=>{const size=readVec('fluid-size'),center=readVec('fluid-center'),spacing=number('fluid-spacing'),positions=fluidBlock({min:sub(center,mul(size,.5)),size,spacing}),o=newObject('mesh',{},'Fluid surface');o.material=app.doc.materials.length;o.position=[0,0,0];o.mesh=empty();o.simulation={type:'fluid',positions,spacing,viscosity:number('fluid-viscosity'),vorticity:number('fluid-vorticity'),bounds:{min:readVec('fluid-min'),max:readVec('fluid-max')},surface:true,meshing:{cellSize:number('fluid-cell'),maxCells:262144}};app.mutate('Create particle fluid',()=>{app.doc.materials.push(material('Fluid dielectric','#a3d1f0',{transmission:.92,roughness:.045,ior:1.333}));app.doc.objects.push(o);app.selected=new Set([o.id]);});},'Create fluid',710);}
function volumeDialog(app){let draft=structuredClone(app.doc.volumes||[]);app.dialog('Volume regions · heterogeneous and nested',`<div class="production-actions">${button('volume-fog','Add homogeneous region')}${button('volume-cloud','Add sparse cloud')}${button('volume-import-grid','Import density grid')}</div>${area('volume-data',draft)}<p class="production-note">Regions use affine index-to-world transforms. Dense grids and sparse 8³ blocks are sampled trilinearly. Additive regions mix coefficients; replace regions override lower priorities, including empty grid cells. Closed dielectric and subsurface solids maintain a separate nested interior stack.</p>`,()=>{draft=parse('volume-data');if(!Array.isArray(draft)||draft.length>32)throw Error('Use an array of at most 32 regions');draft.forEach(validateVolume);app.mutate('Volume regions',()=>app.doc.volumes=draft);},'Apply regions',920);
 const append=v=>{const a=parse('volume-data');a.push(v);$('#volume-data').value=JSON.stringify(a,null,2);};$('#volume-fog').onclick=()=>append({name:'Fog',min:[-1,0,-1],max:[1,2,1],density:.3,color:[.9,.95,1],anisotropy:.15,priority:0,replace:false,emission:[0,0,0]});$('#volume-cloud').onclick=()=>app.safe(()=>append({name:'Sparse cloud',min:[-1,0,-1],max:[1,2,1],density:2,color:[.95,.97,1],anisotropy:.25,priority:1,replace:false,grid:proceduralDensity({dimensions:[16,16,16],frequency:3,seed:1})}));$('#volume-import-grid').onclick=()=>app.safe(async()=>{const[f]=await files('.json');if(!f)return;const grid=JSON.parse(await f.text()),v={name:f.name,min:[-1,0,-1],max:[1,2,1],density:1,color:[1,1,1],grid};validateVolume(v);append(v);});}
async function exrDialog(app){if(!app.gpuReady||!app.renderer.samples)throw Error('Render a path-traced image before EXR export');app.dialog('OpenEXR output',`${row('Compression',choice('exr-compression',['ZIP','ZIPS','NONE'],'ZIP'))}${row('Pixel layout',choice('exr-layout',[['single','Single part · all AOV channels'],['multipart','Multipart · beauty and guides']],'multipart'))}${row('Beauty precision',choice('exr-type',[['FLOAT','32-bit float'],['HALF','16-bit half']],'FLOAT'))}<p class="production-note">Writes standard scanline ZIP/ZIPS data with FLOAT, HALF and UINT channels. Object IDs remain integers. Half conversion is checked for overflow; deep and tiled output are not implied by multipart support.</p>`,async()=>{const image=app.productionResult||{hdr:await app.renderer.readHDR(),aovs:await app.renderer.readAOVs()},channels=renderChannels(image.hdr,image.aovs),pixelType=$('#exr-type').value,types=Object.fromEntries(Object.entries(channels).map(([name,data])=>[name,data instanceof Uint32Array?'UINT':pixelType])),name=app.doc.name.replace(/[^a-z0-9_-]/gi,'_'),compression=$('#exr-compression').value;let options={width:image.hdr.width,height:image.hdr.height,channels,types,compression};if($('#exr-layout').value==='multipart'){const beauty=Object.fromEntries(Object.entries(channels).filter(([n])=>['R','G','B','A'].includes(n))),guides=Object.fromEntries(Object.entries(channels).filter(([n])=>!['R','G','B','A'].includes(n)));options={parts:[{...options,name:'beauty',channels:beauty},...(Object.keys(guides).length?[{...options,name:'guides',channels:guides}]:[])]};}download(await encodeEXRAdvanced(options),name+'.exr','image/x-exr');},'Export EXR',640);}

export function installAdvancedTools(app){style();const commands={bevel:['Segmented bevel','modifier',()=>bevelDialog(app)],boolean:['Exact solid Boolean','box',()=>exactBooleanDialog(app)],udim:['Pack UDIM islands','uv',()=>udimDialog(app)],texturePaint:['Texture painting','material',()=>paintDialog(app)],fiber:['Fiber scattering','material',()=>fiberDialog(app)],groom:['Groom hair guides','curve',()=>groomDialog(app)],controllers:['Transform controllers','curve',()=>controllerDialog(app)],constraints:['Constraint stack','link',()=>constraintDialog(app)],retarget:['Retarget animation','play',()=>retargetDialog(app)],sceneDynamics:['Scene dynamics','settings',()=>dynamicsDialog(app)],fluid:['Particle fluid','sphere',()=>fluidDialog(app)],media:['Volume regions','render',()=>volumeDialog(app)],exportEXR:['Export compressed OpenEXR','save',()=>exrDialog(app)]};for(const[id,[label,icon,fn]]of Object.entries(commands))app.commands[id]={label,icon,fn};const additions={Model:['udim'],Create:['fluid'],Animation:['controllers','constraints','retarget','sceneDynamics','groom'],Render:['texturePaint','fiber']};for(const[group,ids]of Object.entries(additions))app.extraMenus[group]=[...new Set([...(app.extraMenus[group]||[]),...ids])];}
