import { icon } from './icons.js';
import { MODIFIERS } from '../geometry/modifiers.js';
import { triangulate } from '../geometry/mesh.js';
export const escapeHTML = s => String(s).replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));
const row = (label, control) => `<div class="form-row"><label>${label}</label>${control}</div>`;
const number = (id, value, min, max, step = .1) => `<input type="number" data-field="${id}" value="${Number(value.toFixed(4))}" ${min !== undefined ? `min="${min}"` : ''} ${max !== undefined ? `max="${max}"` : ''} step="${step}" aria-label="${id}">`;
const slider = (id, value, min, max, step = .01) => `<input type="range" data-field="${id}" min="${min}" max="${max}" step="${step}" value="${value}" aria-label="${id}"><output>${Number(value.toFixed(2))}</output>`;
const section = (title, content, badge = '') => `<section class="inspector-section"><div class="section-title">${title}${badge ? `<span class="badge">${badge}</span>` : ''}</div>${content}</section>`;
const btn = (cmd, label, ic = 'plus') => `<button class="small-button wide" data-command="${cmd}">${icon(ic)}${label}</button>`;
export function renderInspector(app) {
    const target = document.querySelector('#inspector'), o = app.activeObject, tab = app.inspectorTab, d = app.doc;
    document.querySelectorAll('[data-tab]').forEach(b => b.classList.toggle('active', b.dataset.tab === tab));
    if (tab === 'render') {
        target.innerHTML = `<div class="inspector-title"><span class="object-icon">${icon('render')}</span><div><b>Aureon Ray</b><div class="sub" style="margin-top:5px">WebGPU · Monte Carlo path tracer</div></div></div>` + section('Sampling', row('Target samples', number('settings.samples', d.settings.samples, 1, 8192, 1)) + row('Max path depth', number('settings.bounces', d.settings.bounces, 1, 32, 1)) + row('Resolution scale', `<select data-field="settings.resolution">${[.25, .5, .75, 1, 1.5, 2].map(v => `<option value="${v}" ${v === d.settings.resolution ? 'selected' : ''}>${Math.round(v * 100)}%</option>`).join('')}</select>`) + `<p class="note">Progressive accumulation. Sampling restarts when scene, camera, or integrator settings change. Resolution is bounded by the pixel and device memory limits.</p>`) + section('Lighting & display', row('Environment', slider('settings.environment', d.settings.environment, 0, 3)) + row('Exposure (EV)', slider('settings.exposure', d.settings.exposure, -4, 4, .1)) + `<p class="note">Emissive meshes are area lights. The studio viewport uses preview lighting; path tracing uses the actual scene lights.</p>`) + section('Physical camera', row('Field of view', number('camera.fov', d.camera.fov, 10, 120, 1)) + row('Aperture radius', number('camera.aperture', d.camera.aperture, 0, .5, .005)) + row('Focus distance', number('camera.focus', d.camera.focus, .1, 200, .1)) + btn('focusDistance', 'Focus at orbit target', 'camera')) + section('Render output', btn('toggleRender', app.renderer?.mode === 'trace' ? 'Return to modeling' : 'Start path tracing', 'render') + btn('restartRender', 'Restart accumulation', 'rotate') + btn('exportPNG', 'Save displayed PNG', 'camera') + btn('exportHDR', 'Export linear HDR (.pfm)', 'download') + btn('diagnostics', 'Renderer diagnostics', 'info'));
        target.innerHTML += section('Production',btn('productionSettings','Integrator, photons & denoise','render')+btn('productionRender','Render frame / motion blur','camera')+btn('exportEXR','Export EXR + AOVs','download')+btn('distributed','Distributed rendering','render'));
        return;
    }
    if (tab === 'material') {
        const index = app.materialIndex ?? o?.material ?? 0, m = d.materials[index];
        if (!m) {
            target.innerHTML = '';
            return;
        }
        target.innerHTML = `<div class="inspector-title"><span class="object-icon">${icon('sphere')}</span><div><input data-field="material.name" value="${escapeHTML(m.name)}" aria-label="Material name"><div class="sub">Shared physically based surface</div></div></div>` + section('Surface', row('Base color', `<input type="color" data-field="material.color" value="${m.color}" aria-label="Base color">`) + row('Roughness', slider('material.roughness', m.roughness, 0, 1)) + row('Metalness', slider('material.metallic', m.metallic, 0, 1)) + row('Transmission', slider('material.transmission', m.transmission, 0, 1)) + row('Index of refraction', number('material.ior', m.ior, 1, 3, .01))) + section('Emission', row('Radiance multiplier', number('material.emission', m.emission, 0, 10000, .5)) + `<p class="note">A positive multiplier turns this surface into a sampled mesh light. Glass uses an ideal, smooth dielectric transmission lobe.</p>`) + section('Procedural texture', row('Pattern', `<select data-field="material.pattern">${['solid', 'checker', 'marble', 'wood'].map(p => `<option ${m.pattern === p ? 'selected' : ''}>${p}</option>`).join('')}</select>`) + row('Pattern scale', number('material.patternScale', m.patternScale, .01, 100, .1)) + btn('uvEditor', 'Open UV editor', 'uv')) + section('Material actions', btn('applyMaterial', 'Apply to selection', 'check') + btn('duplicateMaterial', 'Duplicate material', 'duplicate') + btn('newMaterial', 'Create material', 'plus'));
        target.innerHTML += section('Textures & transport',btn('bitmap','Bitmap textures','folder')+btn('shaderGraph','Material node graph','stack')+btn('media','Volume / subsurface','sphere'));
        return;
    }
    if (!o) {
        target.innerHTML = `<div class="empty-state">${icon('cursor')}Select an object to inspect it.<br>Use the viewport or scene explorer.</div>` + section('Scene', row('Objects', `<span>${d.objects.length}</span>`) + row('Materials', `<span>${d.materials.length}</span>`) + btn('create', 'Create geometry', 'plus'));
        return;
    }
    const mesh = app.geometry.get(o), params = Object.entries(o.params || {}).filter(([k, v]) => typeof v === 'number');
    let html = `<div class="inspector-title"><span class="object-icon">${icon(o.type)}</span><div style="min-width:0;flex:1"><input data-field="object.name" value="${escapeHTML(o.name)}" aria-label="Object name"><div class="sub">${o.type === 'mesh' ? 'Editable polygon mesh' : 'Parametric ' + o.type} · ${mesh.faces.length.toLocaleString()} polygons</div></div></div>`;
    if (tab === 'object') {
        html += section('Transform', ['position', 'rotation', 'scale'].map(key => `<div class="xyz-label">${key === 'position' ? 'Position' : key === 'rotation' ? 'Rotation · degrees' : 'Scale'}</div><div class="xyz">${[0, 1, 2].map(i => `<label class="axis-field"><span>${'XYZ'[i]}</span>${number(`object.${key}.${i}`, o[key][i], undefined, undefined, key === 'rotation' ? 1 : .05)}</label>`).join('')}</div>`).join('') + `<div class="button-row" style="margin-top:12px"><button class="small-button" data-command="resetTransform">Reset</button><button class="small-button" data-command="frameSelection">${icon('fit')}Frame</button></div>`, 'LOCAL');
        html += section('Geometry', params.map(([key, value]) => row(key.replace(/([A-Z])/g, ' $1').replace(/^./, x => x.toUpperCase()), number(`params.${key}`, value, key.toLowerCase().includes('segment') || ['rings', 'sides'].includes(key) ? 3 : .001, key.toLowerCase().includes('segment') || ['rings', 'sides'].includes(key) ? 128 : 100, key.toLowerCase().includes('segment') || ['rings', 'sides'].includes(key) ? 1 : .05))).join('') + row('Vertices', `<span>${(mesh.positions.length / 3).toLocaleString()}</span>`) + row('Triangles', `<span>${triangulate(mesh).length.toLocaleString()}</span>`) + btn('convertMesh', 'Convert to editable mesh', 'mesh'));
        html += section('Scene properties', row('Material', `<select data-field="object.material">${d.materials.map((m, i) => `<option value="${i}" ${o.material === i ? 'selected' : ''}>${escapeHTML(m.name)}</option>`).join('')}</select>`) + row('Parent', `<select data-field="object.parent"><option value="">Scene root</option>${d.objects.filter(p => p.id !== o.id).map(p => `<option value="${p.id}" ${p.id === o.parent ? 'selected' : ''}>${escapeHTML(p.name)}</option>`).join('')}</select>`) + row('Visible', `<input data-field="object.visible" type="checkbox" ${o.visible ? 'checked' : ''}>`) + row('Visible to camera', `<input data-field="object.cameraVisible" type="checkbox" ${o.cameraVisible !== false ? 'checked' : ''}>`) + row('Lock selection', `<input data-field="object.locked" type="checkbox" ${o.locked ? 'checked' : ''}>`) + `<p class="note">Changing parent keeps local transform channels. World-space placement may change.</p>`);
    }
    html += section('Modifier stack', `<select id="modifier-select" style="width:100%;font-size:10px"><option value="">Add modifier…</option>${Object.entries(MODIFIERS).map(([key, m]) => `<option value="${key}">${m.label}</option>`).join('')}</select>` + o.modifiers.map((m, i) => `<div class="stack-item"><div class="stack-item-head"><input type="checkbox" data-mod-enabled="${i}" ${m.enabled !== false ? 'checked' : ''} aria-label="Enable ${MODIFIERS[m.type].label}"><span>${MODIFIERS[m.type].label}</span><button data-mod-up="${i}" title="Move up">↑</button><button data-mod-down="${i}" title="Move down">↓</button><button data-mod-delete="${i}" title="Remove">×</button></div><div class="form-row">${slider(`modifier.${i}`, m.value, MODIFIERS[m.type].min, MODIFIERS[m.type].max, MODIFIERS[m.type].step)}</div></div>`).join('') + `<div class="stack-base" style="margin-top:8px">${icon(o.type)}${o.type === 'mesh' ? 'Editable mesh' : o.type[0].toUpperCase() + o.type.slice(1)}</div>` + (o.modifiers.length ? btn('collapseStack', 'Collapse evaluated stack', 'stack') : '') + `<p class="note">Evaluated from top to bottom. Source geometry remains unchanged until you collapse the stack.</p>`, String(o.modifiers.length));
    if (tab === 'modify') {
        html += section('Polygon modeling', row('Active face', `<span>${app.selectedFace >= 0 ? app.selectedFace : 'None'}</span>`) + btn('extrude', 'Extrude selected polygon', 'mesh') + btn('inset', 'Inset selected polygon', 'mesh') + btn('deleteFace', 'Delete selected polygon', 'trash') + btn('weld', 'Weld coincident vertices', 'mesh') + btn('smoothNormals', 'Toggle smooth normals', 'sphere') + btn('uvEditor', 'Edit UV coordinates', 'uv'));
    }
    html += section('Production tools',btn('boolean','Solid boolean','mesh')+btn('rig','Skeleton / skin / IK','curve')+btn('cloth','Cloth simulation','mesh')+btn('rigid','Rigid proxy simulation','mesh')+btn('hair','Surface hair','curve')+btn('bakeCache','Bake deformation','curve'));
    target.innerHTML = html;
}
