/** Production workspaces. Each command changes the same native scene consumed
 * by GeometryCache, the viewport, the compute renderer, and file exporters. */
import { inverse, matMul } from '../core/math.js';
import { booleanMesh, transformMesh } from '../geometry/boolean.js';
import { cloneMesh } from '../geometry/mesh.js';
import { newObject, worldMatrix, GeometryCache, validateDocument } from '../scene/document.js';
import { createChainRig, automaticWeights, setVertexWeights, quatEuler, eulerQuat, bonePose, solveRigIK } from '../animation/rig.js';
import { NODE_TYPES, compileGraph, checkerGraph } from '../materials/graph.js';
import { decodeBitmap } from '../materials/textures.js';
import { importGLTF, exportGLTF2 } from '../io/gltf.js';
import { parsePLY, exportPLY, exportUSDA } from '../io/interchange.js';
import { encodeEXR, renderChannels } from '../io/exr.js';
import { download } from '../io/formats.js';
import { renderProduction } from '../render/production.js';
import { escapeHTML as esc } from './inspector.js';

const $ = s => document.querySelector(s);
const row = (label, html) => `<div class="form-row"><label>${label}</label>${html}</div>`;
const num = (id,v,min=-1e6,max=1e6,step=.1) => `<input id="${id}" type="number" value="${v}" min="${min}" max="${max}" step="${step}" aria-label="${id}">`;
const check = (id,v) => `<input type="checkbox" id="${id}" ${v?'checked':''}>`;
const select = (id,values,current) => `<select id="${id}">${values.map(v=>{const [key,label]=Array.isArray(v)?v:[v,v];return `<option value="${esc(key)}" ${String(key)===String(current)?'selected':''}>${esc(label)}</option>`;}).join('')}</select>`;
const value = id => { const e=$('#'+id),n=Number(e.value);if(!Number.isFinite(n)||n<Number(e.min)||n>Number(e.max))throw Error(`Invalid ${id}`);return n; };
const vector = (prefix,v) => `<div class="xyz">${v.map((n,i)=>num(prefix+i,n)).join('')}</div>`;
const readVector = p => [0,1,2].map(i=>value(p+i));
const button = (id,label) => `<button type="button" class="small-button" id="${id}">${label}</button>`;
const emptyMesh = () => ({positions:[],faces:[],uvs:[],smooth:true});
function bindMesh(o,mesh) {o.type='mesh';o.mesh=mesh;o.params={};o.modifiers=[];delete o.rig;delete o.simulation;delete o.procedural;delete o.meshCache;delete o.morphTargets;delete o.morphWeights;}
function currentMaterial(app) {const index=app.materialIndex??app.activeObject?.material??0;return {index,material:app.doc.materials[index]};}
function inputFiles(accept,multiple=false) {return new Promise(resolve=>{const input=document.createElement('input');input.type='file';input.accept=accept;input.multiple=multiple;input.onchange=()=>resolve([...input.files]);input.oncancel=()=>resolve([]);input.click();});}
function installStyle() {
    if($('#production-style'))return;
    const style=document.createElement('style');style.id='production-style';style.textContent=`
    .production-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(210px,1fr));gap:14px}.production-card{padding:14px;background:var(--surface,#20252d);border:1px solid #465162;border-radius:8px}.production-card h3{margin-top:0}.production-card p{line-height:1.5}.production-actions{display:flex;gap:8px;flex-wrap:wrap;margin:12px 0}.production-scroll{max-height:64vh;overflow:auto}.node-workspace{height:480px;overflow:auto;position:relative;background:#161c24;border-radius:8px}.node-stage{width:1300px;min-height:900px;position:relative}.node-wires{position:absolute;inset:0;pointer-events:none;width:100%;height:100%;overflow:visible}.shade-node{position:absolute;width:206px;box-sizing:border-box;background:#26303b;border:1px solid #71839d;border-radius:8px;padding:10px;box-shadow:0 5px 18px #0005}.shade-node h4{margin:0 0 10px;cursor:move;touch-action:none;color:#eef3fa}.shade-node select,.shade-node input{max-width:120px;min-width:60px}.shade-node .form-row{font-size:11px;margin:5px 0;gap:6px}.shade-node .form-row label{max-width:70px}.shade-node button{float:right}.production-log{white-space:pre-wrap;max-height:240px;overflow:auto;font:12px/1.6 monospace}.production-progress{width:100%;margin:12px 0}.production-note{line-height:1.6;opacity:.8}.rig-list{max-height:160px;overflow:auto;font:12px/1.7 monospace}`;document.head.append(style);
}

function booleanDialog(app) {
    const objects=app.doc.objects.filter(o=>!o.locked&&o.visible), selected=[...app.selected];
    if(objects.length<2)throw Error('Boolean operations need two visible, unlocked closed solids.');
    app.dialog('Solid boolean modeling',row('Target A',select('bool-a',objects.map(o=>[o.id,o.name]),selected[0]||objects[0].id))+row('Operand B',select('bool-b',objects.map(o=>[o.id,o.name]),selected[1]||objects.find(o=>o.id!==selected[0])?.id))+row('Operation',select('bool-op',[['union','Union'],['subtract','A minus B'],['intersect','Intersection']],'subtract'))+row('Hide operands',check('bool-hide',true))+'<p class="production-note">Evaluates both modifier stacks, brings B into A’s local space, and splits the actual polygon solids. Operands must be closed, consistently oriented manifolds. The result is an editable mesh; both originals remain in the scene.</p>',()=>{
        const a=app.doc.objects.find(o=>o.id===$('#bool-a').value),b=app.doc.objects.find(o=>o.id===$('#bool-b').value);
        if(a===b)throw Error('Choose two different objects.');
        const local=matMul(inverse(worldMatrix(app.doc,a)),worldMatrix(app.doc,b));
        const mesh=booleanMesh(app.geometry.get(a),transformMesh(app.geometry.get(b),local),$('#bool-op').value);
        app.mutate('Solid boolean',()=>{const out=newObject('mesh',{},`${a.name} · ${$('#bool-op').value}`);out.mesh=mesh;out.parent=a.parent;for(const k of ['position','rotation','scale'])out[k]=[...a[k]];out.material=a.material;out.materialSlots=[a.material,b.material];app.doc.objects.push(out);if($('#bool-hide').checked)a.visible=b.visible=false;app.selected=new Set([out.id]);});
    },'Create result',560);
}
function rigDialog(app) {
    const object=app.requireObject();
    if(!object.rig){app.dialog('Bind a skeleton',row('Chain joints',num('rig-count',4,2,64,1))+row('Skinning method',select('rig-mode',['linear','dualQuaternion'],'linear'))+'<p class="production-note">The evaluated mesh is bound to a vertical chain. Four nearest segment influences are normalized per vertex. Imported glTF skeletons retain their joint hierarchy instead.</p>',()=>app.mutate('Bind skeleton',()=>{const mesh=cloneMesh(app.geometry.get(object));bindMesh(object,mesh);object.rig=createChainRig(mesh,value('rig-count'));object.rig.mode=$('#rig-mode').value;}),'Bind',520);return;}
    if(object.rig.externalJoints){app.dialog('Imported skeleton','<p>This skin uses scene objects as joints. Select and transform/key the named joint objects in the scene explorer. Imported glTF animation channels are retained by the importer/exporter.</p><div class="rig-list">'+object.rig.externalJoints.map((id,i)=>esc(`${i}: ${app.doc.objects.find(o=>o.id===id)?.name||id}`)).join('<br>')+'</div>');return;}
    let draft=structuredClone(object.rig),active=0;
    const controls=()=>{const b=draft.bones[active],p=bonePose(b,app.doc.animation.frame);return row('Joint',select('rig-bone',draft.bones.map((b,i)=>[i,b.name]),active))+row('Local translation',vector('rig-p',p.position))+row('Rotation · degrees',vector('rig-r',eulerQuat(p.rotation)))+row('Scale',vector('rig-s',p.scale||[1,1,1]))+row('Skinning',select('rig-mode',['linear','dualQuaternion'],draft.mode))+row('Key this pose',check('rig-key',true));};
    app.dialog('Skeleton, weights & inverse kinematics',`<div id="rig-controls">${controls()}</div><div class="production-actions">${button('rig-pose','Store pose in draft')}${button('rig-auto','Recalculate weights')}</div><h3>Inverse kinematics · object-local target</h3>${row('End joint',select('rig-end',draft.bones.map((b,i)=>[i,b.name]),draft.bones.length-1))}${row('Root joint',select('rig-root',draft.bones.map((b,i)=>[i,b.name]),0))}${row('Target',vector('ik-t',[1,2,0]))}${row('Pole',vector('ik-p',[0,0,2]))}${row('Use pole',check('ik-pole',false))}${button('rig-ik','Solve and store IK pose')}<h3>Weight editor · vertex indices are mesh-local</h3>${row('Vertex',num('rig-vertex',Math.max(0,app.selectedVertex),0,draft.weights.length/4-1,1))}${row('Influences',`<input id="rig-influences" placeholder="0:0.75, 1:0.25" value="0:1">`)}${button('rig-weight-read','Read weights')} ${button('rig-weight','Set normalized weights')}<p id="rig-status" class="production-note">Pose edits are staged until Apply. Keys use quaternion interpolation. IK uses a length-preserving FABRIK solve.</p>`,()=>{storePose();app.mutate('Edit skeleton',()=>object.rig=draft);},'Apply rig',710);
    function storePose(){const b=draft.bones[active],pose={position:readVector('rig-p'),rotation:quatEuler(readVector('rig-r')),scale:readVector('rig-s')};if(pose.scale.some(v=>Math.abs(v)<1e-6))throw Error('Joint scale cannot be zero');Object.assign(b,pose);draft.mode=$('#rig-mode').value;if($('#rig-key').checked){const key={...structuredClone(pose),frame:app.doc.animation.frame};b.keys||=[];b.keys=b.keys.filter(k=>k.frame!==key.frame);b.keys.push(key);b.keys.sort((a,b)=>a.frame-b.frame);}}
    function bindControls(){$('#rig-bone').onchange=e=>{storePose();active=Number(e.target.value);$('#rig-controls').innerHTML=controls();bindControls();};}
    bindControls();$('#rig-pose').onclick=()=>app.safe(()=>{storePose();$('#rig-status').textContent='Pose stored in the draft.';});
    $('#rig-auto').onclick=()=>app.safe(()=>{Object.assign(draft,automaticWeights(object.mesh,draft));$('#rig-status').textContent='Weights recalculated from current joint positions.';});
    $('#rig-ik').onclick=()=>app.safe(()=>{storePose();const result=solveRigIK(draft,Number($('#rig-end').value),readVector('ik-t'),{rootBone:Number($('#rig-root').value),frame:app.doc.animation.frame,pole:$('#ik-pole').checked?readVector('ik-p'):null});draft=result.rig;$('#rig-controls').innerHTML=controls();bindControls();$('#rig-status').textContent=`IK residual: ${result.error.toPrecision(4)} · ${result.reachable?'within chain reach':'target beyond chain reach'}`;});
    $('#rig-weight-read').onclick=()=>app.safe(()=>{const i=value('rig-vertex')*4;$('#rig-influences').value=Array.from({length:4},(_,k)=>`${draft.indices[i+k]}:${draft.weights[i+k].toFixed(5)}`).join(', ');});
    $('#rig-weight').onclick=()=>app.safe(()=>{const influences=$('#rig-influences').value.split(',').map(s=>{const [bone,weight]=s.trim().split(':').map(Number);return {bone,weight};});setVertexWeights(draft,value('rig-vertex'),influences);$('#rig-status').textContent='Weights normalized and stored in draft.';});
}
function simulationDialog(app,type='cloth') {
    const o=app.requireObject(),s=o.simulation||{};
    app.dialog(type==='cloth'?'XPBD cloth simulation':'Rigid-body sphere proxy',row('Gravity Y',num('sim-gravity',s.gravity?.[1]??-9.81,-100,100))+row('Local collision floor Y',num('sim-floor',s.floor??-o.position[1]))+row('Damping',num('sim-damping',s.damping??.6,0,50))+row('Compliance',num('sim-compliance',s.compliance??.000001,0,1,.000001))+row('Substeps',num('sim-substeps',s.substeps??4,1,32,1))+row('Constraint iterations',num('sim-iterations',s.iterations??10,1,64,1))+row('Pinned vertex indices',`<input id="sim-pins" value="${esc((s.pins||[0,1]).join(','))}" placeholder="0, 1">`)+row('Rigid collision radius',num('sim-radius',s.body?.radius??.5,.001,100))+row('Restitution',num('sim-bounce',s.body?.restitution??.35,0,1))+`<p class="production-note">${type==='cloth'?'Distance constraints include structural, shear and adjacent-face bend links. Pins stay at their bind positions.':'Contact uses a spherical collision proxy, not the detailed render mesh.'} Scrub from the animation start; simulation is deterministic and resets when seeking backward. Coordinates and floor are object-local.</p>`,()=>app.mutate('Attach simulation',()=>{const mesh=cloneMesh(app.geometry.get(o));bindMesh(o,mesh);const pins=$('#sim-pins').value.trim()?$('#sim-pins').value.split(',').map(Number):[];if(pins.some(i=>!Number.isInteger(i)||i<0||i>=mesh.positions.length/3))throw Error('Invalid pin index');o.simulation={type,gravity:[0,value('sim-gravity'),0],floor:value('sim-floor'),damping:value('sim-damping'),compliance:value('sim-compliance'),substeps:value('sim-substeps'),iterations:value('sim-iterations'),pins,body:{radius:value('sim-radius'),restitution:value('sim-bounce')}};}),'Attach',610);
}
function hairDialog(app) {
    const source=app.requireObject();
    app.dialog('Surface hair / curve geometry',row('Strands',num('hair-count',250,1,30000,1))+row('Length',num('hair-length',.4,.001,100))+row('Segments',num('hair-segments',6,1,128,1))+row('Root radius',num('hair-radius',.006,.0001,1,.001))+row('Ring sides',num('hair-sides',4,3,32,1))+row('Clump',num('hair-clump',.1,0,1))+row('Curl',num('hair-curl',.1,0,2))+row('Seed',num('hair-seed',1,0,2147483647,1))+row('Simulate strands',check('hair-dynamics',false))+'<p class="production-note">Creates seeded, surface-attached strands as tessellated curve tubes, rendered by the same material and light transport pipeline. Dynamics solve root-pinned distance constraints. Render → Fiber scattering enables cylindrical scattering; Animation → Groom hair guides edits root-bound guides.</p>',()=>app.mutate('Create surface hair',()=>{const o=newObject('mesh',{},source.name+' · hair');o.mesh=emptyMesh();o.parent=source.id;o.position=[0,0,0];o.material=source.material;o.procedural={kind:'hair',source:source.id,count:value('hair-count'),length:value('hair-length'),segments:value('hair-segments'),radius:value('hair-radius'),sides:value('hair-sides'),clump:value('hair-clump'),curl:value('hair-curl'),seed:value('hair-seed'),dynamics:$('#hair-dynamics').checked?{floor:-source.position[1]}:null};app.doc.objects.push(o);app.selected=new Set([o.id]);}),'Create hair',580);
}
function particleDialog(app) {
    app.dialog('Deterministic particle emitter',row('Particles / second',num('part-rate',50,.1,10000))+row('Lifetime · seconds',num('part-life',3,.01,100))+row('Initial speed',num('part-speed',3,0,1000))+row('Spread',num('part-spread',.7,0,2))+row('Radius',num('part-radius',.04,.001,10,.01))+row('Gravity Y',num('part-gravity',-9.81,-100,100))+row('Seed',num('part-seed',1,0,2147483647,1))+'<p class="production-note">Fixed-step ballistic particles collide with a local Y=0 floor. Each particle is actual octahedral geometry, not a screen-space sprite. Lifetime and rate bound the population.</p>',()=>app.mutate('Create particle emitter',()=>{const o=newObject('mesh',{},'Particle emitter');o.mesh=emptyMesh();o.position=[0,0,0];o.procedural={kind:'particles',rate:value('part-rate'),lifetime:value('part-life'),speed:value('part-speed'),spread:value('part-spread'),radius:value('part-radius'),gravity:[0,value('part-gravity'),0],seed:value('part-seed')};app.doc.objects.push(o);app.selected=new Set([o.id]);}),'Create emitter',550);
}
function bitmapDialog(app) {
    const {material,index}=currentMaterial(app);
    app.dialog('Bitmap texture',row('Image',select('bitmap-layer',[[-1,'No bitmap'],...(app.doc.textures||[]).map((t,i)=>[i,`${t.name||'Image '+i} · ${t.width} × ${t.height}`])],material.bitmap??-1))+row('GPU layer size',select('bitmap-resolution',[128,256,512,1024,2048],app.doc.settings.textureResolution||256))+button('bitmap-load','Import PNG / JPEG / WebP…')+'<p class="production-note">Source RGBA pixels are retained in the scene. Color is decoded from sRGB for shading. GPU layers are resampled to the selected square resolution with linear-light mipmaps; UV sampling repeats.</p>',()=>app.mutate('Assign bitmap',()=>{const i=Number($('#bitmap-layer').value);if(i<0)delete app.doc.materials[index].bitmap;else app.doc.materials[index].bitmap=i;app.doc.settings.textureResolution=Number($('#bitmap-resolution').value);}),'Apply texture',550);
    $('#bitmap-load').onclick=()=>app.safe(async()=>{const [file]=await inputFiles('image/png,image/jpeg,image/webp');if(!file)return;const texture=await decodeBitmap(file);texture.name=file.name;app.mutate('Import bitmap',()=>{app.doc.textures||=[];app.doc.textures.push(texture);app.doc.materials[index].bitmap=app.doc.textures.length-1;});bitmapDialog(app);});
}
const graphInputs={constant:[],uv:[],position:[],add:['a','b'],subtract:['a','b'],multiply:['a','b'],divide:['a','b'],mix:['a','b','factor'],clamp:['value'],checker:['uv','a','b'],noise:['vector'],image:['uv'],ramp:['value','a','b'],sine:['value'],channel:['value'],power:['a','b']};
function graphDialog(app) {
    const {material,index}=currentMaterial(app);let graph=structuredClone(material.graph||checkerGraph()),next=0;
    app.dialog('Material node graph',`<div class="production-actions">${select('node-type',Object.keys(NODE_TYPES),'constant')}${button('node-add','Add node')}${button('node-check','Validate')}${button('node-preset','Checker preset')}${button('node-clear','Disable graph')}</div><div class="node-workspace"><div class="node-stage"><svg class="node-wires"></svg><div id="node-cards"></div></div></div><h3>Surface outputs</h3><div id="node-outputs" class="production-grid"></div><p id="graph-status" class="production-note">Drag node headers to arrange the graph. Select input connections on each card. Up to 63 nodes; cycles and missing inputs are rejected on Apply.</p>`,()=>{if(graph){compileGraph(graph);app.mutate('Apply material graph',()=>app.doc.materials[index].graph=graph);}else app.mutate('Disable material graph',()=>delete app.doc.materials[index].graph);},'Apply graph',1040);
    const nodeOptions=(current,exclude=null,optional=false)=>`${optional?'<option value="">Use material setting</option>':'<option value="">Connect…</option>'}`+(graph?.nodes||[]).filter(n=>n.id!==exclude).map(n=>`<option value="${esc(n.id)}" ${n.id===current?'selected':''}>${esc(n.id)} · ${esc(n.type)}</option>`).join('');
    function render(){if(!graph){$('#node-cards').innerHTML='';$('#node-outputs').innerHTML='Graph disabled. Apply to use the standard material controls.';drawWires();return;}
        $('#node-cards').innerHTML=graph.nodes.map((n,i)=>{n.ui||={x:25+(i%3)*270,y:25+Math.floor(i/3)*250};return `<section class="shade-node" data-node="${esc(n.id)}" style="left:${n.ui.x}px;top:${n.ui.y}px"><h4>${esc(n.id)} · ${esc(n.type)}</h4><button data-remove="${esc(n.id)}" aria-label="Remove node">×</button>${graphInputs[n.type].map(input=>row(input,`<select data-input="${input}">${nodeOptions(n.inputs?.[input],n.id)}</select>`)).join('')}${['constant','clamp'].includes(n.type)?row('Value',`<input data-prop="value" value="${esc(Array.isArray(n.value)?n.value.join(','):n.value??0)}">`):''}${['checker','noise'].includes(n.type)?row('Scale',`<input data-prop="scale" type="number" step=".1" value="${n.scale??1}">`):''}${n.type==='image'?row('Image',`<select data-prop="texture">${(app.doc.textures||[]).map((t,i)=>`<option value="${i}" ${i===n.texture?'selected':''}>${esc(t.name||'Image '+i)}</option>`).join('')}</select>`):''}${n.type==='channel'?row('Channel',`<select data-prop="channel">${[0,1,2,3].map(i=>`<option ${i===(n.channel||0)?'selected':''}>${i}</option>`).join('')}</select>`):''}</section>`;}).join('');
        $('#node-outputs').innerHTML=['baseColor','roughness','metallic','emission','transmission','ior','subsurface','density'].map(key=>row(key,`<select data-output="${key}">${nodeOptions(graph.outputs[key],null,key!=='baseColor')}</select>`)).join('');
        document.querySelectorAll('.shade-node').forEach(card=>{const n=graph.nodes.find(n=>n.id===card.dataset.node);card.querySelectorAll('[data-input]').forEach(e=>e.onchange=()=>{n.inputs||={};n.inputs[e.dataset.input]=e.value;drawWires();});card.querySelectorAll('[data-prop]').forEach(e=>e.onchange=()=>app.safe(()=>{const key=e.dataset.prop;n[key]=key==='value'?(e.value.includes(',')?e.value.split(',').map(Number):Number(e.value)):Number(e.value);}));card.querySelector('[data-remove]').onclick=()=>{graph.nodes=graph.nodes.filter(x=>x!==n);render();};const header=card.querySelector('h4');header.onpointerdown=e=>{const x=e.clientX,y=e.clientY,start={...n.ui};header.setPointerCapture(e.pointerId);header.onpointermove=p=>{n.ui.x=Math.max(0,start.x+p.clientX-x);n.ui.y=Math.max(0,start.y+p.clientY-y);card.style.left=n.ui.x+'px';card.style.top=n.ui.y+'px';drawWires();};header.onpointerup=()=>header.onpointermove=null;};});
        document.querySelectorAll('[data-output]').forEach(e=>e.onchange=()=>{if(e.value)graph.outputs[e.dataset.output]=e.value;else delete graph.outputs[e.dataset.output];drawWires();});drawWires();
    }
    function drawWires(){const stage=$('.node-stage'),svg=$('.node-wires');if(!stage||!svg)return;const height=Math.max(900,...(graph?.nodes||[]).map(n=>(n.ui?.y||0)+270));stage.style.minHeight=height+'px';svg.setAttribute('height',height);svg.innerHTML=(graph?.nodes||[]).flatMap(n=>Object.values(n.inputs||{}).map(id=>{const from=graph.nodes.find(x=>x.id===id);if(!from?.ui||!n.ui)return '';const x=from.ui.x+206,y=from.ui.y+30,tx=n.ui.x,ty=n.ui.y+55;return `<path d="M${x},${y} C${x+60},${y} ${tx-60},${ty} ${tx},${ty}" fill="none" stroke="#78bce8" stroke-width="2"/>`;})).join('');}
    $('#node-add').onclick=()=>app.safe(()=>{graph||={nodes:[],outputs:{}};if(graph.nodes.length>=63)throw Error('Node limit reached');const type=$('#node-type').value;let id;do{id=`${type}${++next}`;}while(graph.nodes.some(n=>n.id===id));const n={id,type,inputs:{},value:type==='clamp'?[0,1,0,0]:.5,scale:4,texture:0,channel:0};for(const input of graphInputs[type])n.inputs[input]=graph.nodes.find(x=>x.type===(['uv'].includes(input)?'uv':'constant'))?.id||graph.nodes[0]?.id||'';graph.nodes.push(n);render();});
    $('#node-check').onclick=()=>app.safe(()=>$('#graph-status').textContent=`Validated ${compileGraph(graph).nodeCount-1} shader nodes.`);
    $('#node-preset').onclick=()=>{graph=checkerGraph();render();};$('#node-clear').onclick=()=>{graph=null;render();};render();
}
function mediumDialog(app) {
    const {material,index}=currentMaterial(app),v=app.doc.volume||{};
    app.dialog('Volume and subsurface transport',`<h3>Selected material: ${esc(material.name)}</h3>${row('Subsurface weight',num('sss-weight',material.subsurface?.weight||0,0,1,.05))}${row('Interior extinction / metre',num('sss-density',material.subsurface?.density||4,.001,10000,.1))}${row('Scattering anisotropy',num('sss-g',material.subsurface?.anisotropy||0,-.95,.95,.05))}<p class="production-note">Closed surfaces use an interior random walk with the material color as scattering albedo. Nested closed solids use an interior-medium stack. Use Volume regions for dense or sparse overlapping grid fields; the homogeneous box below remains compatible with existing scenes.</p><h3>Homogeneous box volume</h3>${row('Enabled',check('volume-enabled',v.density>0))}${row('Minimum',vector('vol-min',v.min||[-3,0,-3]))}${row('Maximum',vector('vol-max',v.max||[3,4,3]))}${row('Extinction / metre',num('vol-density',v.density??.15,0,1000,.01))}${row('Scattering albedo RGB',vector('vol-color',v.color||[.9,.9,.95]))}${row('Phase anisotropy',num('vol-g',v.anisotropy||0,-.95,.95,.05))}<p class="production-note">Exponential free-flight sampling, Henyey–Greenstein scattering and shadow transmittance are evaluated inside the box. Path tracing and volume photon density estimation both transport these media. This dialog selects path tracing; increase maximum path depth for multiple scattering.</p>`,()=>app.mutate('Edit participating media',()=>{const min=readVector('vol-min'),max=readVector('vol-max'),color=readVector('vol-color');if(min.some((v,i)=>v>=max[i])||color.some(v=>v<0||v>1))throw Error('Volume bounds or albedo are invalid');Object.assign(app.doc.materials[index],{subsurface:{weight:value('sss-weight'),density:value('sss-density'),anisotropy:value('sss-g')}});app.doc.volume={min,max,color,density:$('#volume-enabled').checked?value('vol-density'):0,anisotropy:value('vol-g')};app.doc.settings.integrator='path';app.doc.settings.bounces=Math.max(16,app.doc.settings.bounces);}),'Apply media',640);
}
function renderSettings(app) {
    const s=app.doc.settings;
    app.dialog('Production render settings',row('Integrator',select('prod-integrator',[['path','Path tracing'],['photon','Photon density estimation'],['finalGather','Photon map + final gathering']],s.integrator||'path'))+row('Emitted photon paths',num('prod-photons',s.photonCount||8192,1,131072,1))+row('Photon search radius',num('prod-radius',s.photonRadius||.2,.001,100,.01))+row('Denoise display',check('prod-denoise',s.denoise||false))+row('À-trous passes',num('prod-iterations',s.denoiseIterations||4,1,5,1))+row('View',select('prod-view',['beauty','albedo','normals','depth','objects','emission','direct','indirect'],s.view||'beauty'))+row('Shutter open · frames',num('prod-open',s.shutter?.[0]??-.25,-10,10,.05))+row('Shutter close · frames',num('prod-close',s.shutter?.[1]??.25,-10,10,.05))+row('Random seed',num('prod-seed',s.seed||1,0,2147483647,1))+'<p class="production-note">Photon modes are biased surface and volume density estimators. Final gathering traces an additional scattering bounce before querying the map. Denoising is a spatial edge-aware filter; raw HDR/AOV buffers remain untouched. Shutter integration runs from Render frame, not interactive playback.</p>',()=>app.mutate('Production render settings',()=>{const open=value('prod-open'),close=value('prod-close');if(close<open)throw Error('Shutter close must follow open');Object.assign(s,{integrator:$('#prod-integrator').value,photonCount:value('prod-photons'),photonRadius:value('prod-radius'),denoise:$('#prod-denoise').checked,denoiseIterations:value('prod-iterations'),view:$('#prod-view').value,shutter:[open,close],seed:value('prod-seed')});}),'Apply',620);
}
async function exportEXR(app,denoised=false) {
    if(!app.gpuReady||!app.renderer.samples)throw Error('Render samples before exporting an EXR.');
    const hdr=await app.renderer.readHDR({denoised}),aovs=await app.renderer.readAOVs();download(encodeEXR({width:hdr.width,height:hdr.height,channels:renderChannels(hdr,aovs),metadata:{scene:app.doc.name,frame:app.doc.animation.frame,samples:app.renderer.samples,beauty:denoised?'spatially denoised':'raw'}}),app.filename()+(denoised?'-denoised':'')+'.exr','image/x-exr');
}
function frameDialog(app) {
    if(!app.gpuReady)throw Error('Production rendering requires WebGPU.');
    app.dialog('Render current frame',row('Width',num('frame-width',640,16,8192,1))+row('Height',num('frame-height',480,16,8192,1))+row('Samples',num('frame-samples',app.doc.settings.samples,1,8192,1))+row('Motion blur',check('frame-blur',true))+`<div class="production-actions">${button('frame-start','Start render')}${button('frame-stop','Cancel')}${button('frame-exr','Save raw EXR + AOVs')}${button('frame-filtered','Save denoised EXR')}</div><progress class="production-progress" id="frame-progress" value="0" max="1"></progress><p id="frame-status">Motion blur evaluates actual transforms, skinning, camera keys and geometry at stratified shutter times.</p>`,null,'Close',650);
    let controller=null;
    $('#frame-start').onclick=()=>app.safe(async()=>{if(app.renderLocked)throw Error('A render is already active.');const width=value('frame-width'),height=value('frame-height'),samples=value('frame-samples'),source=structuredClone(app.doc),shutter=$('#frame-blur').checked?(source.settings.shutter||[-.25,.25]):[0,0];controller=new AbortController();app.renderLocked=true;app.playing=false;$('#frame-start').disabled=true;try{while(app.building||app.renderer.busy)await new Promise(r=>setTimeout(r,10));clearTimeout(app.buildTimer);app.needsBuild=false;await renderProduction(app.renderer,source,{width,height,samples,shutter,signal:controller.signal,onProgress:p=>{if($('#frame-progress')){$('#frame-progress').value=p.sample/p.samples;$('#frame-status').textContent=`${p.sample} / ${p.samples} samples · shutter time ${p.time.toFixed(4)} · ${p.width} × ${p.height}`;}}});app.renderer.paused=true;app.dirty=false;app.toast('Frame rendered. Raw EXR and all AOVs are ready.');}catch(error){app.renderer.fixedSize=null;app.renderer.tile=null;app.renderer.sampleStart=0;app.renderer.mode='raster';app.renderer.paused=false;app.requestBuild();app.dirty=true;throw error;}finally{app.renderLocked=false;if($('#frame-start'))$('#frame-start').disabled=false;}});
    $('#frame-stop').onclick=()=>controller?.abort();$('#frame-exr').onclick=()=>app.safe(()=>exportEXR(app));$('#frame-filtered').onclick=()=>app.safe(()=>exportEXR(app,true));
    $('#dialog').addEventListener('close',()=>controller?.abort(),{once:true});
}
function interchangeDialog(app) {
    app.dialog('Production interchange',`<div class="production-grid"><div class="production-card"><h3>Import</h3><p>glTF / GLB with skinning, morph targets, keyframed animation, PBR materials and base-color images. Select companion .bin and image files together for external resources.</p>${button('gltf-open','Choose glTF / GLB and resources…')}</div><div class="production-card"><h3>Export</h3><p>GLB embeds geometry, supported materials, images, skins, morphs and animation. PLY and USDA are evaluated static mesh snapshots.</p><div class="production-actions">${button('gltf-export','glTF 2.0')}${button('glb-export','Binary GLB')}${button('ply-export','ASCII PLY')}${button('usd-export','USDA snapshot')}</div></div></div><p class="production-note">Native Aureon scene files retain the editable scene state. Unsupported required glTF extensions are rejected; optional fields outside the importer’s support are reported. FBX, Alembic and full USD composition are not implemented.</p>`,null,'Close',800);
    $('#gltf-open').onclick=()=>app.safe(async()=>{const files=await inputFiles('.gltf,.glb,.bin,.png,.jpg,.jpeg,.webp',true);if(!files.length)return;const main=files.find(f=>/\.(gltf|glb)$/i.test(f.name));if(!main)throw Error('Choose a glTF or GLB file.');await openGLTF(app,main,files);$('#dialog').close();});
    $('#gltf-export').onclick=()=>app.safe(()=>download(JSON.stringify(exportGLTF2(app.doc,app.geometry)),app.filename()+'.gltf','model/gltf+json'));
    $('#glb-export').onclick=()=>app.safe(()=>download(exportGLTF2(app.doc,app.geometry,{binary:true}),app.filename()+'.glb','model/gltf-binary'));
    $('#ply-export').onclick=()=>app.safe(()=>download(exportPLY(app.doc,app.geometry),app.filename()+'.ply','text/plain'));
    $('#usd-export').onclick=()=>app.safe(()=>download(exportUSDA(app.doc,app.geometry),app.filename()+'.usda','text/plain'));
}
async function openGLTF(app,file,files=[file]) {
    const resources=new Map(files.map(f=>[f.name,f]));const result=await importGLTF(/\.glb$/i.test(file.name)?new Uint8Array(await file.arrayBuffer()):await file.text(),{resolveResource:async uri=>{const name=decodeURIComponent(uri).split('/').at(-1),resource=resources.get(name);if(!resource)throw Error(`Missing companion file: ${name}. Use File → Production interchange to select all resources.`);return new Uint8Array(await resource.arrayBuffer());}});
    const doc=validateDocument(result.document||result.doc||result);app.mutate('Import glTF scene',()=>{app.doc=doc;app.geometry.clear();app.selected=new Set(doc.objects.filter(o=>o.mesh?.faces.length).slice(0,1).map(o=>o.id));});if(result.interchangeWarnings?.length)app.toast(result.interchangeWarnings.join(' · '));
}
function distributedDialog(app) {
    app.dialog('Distributed WebGPU rendering',row('Coordinator',`<input id="dist-url" value="http://127.0.0.1:4183">`)+row('Bearer token',`<input id="dist-token" type="password" autocomplete="off" placeholder="Printed by npm run render:server">`)+row('Width',num('dist-width',640,16,8192,1))+row('Height',num('dist-height',480,16,8192,1))+row('Samples',num('dist-samples',64,1,8192,1))+row('Tile edge',num('dist-tile',64,8,256,1))+row('Batch samples',num('dist-batch',8,1,1024,1))+`<div class="production-actions">${button('dist-submit','Submit scene')}${button('dist-refresh','Refresh jobs')}${button('dist-worker','Open worker')}${button('dist-exr','Download selected job EXR')}${button('dist-cancel','Cancel job')}</div><select id="dist-jobs" style="width:100%"></select><pre id="dist-log" class="production-log"></pre><p class="production-note">Run the included coordinator with <code>npm run render:server</code>. Open its worker page in each participating WebGPU browser and enter the token there. Remote machines require a trusted HTTPS deployment, explicit allowed origins and network access. No external cloud service is provisioned. Tokens stay in memory.</p>`,null,'Close',750);
    const log=message=>{$('#dist-log').textContent=message;};
    const url=()=>{const u=new URL($('#dist-url').value);if(!['http:','https:'].includes(u.protocol))throw Error('Coordinator must use HTTP or HTTPS');return u.href.replace(/\/$/,'');};
    async function request(path,method='GET',body=null){const r=await fetch(url()+path,{method,headers:{Authorization:'Bearer '+$('#dist-token').value,...(body?{'Content-Type':'application/json'}:{})},body:body?JSON.stringify(body):undefined});if(!r.ok)throw Error(await r.text());return r;}
    async function refresh(){const response=await (await request('/api/jobs')).json(),jobs=Array.isArray(response)?response:response.jobs;const prior=$('#dist-jobs').value;$('#dist-jobs').innerHTML=jobs.map(j=>`<option value="${j.id}" ${j.id===prior?'selected':''}>${esc(j.name)} · ${j.status} · ${j.completed}/${j.total} tasks · ${j.id.slice(0,8)}</option>`).join('');log(JSON.stringify(jobs,null,2));}
    $('#dist-submit').onclick=()=>app.safe(async()=>{const result=await (await request('/api/jobs','POST',{scene:app.doc,width:value('dist-width'),height:value('dist-height'),samples:value('dist-samples'),tileSize:value('dist-tile'),batchSize:value('dist-batch')})).json();await refresh();$('#dist-jobs').value=result.id;log(`Submitted ${result.id}`);});
    $('#dist-refresh').onclick=()=>app.safe(refresh);$('#dist-worker').onclick=()=>app.safe(()=>window.open(url()+'/','_blank','noopener'));
    $('#dist-exr').onclick=()=>app.safe(async()=>{const id=$('#dist-jobs').value;if(!id)throw Error('Select a job');download(await (await request(`/api/jobs/${id}/image.exr`)).blob(),`aureon-${id}.exr`);});
    $('#dist-cancel').onclick=()=>app.safe(async()=>{const id=$('#dist-jobs').value;if(!id)throw Error('Select a job');await request(`/api/jobs/${id}`,'DELETE');await refresh();});
}
function bakeDialog(app) {
    const o=app.requireObject();app.dialog('Bake evaluated deformation',row('First frame',num('bake-first',app.doc.animation.start,0,10000,1))+row('Last frame',num('bake-last',Math.min(app.doc.animation.end,60),0,10000,1))+'<p>Samples the evaluated object into a native per-frame position cache. Topology must remain constant. The cache replaces its procedural/deformation stack; rigid object animation channels remain separate. Budget: 32 million position scalars.</p>',async()=>{const first=value('bake-first'),last=value('bake-last');if(last<first)throw Error('Invalid bake interval');const doc=structuredClone(app.doc),cache=new GeometryCache(),target=doc.objects.find(x=>x.id===o.id),positions={},base=cloneMesh(cache.setContext(doc,first).get(target));if((last-first+1)*base.positions.length>32000000)throw Error('Bake exceeds the 32-million-scalar budget');for(let frame=first;frame<=last;frame++){doc.animation.frame=frame;const m=cache.setContext(doc,frame).get(target);if(m.positions.length!==base.positions.length||JSON.stringify(m.faces)!==JSON.stringify(base.faces))throw Error('Changing topology cannot be saved as a position cache');positions[frame]=[...m.positions];if(frame%5===0)await new Promise(r=>setTimeout(r,0));}app.mutate('Bake deformation cache',()=>{bindMesh(o,base);o.meshCache={frames:Object.entries(positions).map(([frame,positions])=>({frame:Number(frame),positions}))};});},'Bake',560);
}
export function installProductionTools(app) {
    installStyle();
    const commands={
        boolean:['Solid boolean…','mesh',()=>booleanDialog(app)],
        bevel:['Convex bevel…','mesh',()=>{const o=app.requireObject();app.dialog('Convex solid bevel',row('Offset width',num('bevel-width',.05,.0001,100,.01))+'<p>Single-segment planar chamfer for closed convex solids. Concave input and widths that collapse a face are rejected; this is not a general curved bevel.</p>',()=>app.mutate('Add bevel',()=>o.modifiers.push({type:'bevel',enabled:true,value:value('bevel-width')})));}],
        rig:['Skeleton / skin / IK…','curve',()=>rigDialog(app)],
        cloth:['Attach cloth simulation…','mesh',()=>simulationDialog(app,'cloth')],
        rigid:['Attach rigid simulation…','mesh',()=>simulationDialog(app,'rigid')],
        hair:['Create surface hair…','curve',()=>hairDialog(app)],
        particles:['Create particle emitter…','plus',()=>particleDialog(app)],
        bakeCache:['Bake deformation cache…','curve',()=>bakeDialog(app)],
        bitmap:['Bitmap textures…','folder',()=>bitmapDialog(app)],
        shaderGraph:['Material node graph…','stack',()=>graphDialog(app)],
        media:['Volumes / subsurface…','sphere',()=>mediumDialog(app)],
        subsurface:['Subsurface / box medium…','sphere',()=>mediumDialog(app)],
        productionSettings:['Production render settings…','render',()=>renderSettings(app)],
        productionRender:['Render frame / motion blur…','render',()=>frameDialog(app)],
        exportEXR:['Export EXR + AOVs','download',()=>exportEXR(app)],
        distributed:['Distributed rendering…','render',()=>distributedDialog(app)],
        interchange:['Production interchange…','folder',()=>interchangeDialog(app)],
        resumeInteractive:['Resume interactive viewport','camera',()=>{app.renderer.fixedSize=null;app.renderer.tile=null;app.renderer.sampleStart=0;app.renderer.paused=false;app.renderer.mode='raster';app.requestBuild();app.dirty=true;}],
    };
    for(const [id,[label,icon,fn]] of Object.entries(commands))app.commands[id]={label,icon,fn};
    app.extraMenus={File:['interchange','exportEXR'],Model:['boolean','bevel'],Create:['hair','particles'],Animation:['rig','cloth','rigid','bakeCache'],Render:['bitmap','shaderGraph','media','subsurface','productionSettings','productionRender','exportEXR','distributed','resumeInteractive']};
    app.readProductionFile=async file=>{if(/\.(glb|gltf)$/i.test(file.name)){await openGLTF(app,file);return true;}if(/\.ply$/i.test(file.name)){const mesh=parsePLY(await file.text());app.mutate('Import PLY',()=>{const o=newObject('mesh',{},file.name);o.mesh=mesh;app.doc.objects.push(o);app.selected=new Set([o.id]);});return true;}return false;};
}
