/** Coordinator state machine: authenticated transport is handled by server.mjs.
 * Leases, heartbeats, stale-result rejection, idempotence and Kahan accumulation.
 */
import {randomUUID,createHash} from 'node:crypto';
import {validateDocument} from '../scene/document.js';
export class RenderQueue {
 constructor({leaseMs=90000,maxMemory=512*1024*1024,now=()=>Date.now()}={}){Object.assign(this,{leaseMs,maxMemory,now});this.jobs=new Map();this.memory=0;}
 create({scene,width=640,height=480,samples=64,tileSize=64,batchSize=8}={}){validateDocument(scene);if([width,height,samples,tileSize,batchSize].some(v=>!Number.isInteger(v)||v<1)||width>8192||height>8192||samples>8192||tileSize>256||batchSize>1024)throw Error('Invalid render job limits');const bytes=width*height*(24*16+4);if(this.memory+bytes>this.maxMemory)throw Error('Render jobs exceed coordinator memory budget');if(Math.ceil(width/tileSize)*Math.ceil(height/tileSize)*Math.ceil(samples/batchSize)>1000000)throw Error('Job exceeds one million tasks');const sceneJSON=JSON.stringify(scene);if(sceneJSON.length>32*1024*1024)throw Error('Scene exceeds 32 MiB coordinator limit');const id=randomUUID(),tasks=[];for(let sampleStart=0;sampleStart<samples;sampleStart+=batchSize)for(let y=0;y<height;y+=tileSize)for(let x=0;x<width;x+=tileSize)tasks.push({id:tasks.length,x,y,width:Math.min(tileSize,width-x),height:Math.min(tileSize,height-y),fullWidth:width,fullHeight:height,sampleStart,samples:Math.min(batchSize,samples-sampleStart),totalSamples:samples,status:'pending',attempts:0});if(tasks.length>1000000)throw Error('Job exceeds one million tasks');const job={id,scene:JSON.parse(sceneJSON),hash:createHash('sha256').update(sceneJSON).digest('hex'),width,height,samples,tasks,sums:new Float64Array(width*height*24),correction:new Float64Array(width*height*24),weights:new Uint32Array(width*height),created:this.now(),status:'queued',bytes,completed:0};this.memory+=bytes;this.jobs.set(id,job);return this.describe(job);}
 describe(job){if(typeof job==='string')job=this.jobs.get(job);if(!job)throw Error('Unknown render job');return {id:job.id,name:job.scene.name,hash:job.hash,width:job.width,height:job.height,samples:job.samples,status:job.status,completed:job.completed,total:job.tasks.length,progress:job.completed/job.tasks.length,created:job.created,leased:job.tasks.filter(t=>t.status==='leased').length};}
 claim(worker){if(typeof worker!=='string'||!worker.length||worker.length>128)throw Error('Invalid worker ID');for(const job of this.jobs.values()){if(!['queued','running'].includes(job.status))continue;for(const task of job.tasks){if(task.status==='leased'&&task.deadline<=this.now()){task.status='pending';task.lease=null;}if(task.status!=='pending')continue;task.status='leased';task.worker=worker;task.lease=randomUUID();task.deadline=this.now()+this.leaseMs;task.attempts++;job.status='running';return {jobId:job.id,hash:job.hash,scene:job.scene,task:{...task},leaseMs:this.leaseMs};}}return null;}
 heartbeat(jobId,taskId,lease){const {task}=this.checkLease(jobId,taskId,lease);task.deadline=this.now()+this.leaseMs;return {deadline:task.deadline};}
 checkLease(jobId,taskId,lease){const job=this.jobs.get(jobId),task=job?.tasks[taskId];if(!job||!task||job.status==='cancelled')throw Error('Unknown or cancelled task');if(task.status==='done'&&task.lease===lease)return {job,task,duplicate:true};if(task.status!=='leased'||task.lease!==lease||task.deadline<=this.now())throw Error('Expired or invalid task lease');return {job,task,duplicate:false};}
 complete(jobId,taskId,lease,data){const {job,task,duplicate}=this.checkLease(jobId,taskId,lease);if(duplicate)return {duplicate:true,...this.describe(job)};if(!(data instanceof Float32Array)||data.length!==task.width*task.height*24||data.some(v=>!Number.isFinite(v)))throw Error('Invalid or nonfinite tile result');for(let y=0;y<task.height;y++)for(let x=0;x<task.width;x++){const src=(y*task.width+x)*24,pixel=(task.y+y)*job.width+task.x+x;for(let c=0;c<24;c++){const dst=pixel*24+c;if(c===15){job.sums[dst]=data[src+c];continue;}const value=data[src+c]*task.samples-job.correction[dst],sum=job.sums[dst]+value;job.correction[dst]=(sum-job.sums[dst])-value;job.sums[dst]=sum;}job.weights[pixel]+=task.samples;}task.status='done';job.completed++;if(job.completed===job.tasks.length)job.status='completed';return {duplicate:false,...this.describe(job)};}
 image(id){const job=this.jobs.get(id);if(!job)throw Error('Unknown job');const hdr=new Float32Array(job.width*job.height*4),aovs=new Float32Array(job.width*job.height*20);for(let i=0;i<job.weights.length;i++)for(let c=0;c<24;c++){const v=c===15?job.sums[i*24+c]:job.sums[i*24+c]/Math.max(1,job.weights[i]);if(c<4)hdr[i*4+c]=v;else aovs[i*20+c-4]=v;}return {hdr:{width:job.width,height:job.height,data:hdr},aovs:{width:job.width,height:job.height,data:aovs}};}
 cancel(id){const j=this.jobs.get(id);if(!j)throw Error('Unknown job');j.status='cancelled';return this.describe(j);}
 remove(id){const j=this.jobs.get(id);if(j){this.memory-=j.bytes;this.jobs.delete(id);}return !!j;}
}
