/** Four-order cylindrical fiber scattering. Longitudinal spherical-Gaussian
 * marginal and normalized, wrapped azimuthal logistic lobes; R, TT, TRT and
 * the summed higher internal-reflection tail. Distances are fiber diameters.
 * Model equations and assumptions: docs/FIBER.md (not a surface GGX shader).
 */
const PI=Math.PI,clamp=(x,a,b)=>Math.max(a,Math.min(b,x)),wrap=x=>((x+PI)%(2*PI)+2*PI)%(2*PI)-PI;
export function validateFiber(f){if(!f||!['roughness','azimuthalRoughness','ior','tilt'].every(k=>f[k]===undefined||Number.isFinite(f[k])))throw Error('Invalid fiber parameters');if((f.roughness??.3)<.03||(f.roughness??.3)>1||(f.azimuthalRoughness??.3)<.03||(f.azimuthalRoughness??.3)>1||(f.ior??1.55)<1.01||(f.ior??1.55)>3||Math.abs(f.tilt??2)>15)throw Error('Fiber parameters outside supported bounds');const a=f.absorption??[.5,1,2];if(a.length!==3||a.some(x=>!Number.isFinite(x)||x<0||x>1000))throw Error('Invalid fiber absorption');return f;}
function fresnel(c,eta){const s2=(1-c*c)/(eta*eta);if(s2>=1)return 1;const t=Math.sqrt(1-s2),a=(eta*c-t)/(eta*c+t),b=(c-eta*t)/(c+eta*t);return (a*a+b*b)/2;}
// log(I0) from a convergent power series below 12 and its asymptotic series above.
export function logBesselI0(x){x=Math.abs(x);if(x<12){let term=1,sum=1;for(let k=1;k<32;k++){term*=x*x/(4*k*k);sum+=term;if(term<sum*1e-16)break;}return Math.log(sum);}const r=1/x;return x-.5*Math.log(2*PI*x)+Math.log(1+r/8+9*r*r/128+225*r*r*r/3072+11025*r**4/98304);}
export function longitudinal(si,so,v){const ci=Math.sqrt(Math.max(0,1-si*si)),co=Math.sqrt(Math.max(0,1-so*so)),x=1/v;return Math.exp(logBesselI0(ci*co*x)-si*so*x-x)/(v*(-Math.expm1(-2*x)));}
const cdf=(x,s)=>1/(1+Math.exp(-x/s));
export function fiberLobes(f,so,h=0){validateFiber(f);so=clamp(so,-.999999,.999999);h=clamp(h,-.99999,.99999);const eta=f.ior??1.55,co=Math.sqrt(1-so*so),st=so/eta,ct=Math.sqrt(1-st*st),etaP=Math.sqrt(eta*eta-so*so)/co,gt=Math.asin(h/etaP),go=Math.asin(h),F=fresnel(co*Math.sqrt(1-h*h),eta),T=(f.absorption??[.5,1,2]).map(a=>Math.exp(-a*2*Math.cos(gt)/ct)),A=[T.map(()=>F),T.map(t=>(1-F)**2*t),T.map(t=>(1-F)**2*t*t*F),T.map(t=>(1-F)**2*t*t*t*F*F/Math.max(1e-12,1-F*t))],rough=f.roughness??.3,bn=f.azimuthalRoughness??rough,v=(.726*rough+.812*rough*rough+3.7*rough**20)**2,variance=[v,v*.25,v*4,v*4],s=Math.sqrt(PI/8)*(.265*bn+1.194*bn*bn+5.372*bn**22),alpha=(f.tilt??2)*PI/180,theta=Math.asin(so),angles=[theta-2*alpha,theta+alpha,theta+4*alpha,theta+4*alpha],weights=A.map(a=>a.reduce((x,y)=>x+y,0)/3),sum=weights.reduce((x,y)=>x+y,0);return {A,variance,s,so:angles.map(a=>clamp(Math.sin(a),-.999999,.999999)),phi:[-2*go,2*gt-2*go+PI,4*gt-2*go+2*PI,0],weights:weights.map(x=>x/sum)};}
export function evaluateFiber(f,wo,wi,h=0){const L=fiberLobes(f,wo[0],h),si=clamp(wi[0],-1,1),phi=Math.atan2(wi[2],wi[1])-Math.atan2(wo[2],wo[1]);let pdf=0,value=[0,0,0];for(let p=0;p<4;p++){const x=wrap(phi-L.phi[p]),q=cdf(x,L.s),az=p===3?1/(2*PI):q*(1-q)/(L.s*(cdf(PI,L.s)-cdf(-PI,L.s))),density=longitudinal(si,L.so[p],L.variance[p])*az;pdf+=L.weights[p]*density;value=value.map((v,k)=>v+L.A[p][k]*density);}return {value,pdf};}
export function sampleFiber(f,wo,h,random){const L=fiberLobes(f,wo[0],h);let u=clamp(random(),1e-9,1-1e-9),p=0;while(p<3&&u>L.weights[p]){u-=L.weights[p++];}const v=L.variance[p],r=clamp(random(),1e-9,1-1e-9),c=1+v*Math.log(r+(1-r)*Math.exp(-2/v)),s=Math.sqrt(Math.max(0,1-c*c)),sinTheta=clamp(-c*L.so[p]+s*Math.cos(2*PI*random())*Math.sqrt(1-L.so[p]**2),-1,1),cosTheta=Math.sqrt(1-sinTheta*sinTheta),lo=cdf(-PI,L.s),hi=cdf(PI,L.s),raw=clamp(random(),1e-9,1-1e-9),a=lo+(hi-lo)*raw,phi=Math.atan2(wo[2],wo[1])+L.phi[p]+(p===3?2*PI*raw-PI:L.s*Math.log(a/(1-a))),wi=[sinTheta,cosTheta*Math.cos(phi),cosTheta*Math.sin(phi)];return {wi,...evaluateFiber(f,wo,wi,h)};}
