/** Validated typed-vector shading DAG compiled to a bounded WGSL bytecode ABI.
 * There is no eval, generated JavaScript, or execution of imported code. */
export const NODE_TYPES={constant:0,uv:1,position:2,add:3,subtract:4,multiply:5,divide:6,mix:7,clamp:8,checker:9,noise:10,image:11,ramp:12,sine:13,channel:14,power:15};
const INPUTS={constant:[],uv:[],position:[],add:['a','b'],subtract:['a','b'],multiply:['a','b'],divide:['a','b'],mix:['a','b','factor'],clamp:['value'],checker:['uv','a','b'],noise:['vector'],image:['uv'],ramp:['value','a','b'],sine:['value'],channel:['value'],power:['a','b']};
export function compileGraph(graph){if(!graph||!Array.isArray(graph.nodes)||graph.nodes.length>63)throw Error('A shading graph supports up to 63 nodes plus its surface output');const nodes=new Map();for(const n of graph.nodes){if(typeof n.id!=='string'||nodes.has(n.id)||!(n.type in NODE_TYPES))throw Error('Duplicate node ID or unsupported shader node');nodes.set(n.id,n);}const sorted=[],visiting=new Set(),visited=new Set();const visit=id=>{if(visited.has(id))return;if(visiting.has(id))throw Error('Shading graph contains a cycle');const n=nodes.get(id);if(!n)throw Error(`Missing shader node ${id}`);visiting.add(id);for(const input of INPUTS[n.type]){const ref=n.inputs?.[input];if(ref===undefined)throw Error(`Missing ${input} input on ${id}`);visit(ref);}visiting.delete(id);visited.add(id);sorted.push(n);};const outputs=graph.outputs||{};if(!outputs.baseColor)throw Error('Graph requires a baseColor surface output');for(const id of Object.values(outputs))visit(id);for(const id of nodes.keys())visit(id);const indices=new Map(sorted.map((n,i)=>[n.id,i])),data=new Float32Array((sorted.length+1)*16);
    sorted.forEach((n,i)=>{const off=i*16;data[off]=NODE_TYPES[n.type];const args=INPUTS[n.type].map(k=>indices.get(n.inputs[k]));data.set([...args,...new Array(4-args.length).fill(-1)],off+4);let value=n.value??[0,0,0,1];if(typeof value==='number')value=[value,value,value,value];if(!Array.isArray(value)||value.length>4||!value.every(Number.isFinite))throw Error('Invalid shader constant');data.set(value,off+8);data[off+12]=n.scale??1;data[off+13]=n.texture??0;data[off+14]=n.channel??0;if(!Number.isFinite(data[off+12])||!Number.isFinite(data[off+13])||!Number.isInteger(n.channel??0)||(n.channel??0)<0||(n.channel??0)>3)throw Error('Invalid shader node parameter');if(n.type==='image'&&(!Number.isInteger(n.texture)||n.texture<0))throw Error('Image node requires a texture index');});
    const end=sorted.length*16;data[end]=100;const names=['baseColor','roughness','metallic','emission','transmission','ior','subsurface','density'];names.forEach((name,k)=>data[end+4+k]=outputs[name]!==undefined?indices.get(outputs[name]):-1);return {data,nodeCount:sorted.length+1,order:sorted.map(n=>n.id)};}
export function compileGraphs(materials){const data=[],ranges=[];let offset=0;for(const m of materials){if(m.graph){const c=compileGraph(m.graph);ranges.push({offset,count:c.nodeCount});data.push(c.data);offset+=c.nodeCount;}else ranges.push({offset:0,count:0});}const buffer=new Float32Array(Math.max(16,offset*16));let at=0;for(const b of data){buffer.set(b,at);at+=b.length;}return {data:buffer,ranges};}
const vec=x=>typeof x==='number'?[x,x,x,x]:[...x,...new Array(Math.max(0,4-x.length)).fill(1)];
/** CPU reference for testing graph values and estimating emissive-light weights. */
export function evaluateGraph(graph,{uv=[0,0],position=[0,0,0],sampleImage=()=>[1,1,1,1]}={}){const {data,nodeCount}=compileGraph(graph),values=[],result={};for(let i=0;i<nodeCount;i++){const off=i*16,op=data[off],args=Array.from(data.slice(off+4,off+8)).map(j=>values[j]),v=Array.from(data.slice(off+8,off+12)),scale=data[off+12];let out=v;const binary=fn=>args[0].map((x,k)=>fn(x,args[1][k]));switch(op){case 1:out=[...uv,0,1];break;case 2:out=[...position,1];break;case 3:out=binary((a,b)=>a+b);break;case 4:out=binary((a,b)=>a-b);break;case 5:out=binary((a,b)=>a*b);break;case 6:out=binary((a,b)=>a/(Math.abs(b)<1e-8?1e-8:b));break;case 7:out=args[0].map((a,k)=>a+(args[1][k]-a)*args[2][0]);break;case 8:out=args[0].map(a=>Math.min(v[1],Math.max(v[0],a)));break;case 9:out=args[((Math.floor(args[0][0]*scale)+Math.floor(args[0][1]*scale))%2+2)%2===0?1:2];break;case 10:{const n=Math.sin(dot3(args[0],[12.9898,78.233,37.719])*scale)*43758.5453;out=vec(n-Math.floor(n));break;}case 11:out=sampleImage(data[off+13],args[0].slice(0,2));break;case 12:out=args[1].map((a,k)=>a+(args[2][k]-a)*Math.min(1,Math.max(0,args[0][0])));break;case 13:out=args[0].map(a=>Math.sin(a));break;case 14:out=vec(args[0][data[off+14]]);break;case 15:out=binary((a,b)=>Math.max(a,0)**b);break;case 100:['baseColor','roughness','metallic','emission','transmission','ior','subsurface','density'].forEach((k,j)=>{const at=data[off+4+j];if(at>=0)result[k]=k==='baseColor'?values[at].slice(0,3):values[at][0];});continue;default:if(op!==0)throw Error('Unknown shader opcode');}values.push(out);}return result;}
const dot3=(a,b)=>a[0]*b[0]+a[1]*b[1]+a[2]*b[2];
export function checkerGraph(){return {nodes:[{id:'uv',type:'uv'},{id:'warm',type:'constant',value:[.58,.18,.05,1]},{id:'cool',type:'constant',value:[.02,.18,.32,1]},{id:'check',type:'checker',inputs:{uv:'uv',a:'warm',b:'cool'},scale:8},{id:'rough',type:'constant',value:.26}],outputs:{baseColor:'check',roughness:'rough'}};}
