import {validateRaster,validateUDIM,sampleUDIM,compositeLayers} from './udim.js';
import {srgbToLinear,clamp} from '../core/math.js';
export function validateTexture(t){if(t?.kind==='udim')return validateUDIM(t);if(t?.kind==='layers'){compositeLayers(t);return t;}return validateRaster(t);}
export async function decodeBitmap(blob,name='Bitmap'){if(blob.size>50000000)throw Error('Texture exceeds 50 MB limit');const bitmap=await createImageBitmap(blob,{colorSpaceConversion:'default',premultiplyAlpha:'none'});try{if(bitmap.width>8192||bitmap.height>8192)throw Error('Texture exceeds 8192 pixels per dimension');const canvas=new OffscreenCanvas(bitmap.width,bitmap.height),ctx=canvas.getContext('2d',{willReadFrequently:true});ctx.drawImage(bitmap,0,0);return {name,width:bitmap.width,height:bitmap.height,colorSpace:'srgb',data:Array.from(ctx.getImageData(0,0,bitmap.width,bitmap.height).data)};}finally{bitmap.close();}}
const linearToSRGB=x=>x<=.0031308?12.92*x:1.055*Math.max(0,x)**(1/2.4)-.055;
export function sampleTexture(t,uv){if(t.kind==='layers')t=compositeLayers(t);if(t.kind==='udim')return sampleUDIM(t,uv);const x=((uv[0]%1+1)%1)*t.width-.5,y=((uv[1]%1+1)%1)*t.height-.5,ix=Math.floor(x),iy=Math.floor(y),fx=x-ix,fy=y-iy;const out=[0,0,0,0];for(let j=0;j<2;j++)for(let i=0;i<2;i++){const px=(ix+i+t.width)%t.width,py=(iy+j+t.height)%t.height,o=(py*t.width+px)*4,w=(i?fx:1-fx)*(j?fy:1-fy);for(let c=0;c<4;c++){const v=t.data[o+c]/255;out[c]+=w*(c<3&&t.colorSpace!=='linear'?srgbToLinear(v):v);}}return out;}
/** Equal-sized array layers with full CPU-generated linear-light mip chains.
 * Source bitmaps remain lossless in the document; render resolution is explicit.
 */
export function textureMipmaps(texture,size){validateTexture(texture);if(!Number.isInteger(size)||size<1||(size&(size-1)))throw Error('Texture array size must be a power of two');let width=size,height=size,current=new Float32Array(size*size*4);for(let y=0;y<size;y++)for(let x=0;x<size;x++)current.set(sampleTexture(texture,[(x+.5)/size,(y+.5)/size]),(y*size+x)*4);const levels=[];while(true){const bytes=new Uint8Array(width*height*4);for(let i=0;i<bytes.length;i++)bytes[i]=Math.round(clamp(i%4===3?current[i]:linearToSRGB(current[i]),0,1)*255);levels.push({width,height,data:bytes});if(width===1&&height===1)break;const w=Math.max(1,width>>1),h=Math.max(1,height>>1),next=new Float32Array(w*h*4);for(let y=0;y<h;y++)for(let x=0;x<w;x++)for(let c=0;c<4;c++){let sum=0;for(let dy=0;dy<2;dy++)for(let dx=0;dx<2;dx++)sum+=current[((Math.min(height-1,y*2+dy))*width+Math.min(width-1,x*2+dx))*4+c];next[(y*w+x)*4+c]=sum*.25;}current=next;width=w;height=h;}return levels;}
export class TextureArray {
    constructor(device){this.device=device;this.texture=null;this.sampler=device.createSampler({addressModeU:'repeat',addressModeV:'repeat',magFilter:'linear',minFilter:'linear',mipmapFilter:'linear'});}
    upload(textures=[],size=256){if(textures.length>this.device.limits.maxTextureArrayLayers)throw Error('Too many bitmap texture layers');const sources=textures.length?textures:[{width:1,height:1,data:[255,255,255,255]}],mips=Math.floor(Math.log2(size))+1;const texture=this.device.createTexture({label:'Bitmap array with linear-light mipmaps',size:[size,size,sources.length],format:'rgba8unorm-srgb',mipLevelCount:mips,usage:GPUTextureUsage.TEXTURE_BINDING|GPUTextureUsage.COPY_DST});try{sources.forEach((t,z)=>textureMipmaps(t,size).forEach((m,level)=>this.device.queue.writeTexture({texture,mipLevel:level,origin:[0,0,z]},m.data,{bytesPerRow:m.width*4,rowsPerImage:m.height},[m.width,m.height,1])));}catch(e){texture.destroy();throw e;}this.texture?.destroy();this.texture=texture;this.view=texture.createView({dimension:'2d-array'});}
    dispose(){this.texture?.destroy();}
}
