/** UDIM addressing and nondestructive RGBA8 painting. UVs remain unwrapped;
 * tile 1001 is (0,0), ten columns per row. Missing tiles return an explicit color.
 */
import {srgbToLinear,clamp} from '../core/math.js';
const toSRGB=x=>x<=.0031308?12.92*x:1.055*Math.max(0,x)**(1/2.4)-.055;
export function udimNumber(u,v){if(!Number.isInteger(u)||!Number.isInteger(v)||u<0||u>9||v<0||v>99)throw Error('UDIM coordinates must be in columns 0–9, rows 0–99');return 1001+u+10*v;}
export function udimCoordinates(id){if(!Number.isInteger(Number(id))||Number(id)<1001||Number(id)>2000)throw Error('Invalid UDIM tile number');const n=Number(id)-1001;return [n%10,Math.floor(n/10)];}
export function validateRaster(t){if(!t||!Number.isInteger(t.width)||!Number.isInteger(t.height)||t.width<1||t.height<1||t.width>8192||t.height>8192||t.width*t.height>16777216||t.data?.length!==t.width*t.height*4||t.data.some(v=>!Number.isInteger(v)||v<0||v>255))throw Error('Invalid RGBA8 bitmap texture');return t;}
export function validateUDIM(t){if(t.kind!=='udim'||!t.tiles||typeof t.tiles!=='object'||Array.isArray(t.tiles))throw Error('Invalid UDIM texture');const tiles=Object.entries(t.tiles);if(!tiles.length||tiles.length>256)throw Error('UDIM requires 1–256 tiles');let total=0;for(const [id,tile] of tiles){udimCoordinates(id);validateRaster(tile);total+=tile.data.length;}if(total>128*1024*1024)throw Error('UDIM source data exceeds 128 MiB');if(t.missing&&(t.missing.length!==4||t.missing.some(x=>!Number.isFinite(x)||x<0||x>1)))throw Error('Invalid missing-tile color');return t;}
function readPixel(t,x,y){const i=(clamp(y,0,t.height-1)*t.width+clamp(x,0,t.width-1))*4;return [0,1,2,3].map(c=>c<3&&t.colorSpace!=='linear'?srgbToLinear(t.data[i+c]/255):t.data[i+c]/255);}
export function sampleUDIM(t,uv){const u=Math.floor(uv[0]),v=Math.floor(uv[1]),missing=t.missing||[0,0,0,0];if(u<0||u>9||v<0||v>99)return [...missing];const source=t.tiles[1001+u+10*v];if(!source)return [...missing];const W=source.width,H=source.height,x=(uv[0]-u)*W-.5,y=(uv[1]-v)*H-.5,ix=Math.floor(x),iy=Math.floor(y),fx=x-ix,fy=y-iy,out=[0,0,0,0];for(let j=0;j<2;j++)for(let i=0;i<2;i++){const globalU=u+(ix+i+.5)/W,globalV=v+(iy+j+.5)/H,tu=Math.floor(globalU),tv=Math.floor(globalV),tile=tu>=0&&tu<10&&tv>=0&&tv<100?t.tiles[1001+tu+10*tv]:null,c=tile?readPixel(tile,Math.floor((globalU-tu)*tile.width),Math.floor((globalV-tv)*tile.height)):missing,weight=(i?fx:1-fx)*(j?fy:1-fy);for(let k=0;k<4;k++)out[k]+=c[k]*weight;}return out;}
export function createPaintTexture({name='Paint',size=256,udim=false,tile=1001,color=[0,0,0,0]}={}){if(!Number.isInteger(size)||size<1||size>4096||color.length!==4||color.some(x=>!Number.isFinite(x)||x<0||x>1))throw Error('Invalid paint surface');const data=Array.from({length:size*size*4},(_,i)=>Math.round(color[i%4]*255)),raster={name,width:size,height:size,colorSpace:'srgb',data};if(!udim)return raster;udimCoordinates(tile);return {kind:'udim',name,tiles:{[tile]:raster},missing:[0,0,0,0]};}
export function compositeLayers(texture){
    if(texture.kind!=='layers')return texture;if(!Array.isArray(texture.layers)||!texture.layers.length||texture.layers.length>64)throw Error('Invalid paint layer stack');
    const layers=texture.layers.map(l=>{if(l.texture?.kind==='layers')throw Error('Nested paint stacks are not supported');if(l.texture?.kind==='udim')validateUDIM(l.texture);else validateRaster(l.texture);if(!Number.isFinite(l.opacity??1)||(l.opacity??1)<0||(l.opacity??1)>1||!['normal','multiply','screen','add'].includes(l.blend||'normal'))throw Error('Invalid paint layer');return l;});
    const tiled=layers.some(l=>l.texture.kind==='udim'),tileIds=tiled?[...new Set(layers.flatMap(l=>l.texture.kind==='udim'?Object.keys(l.texture.tiles):['1001']))]:['1001'],result={};
    for(const id of tileIds){const sources=layers.map(l=>({...l,texture:l.texture.kind==='udim'?l.texture.tiles[id]:id==='1001'?l.texture:null})),first=sources.find(l=>l.texture)?.texture;if(!first)continue;const {width,height}=first;if(sources.some(l=>l.texture&&(l.texture.width!==width||l.texture.height!==height)))throw Error('Paint layers for a tile must share dimensions');const out={width,height,colorSpace:'srgb',data:new Array(width*height*4).fill(0)};
        for(let i=0;i<width*height;i++){let dst=[0,0,0,0];for(const l of sources){if(l.visible===false||!l.texture)continue;const src=readPixel(l.texture,i%width,Math.floor(i/width)),as=src[3]*(l.opacity??1),ad=dst[3],alpha=as+ad*(1-as),blend=(s,d)=>l.blend==='multiply'?s*d:l.blend==='screen'?1-(1-s)*(1-d):l.blend==='add'?Math.min(1,s+d):s;dst=[0,1,2].map(k=>alpha?((1-as)*ad*dst[k]+(1-ad)*as*src[k]+ad*as*blend(src[k],dst[k]))/alpha:0).concat(alpha);}for(let k=0;k<4;k++)out.data[i*4+k]=Math.round(clamp(k===3?dst[k]:toSRGB(dst[k]),0,1)*255);}
        result[id]=out;
    }return tiled?{kind:'udim',name:texture.name,tiles:result,missing:texture.missing||[0,0,0,0]}:{...result['1001'],name:texture.name};
}
/** Sparse per-pixel stroke diffs keep undo independent of image size. */
export class TexturePainter {
    constructor(texture,{maxHistoryBytes=32*1024*1024,autoCreateTiles=false,tileSize=256}={}){if(texture.kind==='udim')validateUDIM(texture);else validateRaster(texture);if(!Number.isInteger(maxHistoryBytes)||maxHistoryBytes<1024)throw Error('Invalid paint history budget');this.texture=texture;this.maxHistoryBytes=maxHistoryBytes;this.autoCreateTiles=autoCreateTiles;this.tileSize=tileSize;this.undoStack=[];this.redoStack=[];this.historyBytes=0;this.active=null;}
    begin(options={}){if(this.active)throw Error('A paint stroke is already active');const settings={radius:.035,opacity:1,hardness:.6,color:[1,0,0,1],mode:'draw',...options};if(!['draw','erase','clone','smudge'].includes(settings.mode)||![settings.radius,settings.opacity,settings.hardness].every(Number.isFinite)||settings.radius<=0||settings.radius>2||settings.opacity<0||settings.opacity>1||settings.hardness<0||settings.hardness>1||settings.color.length!==4||settings.color.some(x=>!Number.isFinite(x)||x<0||x>1))throw Error('Invalid paint brush');this.active={settings,before:new Map(),created:new Set(),last:null,source:settings.mode==='clone'||settings.mode==='smudge'?structuredClone(this.texture):null};return this;}
    tile(u,v){if(this.texture.kind!=='udim')return u===0&&v===0?this.texture:null;if(u<0||u>9||v<0||v>99)return null;const id=String(1001+u+10*v);if(!this.texture.tiles[id]&&this.autoCreateTiles){if(Object.keys(this.texture.tiles).length>=256)throw Error('UDIM tile budget exceeded');this.texture.tiles[id]=createPaintTexture({size:this.tileSize});this.active.created.add(id);}return this.texture.tiles[id]||null;}
    sample(source,uv){if(source.kind==='udim')return sampleUDIM(source,uv);return readPixel(source,Math.floor(uv[0]*source.width),Math.floor(uv[1]*source.height));}
    point(uv,pressure=1){if(!this.active)throw Error('Begin a paint stroke first');if(uv.length!==2||!uv.every(Number.isFinite)||!Number.isFinite(pressure)||pressure<0||pressure>1)throw Error('Invalid brush sample');const last=this.active.last,spacing=this.active.settings.radius*.2,distance=last?Math.hypot(uv[0]-last.uv[0],uv[1]-last.uv[1]):0,steps=Math.max(1,Math.ceil(distance/spacing));if(steps>10000)throw Error('Paint stroke interpolation budget exceeded');for(let i=1;i<=steps;i++){const t=i/steps,p=last?uv.map((x,k)=>last.uv[k]+(x-last.uv[k])*t):uv,weight=last?last.pressure+(pressure-last.pressure)*t:pressure;this.stamp(p,weight,last?uv.map((x,k)=>(x-last.uv[k])/steps):[0,0]);}this.active.last={uv:[...uv],pressure};return this;}
    stamp(uv,pressure,delta){const a=this.active,s=a.settings,r=s.radius*Math.max(.05,pressure),alpha=s.opacity*pressure;if(!alpha)return;let touched=0;
        for(let v=Math.floor(uv[1]-r);v<=Math.floor(uv[1]+r);v++)for(let u=Math.floor(uv[0]-r);u<=Math.floor(uv[0]+r);u++){const tile=this.tile(u,v);if(!tile)continue;const x0=Math.max(0,Math.floor((uv[0]-r-u)*tile.width)),x1=Math.min(tile.width-1,Math.ceil((uv[0]+r-u)*tile.width)),y0=Math.max(0,Math.floor((uv[1]-r-v)*tile.height)),y1=Math.min(tile.height-1,Math.ceil((uv[1]+r-v)*tile.height)),id=this.texture.kind==='udim'?String(1001+u+10*v):'0';
            for(let y=y0;y<=y1;y++)for(let x=x0;x<=x1;x++){if(++touched>4000000)throw Error('Paint stamp pixel budget exceeded');const p=[u+(x+.5)/tile.width,v+(y+.5)/tile.height],d=Math.hypot(p[0]-uv[0],p[1]-uv[1])/r;if(d>=1)continue;const falloff=d<=s.hardness?1:((1-d)/Math.max(1e-8,1-s.hardness))**2,coverage=alpha*falloff,offset=(y*tile.width+x)*4,key=id+':'+offset;if(!a.before.has(key)){if((a.before.size+1)*48>this.maxHistoryBytes){this.cancel();throw Error('Paint stroke history budget exceeded; stroke rolled back');}a.before.set(key,{id,offset,before:tile.data.slice(offset,offset+4)});}const dst=readPixel(tile,x,y);let src=s.color;if(s.mode==='clone'){if(!s.cloneOffset||s.cloneOffset.length!==2)throw Error('Clone brush requires a UV source offset');src=this.sample(a.source,p.map((v,k)=>v+s.cloneOffset[k]));}else if(s.mode==='smudge')src=this.sample(a.source,p.map((v,k)=>v-delta[k]));
                let result;if(s.mode==='erase')result=[...dst.slice(0,3),dst[3]*(1-coverage)];else{const as=src[3]*coverage,ad=dst[3],out=as+ad*(1-as);result=[0,1,2].map(k=>out?(src[k]*as+dst[k]*ad*(1-as))/out:0).concat(out);}for(let k=0;k<4;k++)tile.data[offset+k]=Math.round(clamp(k===3||tile.colorSpace==='linear'?result[k]:toSRGB(result[k]),0,1)*255);
            }
        }
    }
    end(){const a=this.active;if(!a)return false;const entries=[...a.before.values()].map(e=>({...e,after:(this.texture.kind==='udim'?this.texture.tiles[e.id]:this.texture).data.slice(e.offset,e.offset+4)})),stroke={entries,created:[...a.created],bytes:entries.length*48};this.active=null;this.redoStack=[];if(!entries.length){stroke.created.forEach(id=>delete this.texture.tiles[id]);return false;}this.undoStack.push(stroke);this.historyBytes+=stroke.bytes;while(this.historyBytes>this.maxHistoryBytes&&this.undoStack.length>1)this.historyBytes-=this.undoStack.shift().bytes;return true;}
    cancel(){if(!this.active)return;const a=this.active;for(const e of a.before.values()){const t=this.texture.kind==='udim'?this.texture.tiles[e.id]:this.texture;for(let k=0;k<4;k++)t.data[e.offset+k]=e.before[k];}for(const id of a.created)delete this.texture.tiles[id];this.active=null;}
    undo(){if(this.active)throw Error('Finish the stroke before undo');const s=this.undoStack.pop();if(!s)return false;for(const e of s.entries){const t=this.texture.kind==='udim'?this.texture.tiles[e.id]:this.texture;for(let k=0;k<4;k++)t.data[e.offset+k]=e.before[k];}s.createdTiles={};for(const id of s.created){s.createdTiles[id]=this.texture.tiles[id];delete this.texture.tiles[id];}this.redoStack.push(s);this.historyBytes-=s.bytes;return true;}
    redo(){if(this.active)throw Error('Finish the stroke before redo');const s=this.redoStack.pop();if(!s)return false;for(const id of s.created)this.texture.tiles[id]=s.createdTiles[id];for(const e of s.entries){const t=this.texture.kind==='udim'?this.texture.tiles[e.id]:this.texture;for(let k=0;k<4;k++)t.data[e.offset+k]=e.after[k];}this.undoStack.push(s);this.historyBytes+=s.bytes;return true;}
}
export function flattenTextures(textures){const sources=[],descriptors=[];for(const original of textures){const t=compositeLayers(original);if(t.kind==='udim'){validateUDIM(t);const tiles=[];for(const [id,bitmap] of Object.entries(t.tiles).sort((a,b)=>Number(a[0])-Number(b[0]))){const [u,v]=udimCoordinates(id);tiles.push({u,v,layer:sources.length});sources.push(bitmap);}descriptors.push({kind:1,tiles,missing:t.missing||[0,0,0,0]});}else{validateRaster(t);descriptors.push({kind:0,layer:sources.length,tiles:[]});sources.push(t);}}return {sources,descriptors};}
