import http from 'node:http';
import {readFile,stat} from 'node:fs/promises';
import {resolve,sep,extname} from 'node:path';
import {fileURLToPath} from 'node:url';
import {randomBytes,timingSafeEqual} from 'node:crypto';
import {RenderQueue} from '../src/distributed/queue.js';
import {encodeEXR,renderChannels} from '../src/io/exr.js';
const root=resolve(fileURLToPath(new URL('..',import.meta.url))),host=process.env.RENDER_HOST||'127.0.0.1',port=Number(process.env.RENDER_PORT||4183),token=process.env.RENDER_TOKEN||randomBytes(24).toString('hex'),queue=new RenderQueue({maxMemory:(Number(process.env.RENDER_MEMORY_MIB)||512)*1024*1024});
const allowed=(process.env.RENDER_ORIGINS||'http://localhost:4173,http://127.0.0.1:4173,http://localhost:4183,http://127.0.0.1:4183').split(',');
async function body(req,limit){const chunks=[];let size=0;for await(const c of req){size+=c.length;if(size>limit)throw Error('Request body exceeds limit');chunks.push(c);}return Buffer.concat(chunks);}
function authorized(req){const value=String(req.headers.authorization||'').replace(/^Bearer /,'');const a=Buffer.from(value),b=Buffer.from(token);return a.length===b.length&&timingSafeEqual(a,b);}
const mime={'.html':'text/html','.js':'text/javascript','.mjs':'text/javascript','.css':'text/css','.wgsl':'text/plain','.json':'application/json'};
const server=http.createServer(async(req,res)=>{const origin=req.headers.origin;if(origin&&allowed.includes(origin))res.setHeader('Access-Control-Allow-Origin',origin);res.setHeader('Vary','Origin');res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('Cache-Control','no-store');if(req.method==='OPTIONS'){if(origin&&!allowed.includes(origin)){res.writeHead(403);return res.end();}res.writeHead(204,{'Access-Control-Allow-Methods':'GET,POST,DELETE,OPTIONS','Access-Control-Allow-Headers':'Authorization,Content-Type,X-Render-Lease'});return res.end();}const send=(status,data)=>{res.writeHead(status,{'Content-Type':'application/json'});res.end(JSON.stringify(data));};try{const url=new URL(req.url,'http://localhost'),path=url.pathname;if(path.startsWith('/api/')){if(!authorized(req))return send(401,{error:'A coordinator access token is required'});if(req.method==='POST'&&path==='/api/jobs')return send(201,queue.create(JSON.parse(await body(req,34*1024*1024))));if(req.method==='GET'&&path==='/api/jobs')return send(200,[...queue.jobs.values()].map(j=>queue.describe(j)));if(req.method==='GET'&&path==='/api/work')return send(200,queue.claim(url.searchParams.get('worker')));const m=/^\/api\/jobs\/([^/]+)(?:\/tasks\/(\d+)\/(result|heartbeat)|\/(image\.exr))?$/.exec(path);if(m){const [,jobId,taskId,action,image]=m;if(image&&req.method==='GET'){const {hdr,aovs}=queue.image(jobId);res.writeHead(200,{'Content-Type':'image/x-exr','Content-Disposition':`attachment; filename="aureon-${jobId}.exr"`});return res.end(encodeEXR({width:hdr.width,height:hdr.height,channels:renderChannels(hdr,aovs)}));}if(action==='heartbeat'&&req.method==='POST')return send(200,queue.heartbeat(jobId,Number(taskId),req.headers['x-render-lease']));if(action==='result'&&req.method==='POST'){const raw=await body(req,256*256*24*4);if(raw.length%4)throw Error('Misaligned result');const data=new Float32Array(raw.length/4),view=new DataView(raw.buffer,raw.byteOffset,raw.byteLength);for(let i=0;i<data.length;i++)data[i]=view.getFloat32(i*4,true);return send(200,queue.complete(jobId,Number(taskId),req.headers['x-render-lease'],data));}if(req.method==='GET')return send(200,queue.describe(jobId));if(req.method==='DELETE')return send(200,url.searchParams.get('purge')==='1'?{removed:queue.remove(jobId)}:queue.cancel(jobId));}return send(404,{error:'API route not found'});}if(req.method!=='GET')return send(405,{error:'Method not allowed'});const pathname=decodeURIComponent(path==='/'?'/worker.html':path),file=resolve(root,'.'+pathname);if(!file.startsWith(root+sep)||pathname.split('/').some(p=>p.startsWith('.'))||!(await stat(file)).isFile())return send(404,{error:'File not found'});res.writeHead(200,{'Content-Type':mime[extname(file)]||'application/octet-stream'});res.end(await readFile(file));}catch(error){send(400,{error:error.message});}});
server.listen(port,host,()=>console.log(`Aureon render coordinator: http://${host}:${port}\nAccess token: ${token}\nFor remote GPU workers, terminate HTTPS with a trusted reverse proxy. No shell commands or external scene URLs are executed.`));
