/** Hierarchical FK, quaternion interpolation, four-influence LBS/dual-quaternion
 * skinning, automatic weights, weight editing, and FABRIK inverse kinematics. */
import {add,sub,mul,dot,cross,normalize,identity,matMul,inverse,transformPoint,compose,clamp} from '../core/math.js';
import {cloneMesh,bounds,vertex} from '../geometry/mesh.js';
export const quatNormalize=q=>{const l=Math.hypot(...q);return l>1e-12?q.map(x=>x/l):[0,0,0,1];};
export const quatConjugate=q=>[-q[0],-q[1],-q[2],q[3]];
export const quatMul=(a,b)=>[a[3]*b[0]+a[0]*b[3]+a[1]*b[2]-a[2]*b[1],a[3]*b[1]-a[0]*b[2]+a[1]*b[3]+a[2]*b[0],a[3]*b[2]+a[0]*b[1]-a[1]*b[0]+a[2]*b[3],a[3]*b[3]-a[0]*b[0]-a[1]*b[1]-a[2]*b[2]];
export function quatEuler(degrees){const [x,y,z]=degrees.map(v=>v*Math.PI/360),qx=[Math.sin(x),0,0,Math.cos(x)],qy=[0,Math.sin(y),0,Math.cos(y)],qz=[0,0,Math.sin(z),Math.cos(z)];return quatMul(qz,quatMul(qy,qx));}
export function eulerQuat(q){const m=quatMatrix(q),y=Math.asin(clamp(-m[2],-1,1)),c=Math.cos(y);return [Math.abs(c)>1e-7?Math.atan2(m[6],m[10]):Math.atan2(-m[9],m[5]),y,Math.abs(c)>1e-7?Math.atan2(m[1],m[0]):0].map(v=>v*180/Math.PI);}
export function quatMatrix(q,position=[0,0,0],scale=[1,1,1]){const [x,y,z,w]=quatNormalize(q),m=[1-2*(y*y+z*z),2*(x*y+z*w),2*(x*z-y*w),0,2*(x*y-z*w),1-2*(x*x+z*z),2*(y*z+x*w),0,2*(x*z+y*w),2*(y*z-x*w),1-2*(x*x+y*y),0,...position,1];for(let c=0;c<3;c++)for(let r=0;r<3;r++)m[c*4+r]*=scale[c];return m;}
export function matrixQuat(m){const trace=m[0]+m[5]+m[10];let q;if(trace>0){const s=Math.sqrt(trace+1)*2;q=[(m[6]-m[9])/s,(m[8]-m[2])/s,(m[1]-m[4])/s,.25*s];}else if(m[0]>m[5]&&m[0]>m[10]){const s=Math.sqrt(1+m[0]-m[5]-m[10])*2;q=[.25*s,(m[4]+m[1])/s,(m[8]+m[2])/s,(m[6]-m[9])/s];}else if(m[5]>m[10]){const s=Math.sqrt(1+m[5]-m[0]-m[10])*2;q=[(m[4]+m[1])/s,.25*s,(m[9]+m[6])/s,(m[8]-m[2])/s];}else{const s=Math.sqrt(1+m[10]-m[0]-m[5])*2;q=[(m[8]+m[2])/s,(m[9]+m[6])/s,.25*s,(m[1]-m[4])/s];}return quatNormalize(q);}
export function slerp(a,b,t){let c=dot(a,b);if(c<0){b=b.map(v=>-v);c=-c;}if(c>.9995)return quatNormalize(a.map((v,i)=>v+(b[i]-v)*t));const angle=Math.acos(clamp(c,-1,1)),s=Math.sin(angle);return a.map((v,i)=>(v*Math.sin((1-t)*angle)+b[i]*Math.sin(t*angle))/s);}
export function quatFromTo(a,b){a=normalize(a);b=normalize(b);const d=dot(a,b);if(d<-.999999){const axis=normalize(cross(a,Math.abs(a[0])<.8?[1,0,0]:[0,1,0]));return [...axis,0];}return quatNormalize([...cross(a,b),1+d]);}
export function bonePose(bone,frame=0){const keys=bone.keys||[];if(!keys.length)return {position:bone.position||[0,0,0],rotation:bone.rotation||[0,0,0,1],scale:bone.scale||[1,1,1]};const ks=[...keys].sort((a,b)=>a.frame-b.frame);let a=ks[0],b=ks.at(-1);if(frame<=a.frame)return {...bone,...a};if(frame>=b.frame)return {...bone,...b};for(let i=1;i<ks.length;i++)if(frame<=ks[i].frame){a=ks[i-1];b=ks[i];break;}const t=(frame-a.frame)/(b.frame-a.frame);return {position:(a.position||bone.position).map((v,i)=>v+((b.position||bone.position)[i]-v)*t),rotation:slerp(a.rotation||bone.rotation,b.rotation||bone.rotation,t),scale:(a.scale||bone.scale||[1,1,1]).map((v,i)=>v+((b.scale||bone.scale||[1,1,1])[i]-v)*t)};}
export function boneWorlds(rig,frame=0){const matrices=[],visiting=new Set();const visit=i=>{if(matrices[i])return matrices[i];if(visiting.has(i)||!rig.bones[i])throw Error('Invalid or cyclic skeleton');visiting.add(i);const b=rig.bones[i],p=bonePose(b,frame),m=quatMatrix(p.rotation,p.position,p.scale);matrices[i]=b.parent>=0?matMul(visit(b.parent),m):m;visiting.delete(i);return matrices[i];};rig.bones.forEach((_,i)=>visit(i));return matrices;}
export function bindRig(mesh,rig,{mode='linear',automatic=true}={}){const out=structuredClone(rig);out.mode=mode;out.inverseBind=boneWorlds(out,0).map(inverse);if(automatic||!out.weights){const w=automaticWeights(mesh,out);out.weights=w.weights;out.indices=w.indices;}validateRig(out,mesh.positions.length/3);return out;}
export function createChainRig(mesh,count=3){if(!Number.isInteger(count)||count<2||count>64)throw Error('Bone count must be between 2 and 64');const b=bounds(mesh),height=Math.max(1e-3,b.max[1]-b.min[1]),bones=[];for(let i=0;i<count;i++)bones.push({name:`Joint ${i+1}`,parent:i-1,position:i?[0,height/(count-1),0]:[(b.min[0]+b.max[0])/2,b.min[1],(b.min[2]+b.max[2])/2],rotation:[0,0,0,1],scale:[1,1,1],keys:[]});return bindRig(mesh,{bones});}
export function automaticWeights(mesh,rig){const ws=boneWorlds(rig),ps=ws.map(m=>m.slice(12,15)),weights=[],indices=[];for(let i=0;i<mesh.positions.length/3;i++){const p=vertex(mesh,i),dist=ps.map((a,j)=>{const child=rig.bones.findIndex(b=>b.parent===j),b=child>=0?ps[child]:a,ab=sub(b,a),t=clamp(dot(sub(p,a),ab)/Math.max(dot(ab,ab),1e-12),0,1);return {j,d:Math.hypot(...sub(p,add(a,mul(ab,t))))};}).sort((a,b)=>a.d-b.d).slice(0,4);const ws=dist.map(x=>1/Math.max(x.d,1e-4)**3),sum=ws.reduce((a,b)=>a+b,0);for(let k=0;k<4;k++){indices.push(dist[k]?.j??0);weights.push((ws[k]||0)/sum);}}return {weights,indices};}
export function validateRig(rig,vertexCount){if(!rig||!Array.isArray(rig.bones)||!rig.bones.length||rig.bones.length>512)throw Error('Invalid skeleton size');boneWorlds(rig);if(!Array.isArray(rig.inverseBind)||rig.inverseBind.length!==rig.bones.length||rig.inverseBind.some(m=>m.length!==16||!m.every(Number.isFinite)))throw Error('Invalid inverse bind matrices');if(rig.weights?.length!==vertexCount*4||rig.indices?.length!==vertexCount*4)throw Error('Skin weights do not match topology. Rebind after topology changes.');for(let i=0;i<rig.weights.length;i+=4){let sum=0;for(let k=0;k<4;k++){const w=rig.weights[i+k],j=rig.indices[i+k];if(!Number.isFinite(w)||w<0||!Number.isInteger(j)||j<0||j>=rig.bones.length)throw Error('Invalid skin influence');sum+=w;}if(Math.abs(sum-1)>1e-4)throw Error('Skin weights must sum to one');}return rig;}
export function setVertexWeights(rig,vertexIndex,influences){if(vertexIndex<0||vertexIndex*4>=rig.weights.length)throw Error('Unknown skin vertex');const arr=influences.filter(v=>v.weight>0).sort((a,b)=>b.weight-a.weight).slice(0,4),sum=arr.reduce((s,v)=>s+v.weight,0);if(sum<=0||arr.some(v=>!Number.isFinite(v.weight)||!Number.isInteger(v.bone)||v.bone<0||v.bone>=rig.bones.length))throw Error('Invalid weight edit');for(let k=0;k<4;k++){rig.indices[vertexIndex*4+k]=arr[k]?.bone||0;rig.weights[vertexIndex*4+k]=(arr[k]?.weight||0)/sum;}}
export function skinMesh(mesh,rig,frame=0,{matrices:overrideMatrices}={}){validateRig(rig,mesh.positions.length/3);const out=cloneMesh(mesh),matrices=overrideMatrices||boneWorlds(rig,frame).map((m,i)=>matMul(m,rig.inverseBind[i]));delete out.vertexNormals;let duals;
    if(rig.mode==='dualQuaternion'){for(const m of matrices){for(let i=0;i<3;i++)if(Math.abs(Math.hypot(...m.slice(i*4,i*4+3))-1)>1e-4)throw Error('Dual-quaternion skinning requires rigid bone transforms. Use linear mode for scaled bones.');}duals=matrices.map(m=>{const q=matrixQuat(m),d=quatMul([...m.slice(12,15),0],q).map(v=>v*.5);return {q,d};});}
    for(let i=0;i<out.positions.length/3;i++){const p=vertex(mesh,i);let result=[0,0,0];if(!duals){for(let k=0;k<4;k++){const w=rig.weights[i*4+k];if(w)result=add(result,mul(transformPoint(matrices[rig.indices[i*4+k]],p),w));}}else{let real=[0,0,0,0],dual=[0,0,0,0],reference=duals[rig.indices[i*4]].q;for(let k=0;k<4;k++){const d=duals[rig.indices[i*4+k]],w=rig.weights[i*4+k]*(dot(reference,d.q)<0?-1:1);real=real.map((v,j)=>v+d.q[j]*w);dual=dual.map((v,j)=>v+d.d[j]*w);}const len=Math.hypot(...real);real=real.map(v=>v/len);dual=dual.map(v=>v/len);const proj=dot(real,dual);dual=dual.map((v,j)=>v-real[j]*proj);const t=quatMul(dual,quatConjugate(real)).slice(0,3).map(v=>2*v);result=add(transformPoint(quatMatrix(real),p),t);}out.positions.splice(i*3,3,...result);}return out;}
/** Position-only FABRIK, preserving segment lengths, including unreachable goals. */
export function fabrik(points,target,{iterations=64,tolerance=1e-5,pole=null}={}){if(points.length<2||target.length!==3||!target.every(Number.isFinite))throw Error('Invalid IK chain/target');const ps=points.map(p=>[...p]),root=[...ps[0]],lens=ps.slice(1).map((p,i)=>Math.hypot(...sub(p,ps[i]))),total=lens.reduce((a,b)=>a+b,0);if(lens.some(v=>v<1e-9))throw Error('IK chain contains a zero-length bone');const move=(a,b,length)=>add(a,mul(normalize(sub(b,a)),length));
    if(Math.hypot(...sub(target,root))>=total){const dir=normalize(sub(target,root));for(let i=1;i<ps.length;i++)ps[i]=add(ps[i-1],mul(dir,lens[i-1]));}
    else for(let it=0;it<iterations;it++){ps[ps.length-1]=[...target];for(let i=ps.length-2;i>=0;i--)ps[i]=move(ps[i+1],ps[i],lens[i]);ps[0]=[...root];for(let i=1;i<ps.length;i++)ps[i]=move(ps[i-1],ps[i],lens[i-1]);if(Math.hypot(...sub(ps.at(-1),target))<tolerance)break;}
    if(pole)for(let i=1;i<ps.length-1;i++){const axis=normalize(sub(ps[i+1],ps[i-1])),center=add(ps[i-1],mul(axis,dot(sub(ps[i],ps[i-1]),axis))),radial=sub(ps[i],center),toward=sub(sub(pole,center),mul(axis,dot(sub(pole,center),axis)));if(Math.hypot(...toward)>1e-8)ps[i]=add(center,mul(normalize(toward),Math.hypot(...radial)));}
    return {points:ps,error:Math.hypot(...sub(ps.at(-1),target)),reachable:Math.hypot(...sub(target,root))<=total};}
export function solveRigIK(rig,endBone,target,{rootBone=0,frame=0,pole=null,iterations=64}={}){const out=structuredClone(rig),chain=[];let i=endBone;while(i>=0){chain.unshift(i);if(i===rootBone)break;i=out.bones[i]?.parent??-1;}if(chain[0]!==rootBone||chain.length<2)throw Error('IK root must be an ancestor of the end joint');const ws=boneWorlds(out,frame),original=chain.map(i=>ws[i].slice(12,15)),solution=fabrik(original,target,{pole,iterations});for(let k=0;k<chain.length-1;k++){const i=chain[k],b=out.bones[i],current=boneWorlds(out,frame),position=current[i].slice(12,15),child=current[chain[k+1]].slice(12,15),delta=quatFromTo(sub(child,position),sub(solution.points[k+1],solution.points[k])),global=quatMul(delta,matrixQuat(current[i])),parent=b.parent>=0?matrixQuat(current[b.parent]):[0,0,0,1];let q=quatMul(quatConjugate(parent),global);if(b.limits){const e=eulerQuat(q).map((v,j)=>clamp(v,b.limits.min[j],b.limits.max[j]));q=quatEuler(e);}b.rotation=quatNormalize(q);if(b.keys?.length){const pose=bonePose(b,frame),key={frame,position:[...pose.position],scale:[...pose.scale],rotation:[...b.rotation]};const at=b.keys.findIndex(x=>x.frame===frame);at>=0?b.keys.splice(at,1,key):b.keys.push(key);}}
    const final=boneWorlds(out,frame)[endBone].slice(12,15);return {rig:out,error:Math.hypot(...sub(final,target)),reachable:solution.reachable};}
