/** glTF 2.0 / GLB interchange. Bounds-checked accessors, normalized/sparse data,
 * scene hierarchy, PBR images, skins, morphs and all core animation samplers.
 * Unsupported required extensions fail explicitly rather than silently degrade.
 */
import {emptyDocument,newObject,material,GeometryCache,worldMatrix,sampleTransform} from '../scene/document.js';
import {validateMesh,normals,triangulate,cloneMesh,faceNormal} from '../geometry/mesh.js';
import {evaluateModifiers} from '../geometry/modifiers.js';
import {createPrimitive} from '../geometry/primitives.js';
import {identity,inverse,matMul,hexToRGB,srgbToLinear,rgbToHex} from '../core/math.js';
import {matrixQuat,eulerQuat,quatEuler,quatMatrix,validateRig} from '../animation/rig.js';
import {decodeBitmap} from '../materials/textures.js';
import {encodePNG,bytesBase64,base64Bytes} from './png.js';
const components={SCALAR:1,VEC2:2,VEC3:3,VEC4:4,MAT2:4,MAT3:9,MAT4:16};
const info={5120:['getInt8',1],5121:['getUint8',1],5122:['getInt16',2],5123:['getUint16',2],5125:['getUint32',4],5126:['getFloat32',4]};
const linearToSRGB=v=>v<=.0031308?v*12.92:1.055*Math.max(0,v)**(1/2.4)-.055;
export function parseGLB(input){const b=input instanceof Uint8Array?input:new Uint8Array(input),v=new DataView(b.buffer,b.byteOffset,b.byteLength);if(b.length<20||v.getUint32(0,true)!==0x46546c67||v.getUint32(4,true)!==2||v.getUint32(8,true)!==b.length)throw Error('Invalid GLB 2.0 header');let p=12,json=null,bin=null;while(p<b.length){if(p+8>b.length)throw Error('Truncated GLB chunk');const size=v.getUint32(p,true),type=v.getUint32(p+4,true);p+=8;if(size%4||p+size>b.length)throw Error('Invalid GLB chunk size');if(type===0x4e4f534a){if(json)throw Error('Duplicate GLB JSON chunk');json=JSON.parse(new TextDecoder().decode(b.subarray(p,p+size)));}else if(type===0x004e4942){if(bin)throw Error('Duplicate GLB BIN chunk');bin=b.slice(p,p+size);}p+=size;}if(!json)throw Error('GLB has no JSON');return {json,bin};}
function dataURI(uri){const match=/^data:([^,]*?),(.*)$/s.exec(uri);if(!match)throw Error('Not a data URI');return match[1].includes(';base64')?base64Bytes(match[2]):new TextEncoder().encode(decodeURIComponent(match[2]));}
async function resource(uri,resolver){if(uri.startsWith('data:'))return dataURI(uri);if(!resolver)throw Error(`External asset "${uri}" is required. Import with its companion files.`);const bytes=await resolver(uri);if(!bytes)throw Error(`Missing external asset ${uri}`);return bytes instanceof Uint8Array?bytes:new Uint8Array(bytes);}
export function readAccessor(gltf,buffers,index){const a=gltf.accessors?.[index];if(!a||!(a.componentType in info)||!(a.type in components)||!Number.isInteger(a.count)||a.count<0||a.count>4000000)throw Error('Invalid glTF accessor');const [getter,size]=info[a.componentType],n=components[a.type],out=new Array(a.count*n).fill(0);if(a.type.startsWith('MAT')&&size<4)throw Error('Integer matrix accessors with column padding are not supported');const normalize=v=>!a.normalized?v:a.componentType===5120?Math.max(v/127,-1):a.componentType===5121?v/255:a.componentType===5122?Math.max(v/32767,-1):a.componentType===5123?v/65535:v;
    function read(viewIndex,offset,count,stride,fn){const bv=gltf.bufferViews?.[viewIndex],buffer=buffers[bv?.buffer];if(!bv||!buffer)throw Error('Missing glTF buffer view');const base=(bv.byteOffset||0)+offset,step=stride||bv.byteStride||n*size;if(base<0||offset<0||step<n*size||base+(count?count-1:0)*step+(count?n*size:0)>(bv.byteOffset||0)+bv.byteLength||(bv.byteOffset||0)+bv.byteLength>buffer.length)throw Error('glTF accessor exceeds its buffer view');const v=new DataView(buffer.buffer,buffer.byteOffset,buffer.byteLength);for(let i=0;i<count;i++)for(let k=0;k<n;k++)fn(i,k,normalize(v[getter](base+i*step+k*size,true)));}
    if(a.bufferView!==undefined)read(a.bufferView,a.byteOffset||0,a.count,0,(i,k,v)=>out[i*n+k]=v);
    if(a.sparse){const sp=a.sparse;if(sp.count>a.count||!Number.isInteger(sp.count))throw Error('Invalid sparse accessor count');const ii=info[sp.indices.componentType];if(!ii||![5121,5123,5125].includes(sp.indices.componentType))throw Error('Invalid sparse index type');const bv=gltf.bufferViews[sp.indices.bufferView],buffer=buffers[bv?.buffer];if(!buffer||(sp.indices.byteOffset||0)+sp.count*ii[1]>bv.byteLength)throw Error('Sparse indices exceed buffer');const dv=new DataView(buffer.buffer,buffer.byteOffset,buffer.byteLength),ids=[];for(let i=0;i<sp.count;i++){const id=dv[ii[0]]((bv.byteOffset||0)+(sp.indices.byteOffset||0)+i*ii[1],true);if(id>=a.count||(i&&id<=ids[i-1]))throw Error('Sparse indices must be increasing and in range');ids.push(id);}read(sp.values.bufferView,sp.values.byteOffset||0,sp.count,n*size,(i,k,v)=>out[ids[i]*n+k]=v);}
    if(!out.every(Number.isFinite))throw Error('Nonfinite glTF accessor');return out;}
export function decomposeMatrix(matrix){if(matrix.length!==16||!matrix.every(Number.isFinite))throw Error('Invalid glTF matrix');const scale=[0,1,2].map(i=>Math.hypot(...matrix.slice(i*4,i*4+3))),m=[...matrix];if(scale.some(s=>s<1e-9))throw Error('Singular glTF transform');const determinant=m[0]*(m[5]*m[10]-m[6]*m[9])-m[4]*(m[1]*m[10]-m[2]*m[9])+m[8]*(m[1]*m[6]-m[2]*m[5]);if(determinant<0)scale[0]*=-1;for(let c=0;c<3;c++)for(let r=0;r<3;r++)m[c*4+r]/=scale[c];const rotation=eulerQuat(matrixQuat(m)),position=matrix.slice(12,15),test=quatMatrix(quatEuler(rotation),position,scale);if(test.some((v,i)=>Math.abs(v-matrix[i])>1e-4))throw Error('Sheared/perspective node matrices cannot be represented by this editor');return {position,rotation,scale};}
export async function importGLTF(input,{resolveResource,decodeImage=decodeBitmap,animation=0,fps=24}={}){
    let gltf,bin;if(input instanceof ArrayBuffer||ArrayBuffer.isView(input)){const p=parseGLB(input);gltf=p.json;bin=p.bin;}else gltf=typeof input==='string'?JSON.parse(input):structuredClone(input);
    if(gltf.asset?.version!=='2.0')throw Error('Only glTF 2.0 is supported');const supported=new Set(['KHR_materials_transmission','KHR_materials_ior','KHR_materials_emissive_strength']);for(const ext of gltf.extensionsRequired||[])if(!supported.has(ext))throw Error(`Required glTF extension is unsupported: ${ext}`);
    const buffers=[];for(let i=0;i<(gltf.buffers||[]).length;i++){const spec=gltf.buffers[i],bytes=spec.uri?await resource(spec.uri,resolveResource):i===0?bin:null;if(!bytes||bytes.length<spec.byteLength)throw Error('Missing/truncated glTF binary buffer');buffers.push(bytes);}
    const read=i=>readAccessor(gltf,buffers,i),doc=emptyDocument();doc.name=gltf.scenes?.[gltf.scene||0]?.name||'Imported glTF';doc.objects=[];doc.materials=[];doc.textures=[];doc.animation.fps=fps;doc.interchangeWarnings=[];
    for(const image of gltf.images||[]){let bytes;if(image.uri)bytes=await resource(image.uri,resolveResource);else{const bv=gltf.bufferViews?.[image.bufferView],b=buffers[bv?.buffer];if(!b||(bv.byteOffset||0)+bv.byteLength>b.length)throw Error('Invalid embedded glTF image');bytes=b.slice(bv.byteOffset||0,(bv.byteOffset||0)+bv.byteLength);}doc.textures.push(await decodeImage(new Blob([bytes],{type:image.mimeType||'image/png'}),image.name||'glTF bitmap'));}
    for(const src of gltf.materials||[]){const pbr=src.pbrMetallicRoughness||{},base=pbr.baseColorFactor||[1,1,1,1],em=src.emissiveFactor||[0,0,0],strength=src.extensions?.KHR_materials_emissive_strength?.emissiveStrength||1,hasEmission=em.some(v=>v>0),m=material(src.name||'glTF material',rgbToHex(base.slice(0,3).map(linearToSRGB)),{roughness:pbr.roughnessFactor??1,metallic:pbr.metallicFactor??1,transmission:src.extensions?.KHR_materials_transmission?.transmissionFactor||0,ior:src.extensions?.KHR_materials_ior?.ior||1.5,emission:hasEmission?Math.max(...em)*strength:0});if(pbr.baseColorTexture){const texture=gltf.textures?.[pbr.baseColorTexture.index];if(texture?.source===undefined)throw Error('Missing glTF base-color texture');m.bitmap=texture.source;}if(pbr.metallicRoughnessTexture||src.normalTexture||src.occlusionTexture||src.emissiveTexture)doc.interchangeWarnings.push(`Material ${m.name}: additional texture channels retained in gltfSource but not applied automatically`);if(src.alphaMode&&src.alphaMode!=='OPAQUE')doc.interchangeWarnings.push(`Material ${m.name}: alpha mode ${src.alphaMode} is not rendered`);m.gltfSource=structuredClone(src);doc.materials.push(m);}if(!doc.materials.length)doc.materials=[material('glTF default','#ffffff',{metallic:1,roughness:1})];
    const nodes=gltf.nodes||[],map=nodes.map((n,i)=>{const o=newObject('mesh',{},n.name||`Node ${i}`);o.mesh={positions:[],uvs:[],faces:[],smooth:true};Object.assign(o,n.matrix?decomposeMatrix(n.matrix):{position:n.translation||[0,0,0],rotation:n.rotation?eulerQuat(n.rotation):[0,0,0],scale:n.scale||[1,1,1]});o.trackFPS=fps;if(n.extras?.aureonHidden)o.visible=false;return o;});doc.objects.push(...map);nodes.forEach((n,i)=>(n.children||[]).forEach(j=>{if(!map[j]||map[j].parent)throw Error('Invalid glTF node hierarchy');map[j].parent=map[i].id;}));
    const objectForPrimitive=[];nodes.forEach((node,ni)=>{if(node.mesh===undefined)return;const src=gltf.meshes?.[node.mesh];if(!src)throw Error('Missing glTF mesh');for(let pi=0;pi<src.primitives.length;pi++){const primitive=src.primitives[pi],attr=primitive.attributes||{};if(attr.POSITION===undefined)throw Error('glTF mesh lacks POSITION');const positions=read(attr.POSITION),uvs=attr.TEXCOORD_0!==undefined?read(attr.TEXCOORD_0):[],indices=primitive.indices!==undefined?read(primitive.indices):Array.from({length:positions.length/3},(_,i)=>i),faces=[],mode=primitive.mode??4;if(mode===4){if(indices.length%3)throw Error('Incomplete triangle indices');for(let i=0;i<indices.length;i+=3)faces.push(indices.slice(i,i+3));}else if(mode===5){for(let i=2;i<indices.length;i++)faces.push(i%2?[indices[i-1],indices[i-2],indices[i]]:[indices[i-2],indices[i-1],indices[i]]);}else if(mode===6){for(let i=2;i<indices.length;i++)faces.push([indices[0],indices[i-1],indices[i]]);}else throw Error('Only triangle, strip and fan glTF primitives are supported');const o=src.primitives.length===1?map[ni]:newObject('mesh',{},`${map[ni].name} · primitive ${pi+1}`);if(o!==map[ni]){o.position=[0,0,0];o.parent=map[ni].id;doc.objects.push(o);}o.mesh=validateMesh({positions,uvs,faces,smooth:true});if(attr.NORMAL!==undefined)o.mesh.vertexNormals=read(attr.NORMAL);o.material=primitive.material??0;if(!doc.materials[o.material])throw Error('Missing glTF material');if(primitive.targets){o.morphTargets=primitive.targets.map(t=>t.POSITION!==undefined?read(t.POSITION):new Array(positions.length).fill(0));o.morphWeights=node.weights||src.weights||primitive.targets.map(()=>0);}
        objectForPrimitive.push({o,node,ni,primitive});}});
    const ani=gltf.animations?.[animation];if(ani){let duration=0;for(const ch of ani.channels){const sampler=ani.samplers[ch.sampler],target=map[ch.target.node];if(!sampler||!target)throw Error('Invalid glTF animation target');const times=read(sampler.input),values=read(sampler.output),path=ch.target.path,interpolation=sampler.interpolation||'LINEAR';if(!['translation','rotation','scale','weights'].includes(path))throw Error('Unknown glTF animation channel');if(times.some((v,i)=>v<0||i&&v<=times[i-1]))throw Error('Animation times must strictly increase');const count=values.length/times.length/(interpolation==='CUBICSPLINE'?3:1);const track={path,times,values,components:count,interpolation};(target.tracks||=[]).push(track);if(path==='weights')for(const record of objectForPrimitive.filter(r=>r.ni===ch.target.node&&r.o!==target)){(record.o.tracks||=[]).push(structuredClone(track));record.o.trackFPS=fps;}duration=Math.max(duration,times.at(-1)||0);}doc.animation.end=Math.max(1,Math.ceil(duration*fps));}
    for(const {o,node,primitive}of objectForPrimitive){if(node.skin===undefined)continue;const skin=gltf.skins?.[node.skin];if(!skin||primitive.attributes.JOINTS_0===undefined||primitive.attributes.WEIGHTS_0===undefined)throw Error('Skin requires JOINTS_0 and WEIGHTS_0');const indices=read(primitive.attributes.JOINTS_0),weights=read(primitive.attributes.WEIGHTS_0);for(let i=0;i<weights.length;i+=4){const sum=weights.slice(i,i+4).reduce((a,b)=>a+b,0);if(sum<=0)throw Error('Zero glTF skin weight sum');for(let k=0;k<4;k++)weights[i+k]/=sum;}const ib=skin.inverseBindMatrices!==undefined?read(skin.inverseBindMatrices):skin.joints.flatMap(()=>identity());o.rig={mode:'linear',indices,weights,bones:skin.joints.map(j=>({name:map[j]?.name||'Joint',parent:-1,position:[0,0,0],rotation:[0,0,0,1],scale:[1,1,1],keys:[]})),inverseBind:skin.joints.map((_,i)=>ib.slice(i*16,i*16+16)),externalJoints:skin.joints.map(j=>{if(!map[j])throw Error('Unknown skin joint');return map[j].id;})};}
    const activeScene=gltf.scenes?.[gltf.scene||0];if(activeScene){const visible=new Set();const visit=i=>{if(visible.has(i))return;visible.add(i);for(const c of nodes[i]?.children||[])visit(c);};activeScene.nodes.forEach(visit);nodes.forEach((n,i)=>{if(!visible.has(i))map[i].visible=false;});}
    return doc;
}
class Builder{constructor(){this.parts=[];this.length=0;this.views=[];this.accessors=[];}add(values,type,componentType=5126){const C={5126:Float32Array,5125:Uint32Array,5123:Uint16Array,5121:Uint8Array}[componentType],typed=new C(values),bytes=new Uint8Array(typed.buffer);const padding=(4-this.length%4)%4;if(padding){this.parts.push(new Uint8Array(padding));this.length+=padding;}const view=this.views.length;this.views.push({buffer:0,byteOffset:this.length,byteLength:bytes.length});this.parts.push(bytes);this.length+=bytes.length;const accessor={bufferView:view,componentType,count:values.length/components[type],type};if(type==='VEC3'&&values.length){accessor.min=[0,1,2].map(k=>{let v=Infinity;for(let i=k;i<values.length;i+=3)v=Math.min(v,values[i]);return v;});accessor.max=[0,1,2].map(k=>{let v=-Infinity;for(let i=k;i<values.length;i+=3)v=Math.max(v,values[i]);return v;});}const index=this.accessors.length;this.accessors.push(accessor);return index;}bytes(){const b=new Uint8Array(this.length);let o=0;for(const p of this.parts){b.set(p,o);o+=p.length;}return b;}}
export function exportGLTF2(doc,geometry=new GeometryCache(),{binary=false,animation=true,skins=true}={}){geometry.setContext?.(doc);const b=new Builder(),g={asset:{version:'2.0',generator:'Aureon Studio 0.2'},scene:0,scenes:[{name:doc.name,nodes:[]}],nodes:[],meshes:[],materials:[],accessors:b.accessors,bufferViews:b.views,buffers:[],extensionsUsed:[]},used=new Set(),objectMap=new Map(doc.objects.map((o,i)=>[o.id,i]));
    g.materials=doc.materials.map(m=>{const out={name:m.name,pbrMetallicRoughness:{baseColorFactor:[...hexToRGB(m.color).map(srgbToLinear),1],metallicFactor:m.metallic,roughnessFactor:m.roughness},doubleSided:true};if(Number.isInteger(m.bitmap))out.pbrMetallicRoughness.baseColorTexture={index:m.bitmap};if(m.emission>0){out.emissiveFactor=hexToRGB(m.color).map(srgbToLinear);out.extensions={KHR_materials_emissive_strength:{emissiveStrength:m.emission}};used.add('KHR_materials_emissive_strength');}if(m.transmission>0){(out.extensions||={}).KHR_materials_transmission={transmissionFactor:m.transmission};used.add('KHR_materials_transmission');}if(m.ior!==1.5){(out.extensions||={}).KHR_materials_ior={ior:m.ior};used.add('KHR_materials_ior');}if(m.graph||m.subsurface)out.extras={aureonMaterial:structuredClone(m)};return out;});
    if(doc.textures?.length){g.images=doc.textures.map(t=>({name:t.name,uri:'data:image/png;base64,'+bytesBase64(encodePNG(t.width,t.height,Uint8Array.from(t.data)))}));g.textures=doc.textures.map((_,i)=>({source:i,sampler:0}));g.samplers=[{magFilter:9729,minFilter:9987,wrapS:10497,wrapT:10497}];}
    for(const o of doc.objects){const node={name:o.name,translation:[...o.position],rotation:quatEuler(o.rotation),scale:[...o.scale]};if(o.visible===false)node.extras={aureonHidden:true};g.nodes.push(node);}
    doc.objects.forEach((o,i)=>{const parent=objectMap.get(o.parent);if(parent===undefined)g.scenes[0].nodes.push(i);else(g.nodes[parent].children||=[]).push(i);});
    const anim={name:'Scene animation',samplers:[],channels:[]};const channel=(node,path,times,values,interpolation='LINEAR',type)=>{const input=b.add(times,'SCALAR'),output=b.add(values,type|| (path==='rotation'?'VEC4':path==='weights'?'SCALAR':'VEC3')),sampler=anim.samplers.length;anim.samplers.push({input,output,interpolation});anim.channels.push({sampler,target:{node,path}});};
    doc.objects.forEach((o,oi)=>{let mesh;if((o.rig&&skins)||o.morphTargets){const base=o.type==='mesh'?o.mesh:createPrimitive(o.type,o.params);mesh=evaluateModifiers(base,o.modifiers);}else mesh=geometry.get(o);if(mesh.faces.length){
            if(o.rig&&skins)validateRig(o.rig,mesh.positions.length/3);
            if(o.morphTargets&&o.modifiers?.some(m=>m.enabled!==false))throw Error('Bake/remove modifiers before exporting morph targets');
            if(o.morphTargets?.some(p=>p.length!==mesh.positions.length||!p.every(Number.isFinite)))throw Error('Morph target topology does not match the exported mesh');
            const smoothNormals=mesh.vertexNormals||Array.from(normals(mesh)),flat=new Set(mesh.flatFaces||[]),positions=[],normalValues=[],uvs=[],sources=[],vertices=new Map(),groups=new Map();
            for(const tri of triangulate(mesh)){
                const hard=mesh.smooth===false||flat.has(tri.face),normal=hard?faceNormal(mesh,mesh.faces[tri.face]):null,mat=o.materialSlots?.[mesh.faceMaterials?.[tri.face]]??o.material;
                if(!doc.materials[mat])throw Error('Missing export face material');
                const indices=groups.get(mat)||[];groups.set(mat,indices);
                for(const id of tri.ids){const key=hard?`${id}:${tri.face}`:`${id}:smooth`;let vi=vertices.get(key);if(vi===undefined){vi=sources.length;vertices.set(key,vi);sources.push(id);positions.push(...mesh.positions.slice(id*3,id*3+3));normalValues.push(...(normal||smoothNormals.slice(id*3,id*3+3)));if(mesh.uvs?.length)uvs.push(...mesh.uvs.slice(id*2,id*2+2));}indices.push(vi);}
            }
            const attributes={POSITION:b.add(positions,'VEC3'),NORMAL:b.add(normalValues,'VEC3')};if(uvs.length)attributes.TEXCOORD_0=b.add(uvs,'VEC2');
            if(o.rig&&skins){attributes.JOINTS_0=b.add(sources.flatMap(id=>o.rig.indices.slice(id*4,id*4+4)),'VEC4',5123);attributes.WEIGHTS_0=b.add(sources.flatMap(id=>o.rig.weights.slice(id*4,id*4+4)),'VEC4');}
            const targets=o.morphTargets?.map(p=>({POSITION:b.add(sources.flatMap(id=>p.slice(id*3,id*3+3)),'VEC3')}));
            const primitives=[...groups].map(([material,ids])=>({attributes,indices:b.add(ids,'SCALAR',5125),material,mode:4,...(targets?{targets}:{})}));
            g.nodes[oi].mesh=g.meshes.length;g.meshes.push({name:o.name,primitives,...(targets?{weights:o.morphWeights||targets.map(()=>0)}:{})});
        }
        if(o.rig&&skins){const rig=o.rig;let joints;if(rig.externalJoints){joints=rig.externalJoints.map(id=>{const index=objectMap.get(id);if(index===undefined)throw Error('Missing external skin joint during export');return index;});}else{const offset=g.nodes.length;joints=rig.bones.map((_,i)=>offset+i);rig.bones.forEach((bone,i)=>g.nodes.push({name:bone.name,translation:bone.position,rotation:bone.rotation,scale:bone.scale||[1,1,1]}));rig.bones.forEach((bone,i)=>{const parent=bone.parent>=0?offset+bone.parent:oi;(g.nodes[parent].children||=[]).push(offset+i);if(animation&&bone.keys?.length){const keys=[...bone.keys].sort((a,b)=>a.frame-b.frame),times=keys.map(k=>k.frame/doc.animation.fps);channel(offset+i,'translation',times,keys.flatMap(k=>k.position||bone.position));channel(offset+i,'rotation',times,keys.flatMap(k=>k.rotation||bone.rotation));channel(offset+i,'scale',times,keys.flatMap(k=>k.scale||bone.scale||[1,1,1]));}});}const skinsList=g.skins||=[];g.nodes[oi].skin=skinsList.length;skinsList.push({name:`${o.name} skin`,joints,inverseBindMatrices:b.add(rig.inverseBind.flat(),'MAT4')});}
        if(animation){if(o.tracks?.length){for(const t of o.tracks)channel(oi,t.path,t.times,t.values,t.interpolation,t.path==='weights'?'SCALAR':undefined);}else if(o.keys?.length){const first=Math.min(...o.keys.map(k=>k.frame)),last=Math.max(...o.keys.map(k=>k.frame)),frames=[];for(let f=first;f<=last;f++)frames.push(f);if(frames.at(-1)!==last)frames.push(last);const poses=frames.map(f=>sampleTransform(o,f,doc.animation.interpolation)),times=frames.map(f=>f/doc.animation.fps),mode=doc.animation.interpolation==='step'?'STEP':'LINEAR';channel(oi,'translation',times,poses.flatMap(p=>p.position),mode);channel(oi,'rotation',times,poses.flatMap(p=>quatEuler(p.rotation)),mode);channel(oi,'scale',times,poses.flatMap(p=>p.scale),mode);}}
    });if(anim.channels.length)g.animations=[anim];g.extensionsUsed=[...used];if(!g.extensionsUsed.length)delete g.extensionsUsed;const bytes=b.bytes();g.buffers=bytes.length?[{byteLength:bytes.length}]:[];if(!bytes.length){delete g.buffers;delete g.bufferViews;delete g.accessors;delete g.meshes;}if(!binary){if(bytes.length)g.buffers[0].uri='data:application/octet-stream;base64,'+bytesBase64(bytes);return g;}return packGLB(g,bytes);}
export function packGLB(json,bin){const j=new TextEncoder().encode(JSON.stringify(json)),jl=(j.length+3)&~3,bl=(bin.length+3)&~3,total=12+8+jl+(bl?8+bl:0),out=new Uint8Array(total),v=new DataView(out.buffer);v.setUint32(0,0x46546c67,true);v.setUint32(4,2,true);v.setUint32(8,total,true);v.setUint32(12,jl,true);v.setUint32(16,0x4e4f534a,true);out.fill(32,20,20+jl);out.set(j,20);if(bl){const p=20+jl;v.setUint32(p,bl,true);v.setUint32(p+4,0x004e4942,true);out.set(bin,p+8);}return out;}
