import {vertex,validateMesh} from '../geometry/mesh.js';
import {worldMatrix} from '../scene/document.js';
import {transformPoint} from '../core/math.js';
import {reversesWinding} from '../render/compile.js';
const isVisible=(doc,o)=>o.visible!==false&&(!o.parent||isVisible(doc,doc.objects.find(p=>p.id===o.parent)||{visible:true}));
/** ASCII PLY with arbitrary polygon faces; supports scalar vertex properties and a leading vertex-index face list. */
export function parsePLY(text){const lines=text.split(/\r?\n/);if(lines[0].trim()!=='ply'||!lines[1].startsWith('format ascii 1.0'))throw Error('Only ASCII PLY 1.0 is supported');let vertexCount=0,faceCount=0,props=[],element='',end=-1;for(let i=2;i<lines.length;i++){const p=lines[i].trim().split(/\s+/);if(p[0]==='element'){if(!['vertex','face'].includes(p[1])||p[1]==='vertex'&&element==='face')throw Error('Only vertex-then-face PLY elements are supported');element=p[1];if(element==='vertex')vertexCount=Number(p[2]);if(element==='face')faceCount=Number(p[2]);}if(p[0]==='property'&&element==='vertex'){if(p[1]==='list')throw Error('PLY vertex list properties are unsupported');props.push(p.at(-1));}if(p[0]==='end_header'){end=i+1;break;}}if(end<0||!Number.isInteger(vertexCount)||vertexCount<0||vertexCount>1000000||!Number.isInteger(faceCount)||faceCount<0||faceCount>1000000)throw Error('Invalid PLY header');const axes=['x','y','z'].map(k=>props.indexOf(k));if(axes.some(i=>i<0))throw Error('PLY lacks XYZ coordinates');const positions=[],faces=[],uvs=[];for(let i=0;i<vertexCount;i++){const p=lines[end+i]?.trim().split(/\s+/).map(Number);if(!p||p.length<props.length||!p.every(Number.isFinite))throw Error('Truncated or invalid PLY vertex');positions.push(...axes.map(k=>p[k]));}for(let i=0;i<faceCount;i++){const p=lines[end+vertexCount+i]?.trim().split(/\s+/).map(Number);if(!p||p[0]<3||p.length<p[0]+1)throw Error('Invalid PLY face');faces.push(p.slice(1,p[0]+1));}return validateMesh({positions,faces,uvs,smooth:true});}
export function exportPLY(doc,geometry){const positions=[],faces=[];for(const o of doc.objects.filter(o=>isVisible(doc,o))){const m=geometry.get(o),world=worldMatrix(doc,o),offset=positions.length/3;for(let i=0;i<m.positions.length/3;i++)positions.push(...transformPoint(world,vertex(m,i)));for(const f of m.faces)faces.push((reversesWinding(world)?[...f].reverse():f).map(i=>i+offset));}return `ply\nformat ascii 1.0\ncomment Aureon Studio\nelement vertex ${positions.length/3}\nproperty float x\nproperty float y\nproperty float z\nelement face ${faces.length}\nproperty list uint int vertex_indices\nend_header\n`+Array.from({length:positions.length/3},(_,i)=>positions.slice(i*3,i*3+3).join(' ')).join('\n')+'\n'+faces.map(f=>`${f.length} ${f.join(' ')}`).join('\n')+'\n';}
/** OpenUSD ASCII mesh snapshot. Standard indexed UV primvar and transforms baked.
 * It does not claim composition, variants, skeletal or simulation-cache support. */
export function exportUSDA(doc,geometry){let text='#usda 1.0\n(\n    defaultPrim = "Scene"\n    metersPerUnit = 1\n    upAxis = "Y"\n)\n\ndef Xform "Scene" {\n';for(let oi=0;oi<doc.objects.length;oi++){const o=doc.objects[oi];if(!isVisible(doc,o))continue;const m=geometry.get(o);if(!m.faces.length)continue;const matrix=worldMatrix(doc,o),name=(o.name.replace(/[^A-Za-z0-9_]/g,'_')||'Mesh')+'_'+oi;const faces=reversesWinding(matrix)?m.faces.map(f=>[...f].reverse()):m.faces;const points=Array.from({length:m.positions.length/3},(_,i)=>'('+transformPoint(matrix,vertex(m,i)).join(', ')+')');text+=`    def Mesh "${name}" {\n        point3f[] points = [${points.join(', ')}]\n        int[] faceVertexCounts = [${faces.map(f=>f.length).join(', ')}]\n        int[] faceVertexIndices = [${faces.flat().join(', ')}]\n        uniform token subdivisionScheme = "none"\n`;if(m.uvs?.length)text+=`        texCoord2f[] primvars:st = [${Array.from({length:m.uvs.length/2},(_,i)=>'('+m.uvs.slice(i*2,i*2+2).join(', ')+')').join(', ')}] (\n            interpolation = "vertex"\n        )\n`;text+='    }\n';}return text+'}\n';}
